"use client";import Header from"../components/Header";

import { FormEvent, useEffect, useMemo, useState } from "react";
import PreviewAuthGuard from "../preview-auth-guard";

const apiBase=process.env.NEXT_PUBLIC_SUBIL_API_URL?.replace(/\/$/,"")||"";
type Filter="all"|"draft"|"approved"|"partially_received"|"received"|"overdue";
type Line={id:string;item_id:string;sku:string;name:string;unit:string;ordered_quantity:number|string;received_quantity:number|string;unit_cost:number|string};
type Order={id:string;po_number:string;supplier_name:string;supplier_id:string;warehouse_name:string;warehouse_id:string;status:string;expected_at?:string;subtotal:number|string;item_count:number;ordered_units:number|string;received_units:number|string;items:Line[];created_at:string};
type Supplier={id:string;name:string;mobile?:string};type Item={id:string;sku:string;name:string;unit_cost:number|string;balances?:{warehouse_id:string}[]};
type Stats={open_orders:number;pending_approval:number;awaiting_receipt:number;overdue:number;received_this_month:number;open_value:number|string};
const seedSuppliers:Supplier[]=[{id:"SUP-1",name:"مؤسسة نقاء المياه",mobile:"0500000001"},{id:"SUP-2",name:"شركة حلول الفلاتر",mobile:"0500000002"}];
const seedItems:Item[]=[{id:"ITEM-1",sku:"MEM-75GPD",name:"شمعة ممبرين 75 GPD",unit_cost:42,balances:[{warehouse_id:"main-riyadh"}]},{id:"ITEM-2",sku:"RO-7-STAGE",name:"جهاز تحلية 7 مراحل",unit_cost:330,balances:[{warehouse_id:"main-riyadh"}]}];
const seedOrders:Order[]=[{id:"PO-1",po_number:"PO-2026-014",supplier_name:"مؤسسة نقاء المياه",supplier_id:"SUP-1",warehouse_name:"المستودع الرئيسي",warehouse_id:"main-riyadh",status:"approved",expected_at:"2026-09-18T09:00:00Z",subtotal:4200,item_count:1,ordered_units:100,received_units:0,created_at:"2026-09-15T09:00:00Z",items:[{id:"LINE-1",item_id:"ITEM-1",sku:"MEM-75GPD",name:"شمعة ممبرين 75 GPD",unit:"حبة",ordered_quantity:100,received_quantity:0,unit_cost:42}]},{id:"PO-2",po_number:"PO-2026-013",supplier_name:"شركة حلول الفلاتر",supplier_id:"SUP-2",warehouse_name:"المستودع الرئيسي",warehouse_id:"main-riyadh",status:"draft",subtotal:3300,item_count:1,ordered_units:10,received_units:0,created_at:"2026-09-16T07:00:00Z",items:[{id:"LINE-2",item_id:"ITEM-2",sku:"RO-7-STAGE",name:"جهاز تحلية 7 مراحل",unit:"جهاز",ordered_quantity:10,received_quantity:0,unit_cost:330}]}];
const initialStats:Stats={open_orders:2,pending_approval:1,awaiting_receipt:1,overdue:0,received_this_month:6,open_value:7500};
const money=(v:number|string)=>Number(v||0).toLocaleString("ar-SA",{minimumFractionDigits:2,maximumFractionDigits:2});const num=(v:number|string)=>Number(v||0).toLocaleString("ar-SA",{maximumFractionDigits:2});
const labels:Record<string,string>={draft:"مسودة",approved:"معتمد",partially_received:"مستلم جزئيًا",received:"مستلم",cancelled:"ملغي"};

export default function PurchasingPage(){
 const [orders,setOrders]=useState<Order[]>(apiBase?[]:seedOrders),[suppliers,setSuppliers]=useState<Supplier[]>(apiBase?[]:seedSuppliers),[items,setItems]=useState<Item[]>(apiBase?[]:seedItems),[stats,setStats]=useState<Stats>(initialStats),[filter,setFilter]=useState<Filter>("all"),[query,setQuery]=useState(""),[loading,setLoading]=useState(Boolean(apiBase)),[error,setError]=useState(""),[reload,setReload]=useState(0),[modal,setModal]=useState<"supplier"|"order"|null>(null),[receipt,setReceipt]=useState<Order|null>(null),[saving,setSaving]=useState(false),[canManage,setCanManage]=useState(!apiBase);
 useEffect(()=>setCanManage(!apiBase||["branch_manager","admin","super_admin"].includes(sessionStorage.getItem("subil_role")||"")),[]);
 useEffect(()=>{if(!apiBase)return;const token=sessionStorage.getItem("subil_session"),headers={Authorization:`Bearer ${token}`};setLoading(true);Promise.all([fetch(`${apiBase}/api/v1/purchasing/orders?status=${filter}&q=${encodeURIComponent(query)}&limit=50`,{headers}),fetch(`${apiBase}/api/v1/purchasing/stats`,{headers}),fetch(`${apiBase}/api/v1/purchasing/suppliers?limit=100`,{headers}),fetch(`${apiBase}/api/v1/inventory?limit=100`,{headers})]).then(async rs=>{if(rs.some(r=>!r.ok))throw new Error("تعذر تحميل بيانات المشتريات.");return Promise.all(rs.map(r=>r.json()));}).then(([o,s,p,i])=>{setOrders(o.orders||[]);setStats(s.stats);setSuppliers(p.suppliers||[]);setItems(i.items||[]);setError("");}).catch(e=>setError(e instanceof Error?e.message:"تعذر التحميل.")).finally(()=>setLoading(false));},[filter,query,reload]);
 const shown=useMemo(()=>apiBase?orders:orders.filter(o=>(filter==="all"||(filter==="overdue"?Boolean(o.expected_at&&new Date(o.expected_at)<new Date()&&["approved","partially_received"].includes(o.status)):o.status===filter))&&(!query||`${o.po_number} ${o.supplier_name}`.includes(query))),[orders,filter,query]);
 async function post(path:string,payload:object){if(!apiBase)return null;const token=sessionStorage.getItem("subil_session"),res=await fetch(`${apiBase}${path}`,{method:"POST",headers:{"content-type":"application/json",Authorization:`Bearer ${token}`},body:JSON.stringify(payload)}),data=await res.json();if(!res.ok)throw new Error(data.error==="purchase_order_conflict"?"لا يمكن تنفيذ الإجراء في حالة الطلب الحالية.":"تعذر حفظ العملية.");return data;}
 async function saveSupplier(e:FormEvent<HTMLFormElement>){e.preventDefault();const d=new FormData(e.currentTarget),supplier={name:String(d.get("name")||""),contactName:String(d.get("contactName")||""),mobile:String(d.get("mobile")||"")};setSaving(true);try{if(apiBase)await post("/api/v1/purchasing/suppliers",supplier);else setSuppliers(v=>[{id:`SUP-${Date.now()}`,...supplier},...v]);setModal(null);setReload(v=>v+1);}catch(e){setError(e instanceof Error?e.message:"تعذر الحفظ.");}finally{setSaving(false);}}
 async function saveOrder(e:FormEvent<HTMLFormElement>){e.preventDefault();const d=new FormData(e.currentTarget),item=items.find(i=>i.id===d.get("itemId")),payload={poNumber:String(d.get("poNumber")||""),supplierId:String(d.get("supplierId")||""),warehouseId:String(d.get("warehouseId")||"main-riyadh"),expectedAt:String(d.get("expectedAt")||"")||undefined,notes:String(d.get("notes")||""),items:[{itemId:String(d.get("itemId")||""),quantity:Number(d.get("quantity")),unitCost:Number(d.get("unitCost"))}]};setSaving(true);try{if(apiBase)await post("/api/v1/purchasing/orders",payload);else{const supplier=suppliers.find(s=>s.id===payload.supplierId)!;setOrders(v=>[{id:`PO-${Date.now()}`,po_number:payload.poNumber,supplier_id:supplier.id,supplier_name:supplier.name,warehouse_id:payload.warehouseId,warehouse_name:"المستودع الرئيسي",status:"draft",expected_at:payload.expectedAt,subtotal:payload.items[0].quantity*payload.items[0].unitCost,item_count:1,ordered_units:payload.items[0].quantity,received_units:0,created_at:new Date().toISOString(),items:[{id:`LINE-${Date.now()}`,item_id:item!.id,sku:item!.sku,name:item!.name,unit:"حبة",ordered_quantity:payload.items[0].quantity,received_quantity:0,unit_cost:payload.items[0].unitCost}]},...v]);}setModal(null);setReload(v=>v+1);}catch(e){setError(e instanceof Error?e.message:"تعذر الحفظ.");}finally{setSaving(false);}}
 async function approve(order:Order){setSaving(true);try{if(apiBase)await post(`/api/v1/purchasing/orders/${order.id}/approve`,{});else setOrders(v=>v.map(o=>o.id===order.id?{...o,status:"approved"}:o));setReload(v=>v+1);}catch(e){setError(e instanceof Error?e.message:"تعذر الاعتماد.");}finally{setSaving(false);}}
 async function receive(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!receipt)return;const d=new FormData(e.currentTarget),lines=receipt.items.map(line=>({purchaseOrderItemId:line.id,quantity:Number(d.get(line.id)||0)})).filter(line=>line.quantity>0);if(!lines.length){setError("أدخل كمية مستلمة واحدة على الأقل.");return;}setSaving(true);try{if(apiBase)await post(`/api/v1/purchasing/orders/${receipt.id}/receive`,{lines,notes:String(d.get("notes")||"")});else setOrders(v=>v.map(o=>o.id===receipt.id?{...o,status:"received",received_units:o.ordered_units,items:o.items.map(i=>({...i,received_quantity:i.ordered_quantity}))}:o));setReceipt(null);setReload(v=>v+1);}catch(e){setError(e instanceof Error?e.message:"تعذر الاستلام.");}finally{setSaving(false);}}
 const cards=[{title:"الطلبات المفتوحة",value:stats.open_orders,f:"all"},{title:"بانتظار الاعتماد",value:stats.pending_approval,f:"draft"},{title:"بانتظار الاستلام",value:stats.awaiting_receipt,f:"approved"},{title:"متأخرة",value:stats.overdue,f:"overdue"},{title:"قيمة المفتوح",value:`${money(stats.open_value)} ر.س`,f:"all"}];
 return <PreviewAuthGuard><main className="customers-page purchasing-page"><Header active="/purchasing"/><div className="customers-wrap">
 <div className="demo-notice"><span>نسخة المعاينة</span> الاستلام يحدّث المخزون تلقائيًا مع سجل تدقيق كامل.</div><div className="page-head"><div><p>التوريد والمستودعات</p><h1>مركز المشتريات</h1><span>الموردون وأوامر الشراء والاعتماد والاستلام</span></div>{canManage&&<div className="purchasing-head-actions"><button className="secondary-button" onClick={()=>setModal("supplier")}>مورد جديد</button><button className="primary-button" onClick={()=>setModal("order")}><span>+</span>أمر شراء</button></div>}</div>
 <section className="inventory-stats">{cards.map(c=><button key={c.title} className={filter===c.f?"active":""} onClick={()=>setFilter(c.f as Filter)}><span>{c.title}</span><strong>{typeof c.value==="number"?num(c.value):c.value}</strong></button>)}</section>{error&&<div className="api-error">{error}</div>}
 <section className="panel purchasing-worklist"><div className="customers-toolbar"><div><h2>أوامر الشراء</h2><p>{loading?"جارٍ التحميل...":`${shown.length.toLocaleString("ar-SA")} طلب`}</p></div><div className="jobs-toolbar-actions"><select value={filter} onChange={e=>setFilter(e.target.value as Filter)}><option value="all">كل الطلبات</option><option value="draft">مسودة</option><option value="approved">معتمد</option><option value="partially_received">استلام جزئي</option><option value="received">مستلم</option><option value="overdue">متأخر</option></select><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="رقم الطلب أو المورد"/></div></div><div className="table-wrap"><table><thead><tr><th>الطلب</th><th>المورد</th><th>المستودع</th><th>الاستلام</th><th>القيمة</th><th>الحالة</th><th>الإجراء</th></tr></thead><tbody>{shown.map(o=><tr key={o.id}><td><strong dir="ltr">{o.po_number}</strong><small>{o.item_count} صنف</small></td><td><strong>{o.supplier_name}</strong></td><td>{o.warehouse_name}</td><td><strong>{num(o.received_units)} / {num(o.ordered_units)}</strong></td><td><strong>{money(o.subtotal)} ر.س</strong></td><td><span className={`purchase-state ${o.status}`}>{labels[o.status]||o.status}</span></td><td><div className="inventory-actions">{canManage&&o.status==="draft"&&<button disabled={saving} onClick={()=>approve(o)}>اعتماد</button>}{canManage&&["approved","partially_received"].includes(o.status)&&<button onClick={()=>setReceipt(o)}>استلام</button>}</div></td></tr>)}</tbody></table></div></section>
 {modal==="supplier"&&<div className="modal-backdrop"><section className="customer-modal"><div className="modal-head"><div><h2>إضافة مورد</h2><p>بيانات التواصل الأساسية</p></div><button onClick={()=>setModal(null)}>×</button></div><form onSubmit={saveSupplier}><label>اسم المورد<input name="name" required minLength={2}/></label><label>اسم جهة الاتصال<input name="contactName"/></label><label>رقم الجوال<input name="mobile" dir="ltr"/></label><div className="modal-actions"><button type="button" className="secondary-button" onClick={()=>setModal(null)}>إلغاء</button><button className="primary-button" disabled={saving}>حفظ المورد</button></div></form></section></div>}
 {modal==="order"&&<div className="modal-backdrop"><section className="customer-modal purchasing-modal"><div className="modal-head"><div><h2>إنشاء أمر شراء</h2><p>سيُحفظ كمسودة للمراجعة</p></div><button onClick={()=>setModal(null)}>×</button></div><form onSubmit={saveOrder}><label>رقم الأمر<input name="poNumber" required placeholder="PO-2026-015"/></label><label>المورد<select name="supplierId" required>{suppliers.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label>الصنف<select name="itemId" required onChange={e=>{const i=items.find(x=>x.id===e.target.value),cost=e.currentTarget.form?.elements.namedItem("unitCost") as HTMLInputElement;if(i&&cost)cost.value=String(i.unit_cost)}}>{items.map(i=><option key={i.id} value={i.id}>{i.name} · {i.sku}</option>)}</select></label><label>المستودع<input name="warehouseId" defaultValue={items[0]?.balances?.[0]?.warehouse_id||"main-riyadh"}/></label><label>الكمية<input name="quantity" required type="number" min="0.01" step="0.01"/></label><label>تكلفة الوحدة<input name="unitCost" required type="number" min="0" step="0.01" defaultValue={Number(items[0]?.unit_cost||0)}/></label><label>موعد التوريد<input name="expectedAt" type="datetime-local"/></label><label>ملاحظات<input name="notes"/></label><div className="modal-actions"><button type="button" className="secondary-button" onClick={()=>setModal(null)}>إلغاء</button><button className="primary-button" disabled={saving}>إنشاء الطلب</button></div></form></section></div>}
 {receipt&&<div className="modal-backdrop"><section className="customer-modal purchasing-modal"><div className="modal-head"><div><h2>استلام أمر {receipt.po_number}</h2><p>لن يسمح النظام بتجاوز الكمية المطلوبة</p></div><button onClick={()=>setReceipt(null)}>×</button></div><form onSubmit={receive}>{receipt.items.map(line=><label key={line.id}>{line.name} · المتبقي {num(Number(line.ordered_quantity)-Number(line.received_quantity))}<input name={line.id} type="number" min="0" max={Number(line.ordered_quantity)-Number(line.received_quantity)} step="0.01" defaultValue={Number(line.ordered_quantity)-Number(line.received_quantity)}/></label>)}<label>ملاحظات الاستلام<input name="notes"/></label><div className="modal-actions"><button type="button" className="secondary-button" onClick={()=>setReceipt(null)}>إلغاء</button><button className="primary-button" disabled={saving}>تأكيد الاستلام</button></div></form></section></div>}
 </div></main></PreviewAuthGuard>;
}
