import test from'node:test';import assert from'node:assert/strict';import{routePersistentRequest}from'../src/http/persistent-router.mjs';import{markCartRecovered,runAbandonedCartRecovery,upsertAbandonedCart}from'../src/marketing/abandoned-carts.mjs';function tx(handler){const calls=[];return{calls,db:{query:async()=>({rows:[]}),connect:async()=>({query:async(sql,p=[])=>{calls.push({sql,params:p});if(['BEGIN','COMMIT','ROLLBACK'].includes(sql))return{rows:[]};return handler(sql,p)},release(){}})}}}
test('support reads abandoned cart counters',async()=>{const db={query:async sql=>{assert.match(sql,/at_risk_value/);return{rows:[{active:5,recovered:2}]}}};const r=await routePersistentRequest({method:'GET',url:'/api/v1/marketing/abandoned-carts/stats',role:'support',db});assert.equal(r.status,200);assert.equal(r.data.stats.active,5)});
test('manager filters active abandoned carts',async()=>{const db={query:async(sql,p)=>{assert.match(sql,/abandoned_carts/);assert.deepEqual(p,['active',10,0]);return{rows:[{id:'a1',total_count:3}]}}};const r=await routePersistentRequest({method:'GET',url:'/api/v1/marketing/abandoned-carts',role:'branch_manager',context:{status:'active',limit:'10'},db});assert.equal(r.status,200);assert.equal(r.data.pagination.total,3)});
test('cart import requires contact and valid value',async()=>{const db={connect:async()=>{throw new Error('must not connect')},query:async()=>({rows:[]})};const r=await routePersistentRequest({method:'POST',url:'/api/v1/marketing/abandoned-carts',role:'branch_manager',context:{userId:'m1'},body:{externalCartId:'c1',cartValue:-1,abandonedAt:'2026-09-16'},db});assert.equal(r.status,400)});
test('cart upsert is idempotent and audited',async()=>{const{db,calls}=tx(async(sql)=>{if(/INSERT INTO abandoned_carts/.test(sql))return{rows:[{id:'a1',status:'open'}]};if(/INSERT INTO audit_log/.test(sql))return{rows:[]};throw new Error(`unexpected ${sql}`)});const cart=await upsertAbandonedCart(db,{externalCartId:'wc1',mobile:'0500000000',cartValue:500,abandonedAt:'2026-09-16',actorUserId:'m1'});assert.equal(cart.id,'a1');assert.ok(calls.some(c=>/ON CONFLICT/.test(c.sql)));assert.ok(calls.some(c=>c.params[1]==='marketing.abandoned_cart_upserted'))});
test('recovery run queues only eligible locked carts',async()=>{const{db,calls}=tx(async(sql)=>{if(/FOR UPDATE SKIP LOCKED/.test(sql))return{rows:[{id:'a1',customer_id:'u1',customer_name:'عميل',mobile:'0500000000',email:null,cart_value:'650',currency:'SAR',checkout_url:'url',items:[],reminder_count:0}]};if(/INSERT INTO notification_events|UPDATE abandoned_carts|INSERT INTO audit_log/.test(sql))return{rows:[]};throw new Error(`unexpected ${sql}`)});const r=await runAbandonedCartRecovery(db,{actorUserId:'m1',limit:20});assert.deepEqual(r,{scanned:1,queued:1});assert.ok(calls.some(c=>/24 hours/.test(c.sql)));assert.ok(calls.some(c=>/notification_events/.test(c.sql)&&c.params[1].includes('whatsapp')))});
test('recovery run is safe when queue is empty',async()=>{const{db,calls}=tx(async sql=>{if(/FOR UPDATE SKIP LOCKED/.test(sql))return{rows:[]};if(/INSERT INTO audit_log/.test(sql))return{rows:[]};throw new Error(`unexpected ${sql}`)});const r=await runAbandonedCartRecovery(db,{actorUserId:'m1'});assert.equal(r.queued,0);assert.ok(!calls.some(c=>/notification_events/.test(c.sql)))});
test('mark recovered closes only an active cart',async()=>{const{db,calls}=tx(async sql=>{if(/UPDATE abandoned_carts SET status='recovered'/.test(sql))return{rows:[{id:'a1',status:'recovered',cart_value:'500'}]};if(/INSERT INTO audit_log/.test(sql))return{rows:[]};throw new Error(`unexpected ${sql}`)});const cart=await markCartRecovered(db,{cartId:'a1',orderId:null,actorUserId:'m1'});assert.equal(cart.status,'recovered');assert.ok(calls.some(c=>c.params[1]==='marketing.abandoned_cart_recovered'))});
test('recovery run validates its batch limit',async()=>{const db={connect:async()=>{throw new Error('must not connect')},query:async()=>({rows:[]})};const r=await routePersistentRequest({method:'POST',url:'/api/v1/marketing/abandoned-carts/recovery/run',role:'branch_manager',context:{userId:'m1'},body:{limit:501},db});assert.equal(r.status,400)});
