import test from'node:test';import assert from'node:assert/strict';import{routePersistentRequest}from'../src/http/persistent-router.mjs';import{createCareSuggestion,createKnowledgeArticle,reviewSuggestion,useSuggestion}from'../src/ai/copilot.mjs';
function tx(handler){const calls=[];return{calls,db:{query:async()=>({rows:[]}),connect:async()=>({query:async(sql,p=[])=>{calls.push({sql,params:p});if(['BEGIN','COMMIT','ROLLBACK'].includes(sql))return{rows:[]};return handler(sql,p)},release(){}})}}}
test('copilot grounds reply in an approved knowledge article',async()=>{const{db}=tx(async sql=>{if(/SELECT cc.id/.test(sql))return{rows:[{id:'c1',channel:'whatsapp'}]};if(/FROM conversation_messages/.test(sql))return{rows:[{direction:'inbound',body:'كم مدة ضمان الفلتر؟'}]};if(/FROM ai_knowledge_articles/.test(sql))return{rows:[{id:'k1',title:'ضمان الفلاتر',category:'warranty',keywords:['ضمان'],content:'مدة الضمان سنتان حسب شروط المنتج.'}]};if(/INSERT INTO ai_suggestions/.test(sql))return{rows:[{id:'a1',generated_text:'مدة الضمان سنتان',risk_level:'high',confidence:.7}]};if(/INSERT INTO audit_log/.test(sql))return{rows:[]};throw new Error(`unexpected ${sql}`)});const result=await createCareSuggestion(db,{conversationId:'c1',actorUserId:'u1'});assert.equal(result.risk_level,'high');assert.equal(result.id,'a1')});
test('copilot uses safe fallback when no knowledge matches',async()=>{const{db,calls}=tx(async sql=>{if(/SELECT cc.id/.test(sql))return{rows:[{id:'c1',channel:'webchat'}]};if(/FROM conversation_messages/.test(sql))return{rows:[{direction:'inbound',body:'سؤال غير معروف'}]};if(/FROM ai_knowledge_articles/.test(sql))return{rows:[]};if(/INSERT INTO ai_suggestions/.test(sql))return{rows:[{id:'a1',confidence:.35,risk_level:'medium'}]};if(/INSERT INTO audit_log/.test(sql))return{rows:[]};throw new Error(`unexpected ${sql}`)});await createCareSuggestion(db,{conversationId:'c1',actorUserId:'u1'});const insert=calls.find(x=>/INSERT INTO ai_suggestions/.test(x.sql));assert.match(insert.params[3],/المعلومة الدقيقة/);assert.equal(insert.params[6],'[]')});
test('manager approval is atomic and audited',async()=>{const{db,calls}=tx(async sql=>{if(/UPDATE ai_suggestions SET status/.test(sql))return{rows:[{id:'a1',status:'approved',risk_level:'low'}]};if(/INSERT INTO audit_log/.test(sql))return{rows:[]};throw new Error(`unexpected ${sql}`)});const result=await reviewSuggestion(db,{suggestionId:'a1',decision:'approved',actorUserId:'m1'});assert.equal(result.status,'approved');assert.ok(calls.some(x=>x.params[1]==='ai.suggestion_approved'))});
test('only an approved suggestion can become a queued reply',async()=>{const{db}=tx(async sql=>{if(/SELECT \* FROM ai_suggestions/.test(sql))return{rows:[{id:'a1',status:'draft',conversation_id:'c1'}]};throw new Error(`unexpected ${sql}`)});await assert.rejects(()=>useSuggestion(db,{suggestionId:'a1',actorUserId:'u1'}),/not approved/)});
test('approved suggestion is used once with audit linkage',async()=>{const{db,calls}=tx(async sql=>{if(/SELECT \* FROM ai_suggestions/.test(sql))return{rows:[{id:'a1',status:'approved',conversation_id:'c1',generated_text:'رد موثق'}]};if(/SELECT \* FROM customer_conversations/.test(sql))return{rows:[{id:'c1',status:'open'}]};if(/INSERT INTO conversation_messages/.test(sql))return{rows:[{id:'m1',sent_at:'2026-09-16'}]};if(/UPDATE customer_conversations|UPDATE ai_suggestions|INSERT INTO audit_log/.test(sql))return{rows:[]};throw new Error(`unexpected ${sql}`)});const result=await useSuggestion(db,{suggestionId:'a1',actorUserId:'u1'});assert.equal(result.suggestion.status,'used');assert.ok(calls.some(x=>String(x.params[4]||'').includes('aiSuggestionId')))});
test('knowledge creation records its approver and audit',async()=>{const{db}=tx(async sql=>{if(/INSERT INTO ai_knowledge_articles/.test(sql))return{rows:[{id:'k1',status:'approved'}]};if(/INSERT INTO audit_log/.test(sql))return{rows:[]};throw new Error(`unexpected ${sql}`)});const article=await createKnowledgeArticle(db,{title:'الشحن',category:'delivery',content:'التوصيل داخل الرياض',keywords:['شحن'],status:'approved',actorUserId:'m1'});assert.equal(article.id,'k1')});
test('support can suggest but cannot approve or manage knowledge',async()=>{const db={query:async()=>({rows:[]}),connect:async()=>{throw new Error('must not connect')}};const approve=await routePersistentRequest({method:'POST',url:'/api/v1/ai/suggestions/a1/approve',role:'support',context:{userId:'u1'},db});const knowledge=await routePersistentRequest({method:'POST',url:'/api/v1/ai/knowledge',role:'support',context:{userId:'u1'},body:{title:'عنوان',content:'محتوى'},db});assert.equal(approve.status,403);assert.equal(knowledge.status,403)});
test('knowledge endpoint validates content before database access',async()=>{const db={query:async()=>{throw new Error('must not query')}};const result=await routePersistentRequest({method:'POST',url:'/api/v1/ai/knowledge',role:'branch_manager',context:{userId:'m1'},body:{title:'x',content:''},db});assert.equal(result.status,400)});
