import test from'node:test';import assert from'node:assert/strict';import{routePersistentRequest}from'../src/http/persistent-router.mjs';import{createDispatchRecommendation,reviewDispatchRecommendation,scoreDispatchCandidates}from'../src/ai/dispatch.mjs';
function tx(handler,directHandler=()=>({rows:[]})){const calls=[];return{calls,db:{query:async(sql,p=[])=>{calls.push({sql,params:p});return directHandler(sql,p)},connect:async()=>({query:async(sql,p=[])=>{calls.push({sql,params:p});if(['BEGIN','COMMIT','ROLLBACK'].includes(sql))return{rows:[]};return handler(sql,p)},release(){}})}}}
test('candidate scoring rewards proximity rating and low workload',()=>{const ranked=scoreDispatchCandidates([{technician_id:'busy',distance_km:'1',avg_rating:'4.9',jobs_in_window:3},{technician_id:'best',distance_km:'2',avg_rating:'4.8',jobs_in_window:0},{technician_id:'far',distance_km:'20',avg_rating:'5',jobs_in_window:0}]);assert.equal(ranked[0].technician_id,'best');assert.ok(ranked[0].score>ranked[1].score);assert.match(ranked[0].reasons.join(' '),/المهارة/)});
test('unknown location produces an explainable risk',()=>{const[result]=scoreDispatchCandidates([{technician_id:'t1',distance_km:null,avg_rating:'4',jobs_in_window:0}]);assert.ok(result.risks.includes('المسافة غير معروفة'));assert.match(result.reasons[0],/غير متاح/)});
test('recommendation expires old pending tenant record and stores ranked candidates',async()=>{const candidates=[{technician_id:'t1',distance_km:'2',avg_rating:'4.8',jobs_in_window:0}];const direct=async sql=>{if(/FROM service_jobs j LEFT JOIN service_locations/.test(sql))return{rows:[{id:'j1',organization_id:'00000000-0000-4000-8000-000000000001',city_id:'riyadh',status:'pending_assignment',scheduled_at:'2026-09-16T10:00:00Z',service_duration_minutes:60}]};if(/FROM technicians t/.test(sql))return{rows:candidates};throw new Error(`unexpected direct ${sql}`)};const{db,calls}=tx(async(sql)=>{if(/UPDATE ai_dispatch_recommendations SET status='expired'/.test(sql))return{rows:[]};if(/INSERT INTO ai_dispatch_recommendations/.test(sql))return{rows:[{id:'r1',risk_level:'low'}]};if(/INSERT INTO audit_log/.test(sql))return{rows:[]};throw new Error(`unexpected tx ${sql}`)},direct);const result=await createDispatchRecommendation(db,{jobId:'j1',actorUserId:'d1'});assert.equal(result.candidates[0].technician_id,'t1');assert.ok(calls.some(x=>/organization_id=\$1 AND job_id=\$2/.test(x.sql)))});
test('recommendation safely reports when no candidate exists',async()=>{const direct=async sql=>/FROM service_jobs j LEFT JOIN/.test(sql)?{rows:[{id:'j1',organization_id:'00000000-0000-4000-8000-000000000001',city_id:'riyadh',status:'pending_assignment',scheduled_at:'2026-09-16T10:00:00Z',service_duration_minutes:60}]}:{rows:[]};const{db}=tx(async sql=>{if(/UPDATE ai_dispatch/.test(sql))return{rows:[]};if(/INSERT INTO ai_dispatch/.test(sql))return{rows:[{id:'r1',risk_level:'high',explanation:'لا يوجد فني'}]};if(/INSERT INTO audit_log/.test(sql))return{rows:[]};throw new Error(`unexpected ${sql}`)},direct);const result=await createDispatchRecommendation(db,{jobId:'j1',actorUserId:'d1'});assert.equal(result.recommendation.risk_level,'high');assert.equal(result.candidates.length,0)});
test('dispatcher can approve only a listed candidate',async()=>{const{db,calls}=tx(async sql=>{if(/SELECT \* FROM ai_dispatch/.test(sql))return{rows:[{id:'r1',job_id:'j1',candidates:[{technician_id:'t1'}],recommended_technician_id:'t1'}]};if(/UPDATE ai_dispatch_recommendations SET status/.test(sql))return{rows:[{id:'r1',status:'approved',selected_technician_id:'t1'}]};if(/INSERT INTO audit_log/.test(sql))return{rows:[]};throw new Error(`unexpected ${sql}`)});const result=await reviewDispatchRecommendation(db,{recommendationId:'r1',decision:'approved',actorUserId:'d1'});assert.equal(result.selected_technician_id,'t1');assert.ok(calls.some(x=>x.params[1]==='ai.dispatch_approved'))});
test('unlisted technician is rejected',async()=>{const{db}=tx(async sql=>{if(/SELECT \* FROM ai_dispatch/.test(sql))return{rows:[{id:'r1',candidates:[{technician_id:'t1'}],recommended_technician_id:'t1'}]};throw new Error(`unexpected ${sql}`)});await assert.rejects(()=>reviewDispatchRecommendation(db,{recommendationId:'r1',decision:'approved',technicianId:'t2',actorUserId:'d1'}),/not a candidate/)});
test('support cannot access dispatch recommendations',async()=>{const db={query:async()=>{throw new Error('must not query')}};const result=await routePersistentRequest({method:'GET',url:'/api/v1/ai/dispatch/queue',role:'support',context:{},db});assert.equal(result.status,403)});
test('rejection requires a review note',async()=>{const db={query:async()=>{throw new Error('must not query')}};const result=await routePersistentRequest({method:'POST',url:'/api/v1/ai/dispatch/r1/reject',role:'dispatcher',context:{userId:'d1'},body:{note:'x'},db});assert.equal(result.status,400)});
