import test from'node:test';import assert from'node:assert/strict';import{routePersistentRequest}from'../src/http/persistent-router.mjs';import{buildFinanceAnomalies,scanFinanceAnomalies,updateFinanceAnomaly}from'../src/ai/finance.mjs';
function tx(handler){const calls=[];return{calls,db:{query:async()=>({rows:[]}),connect:async()=>({query:async(sql,p=[])=>{calls.push({sql,params:p});if(['BEGIN','COMMIT','ROLLBACK'].includes(sql))return{rows:[]};return handler(sql,p)},release(){}})}}}
test('detects negative margin order with financial impact',()=>{const list=buildFinanceAnomalies({},[{id:'o1',external_order_id:'1001',net_profit:'-650'}]);assert.equal(list[0].type,'negative_margin');assert.equal(list[0].severity,'critical');assert.equal(list[0].impact,650)});
test('detects material weekly revenue drop',()=>{const list=buildFinanceAnomalies({current_revenue:4000,previous_revenue:10000},[]);const drop=list.find(x=>x.type==='revenue_drop');assert.ok(drop);assert.equal(drop.severity,'critical');assert.equal(drop.impact,6000)});
test('detects settlement and purchasing backlogs',()=>{const list=buildFinanceAnomalies({pending_settlements:8,pending_settlement_value:2400,overdue_purchase_orders:2,overdue_purchase_value:5000},[]);assert.ok(list.some(x=>x.type==='settlement_backlog'));assert.ok(list.some(x=>x.type==='overdue_purchase'))});
test('finance scan upserts active anomalies and audits',async()=>{const metrics={current_revenue:100,previous_revenue:100,pending_settlements:0,overdue_purchase_orders:0};const orders=[{id:'o1',external_order_id:'1',net_profit:'-20'}];const{db,calls}=tx(async sql=>{if(/SELECT\(SELECT COALESCE/.test(sql))return{rows:[metrics]};if(/FROM orders o LEFT JOIN LATERAL/.test(sql))return{rows:orders};if(/INSERT INTO ai_finance_anomalies/.test(sql))return{rows:[{id:'a1'}]};if(/INSERT INTO audit_log/.test(sql))return{rows:[]};throw new Error(`unexpected ${sql}`)});const result=await scanFinanceAnomalies(db,{actorUserId:'f1'});assert.equal(result.anomalies.length,1);assert.ok(calls.some(x=>/ON CONFLICT\(fingerprint\)/.test(x.sql)))});
test('finance anomaly review is audited',async()=>{const{db,calls}=tx(async sql=>{if(/SELECT \* FROM ai_finance/.test(sql))return{rows:[{id:'a1',status:'open'}]};if(/UPDATE ai_finance/.test(sql))return{rows:[{id:'a1',status:'reviewed'}]};if(/INSERT INTO audit_log/.test(sql))return{rows:[]};throw new Error(`unexpected ${sql}`)});const result=await updateFinanceAnomaly(db,{anomalyId:'a1',status:'reviewed',actorUserId:'f1'});assert.equal(result.status,'reviewed');assert.ok(calls.some(x=>x.params[1]==='ai.finance_reviewed'))});
test('finance workflow blocks resolving before review',async()=>{const{db}=tx(async sql=>{if(/SELECT \* FROM ai_finance/.test(sql))return{rows:[{id:'a1',status:'open'}]};throw new Error(`unexpected ${sql}`)});await assert.rejects(()=>updateFinanceAnomaly(db,{anomalyId:'a1',status:'resolved',note:'fixed',actorUserId:'f1'}),/Invalid finance/)});
test('support cannot access finance anomaly data',async()=>{const db={query:async()=>{throw new Error('must not query')}};const result=await routePersistentRequest({method:'GET',url:'/api/v1/ai/finance/anomalies',role:'support',context:{},db});assert.equal(result.status,403)});
test('resolution requires meaningful note',async()=>{const db={query:async()=>{throw new Error('must not query')}};const result=await routePersistentRequest({method:'PATCH',url:'/api/v1/ai/finance/anomalies/a1',role:'finance',context:{userId:'f1'},body:{status:'resolved',note:'x'},db});assert.equal(result.status,400)});
