import test from'node:test';import assert from'node:assert/strict';import{routePersistentRequest}from'../src/http/persistent-router.mjs';import{generateExecutiveInsights,updateInsight}from'../src/ai/insights.mjs';
function tx(handler){const calls=[];return{calls,db:{query:async()=>({rows:[]}),connect:async()=>({query:async(sql,p=[])=>{calls.push({sql,params:p});if(['BEGIN','COMMIT','ROLLBACK'].includes(sql))return{rows:[]};return handler(sql,p)},release(){}})}}}
const metrics={overdue_jobs:12,open_escalations:2,low_stock_items:3,pending_settlements:4,pending_settlement_value:'800',abandoned_carts:5,abandoned_cart_value:'6000',failed_campaign_deliveries:2,pending_conversations:7};
test('daily scan creates prioritized insights and executive brief',async()=>{let n=0;const{db,calls}=tx(async sql=>{if(/SELECT\s+\(SELECT COUNT/.test(sql))return{rows:[metrics]};if(/INSERT INTO ai_insights/.test(sql)){n++;return{rows:[{id:`i${n}`,severity:n===1?'critical':'high',title:`Insight ${n}`,recommended_action:'Act'}]}}if(/INSERT INTO ai_executive_briefs/.test(sql))return{rows:[{id:'b1',summary:'brief'}]};if(/INSERT INTO audit_log/.test(sql))return{rows:[]};throw new Error(`unexpected ${sql}`)});const result=await generateExecutiveInsights(db,{actorUserId:'m1',date:'2026-09-16'});assert.equal(result.insights.length,7);assert.equal(result.insights[0].severity,'critical');assert.ok(calls.filter(x=>/ON CONFLICT\(organization_id,fingerprint,detected_on\)/.test(x.sql)).length===7)});
test('healthy scan creates a no-exception brief',async()=>{const zero=Object.fromEntries(Object.keys(metrics).map(k=>[k,0]));const{db}=tx(async sql=>{if(/SELECT\s+\(SELECT COUNT/.test(sql))return{rows:[zero]};if(/INSERT INTO ai_executive_briefs/.test(sql))return{rows:[{id:'b1',summary:'لا توجد استثناءات تشغيلية مهمة اليوم.'}]};if(/INSERT INTO audit_log/.test(sql))return{rows:[]};throw new Error(`unexpected ${sql}`)});const result=await generateExecutiveInsights(db,{actorUserId:'m1',date:'2026-09-16'});assert.equal(result.insights.length,0);assert.match(result.brief.summary,/لا توجد/)});
test('daily scan is idempotent by organization fingerprint and date',async()=>{const one={...Object.fromEntries(Object.keys(metrics).map(k=>[k,0])),overdue_jobs:1};const{db,calls}=tx(async sql=>{if(/SELECT\s+\(SELECT COUNT/.test(sql))return{rows:[one]};if(/INSERT INTO ai_insights/.test(sql))return{rows:[{id:'i1',severity:'high',title:'late',recommended_action:'act'}]};if(/INSERT INTO ai_executive_briefs/.test(sql))return{rows:[{id:'b1'}]};if(/INSERT INTO audit_log/.test(sql))return{rows:[]};throw new Error(`unexpected ${sql}`)});await generateExecutiveInsights(db,{actorUserId:'m1',date:'2026-09-16'});assert.ok(calls.some(x=>/ON CONFLICT\(organization_id,brief_date\)/.test(x.sql)))});
test('resolving insight requires atomic audit',async()=>{const{db,calls}=tx(async sql=>{if(/UPDATE ai_insights SET status/.test(sql))return{rows:[{id:'i1',status:'resolved'}]};if(/INSERT INTO audit_log/.test(sql))return{rows:[]};throw new Error(`unexpected ${sql}`)});const insight=await updateInsight(db,{insightId:'i1',status:'resolved',note:'تمت المعالجة',actorUserId:'m1'});assert.equal(insight.status,'resolved');assert.ok(calls.some(x=>x.params[1]==='ai.insight_resolved'))});
test('support can read insights but cannot run the scan',async()=>{const db={query:async()=>({rows:[{open:1}]}),connect:async()=>{throw new Error('must not connect')}};const read=await routePersistentRequest({method:'GET',url:'/api/v1/ai/insights/stats',role:'support',db});const run=await routePersistentRequest({method:'POST',url:'/api/v1/ai/insights/run',role:'support',context:{userId:'u1'},db});assert.equal(read.status,200);assert.equal(run.status,403)});
test('resolved insight requires a meaningful note',async()=>{const db={query:async()=>{throw new Error('must not query')}};const result=await routePersistentRequest({method:'PATCH',url:'/api/v1/ai/insights/i1',role:'branch_manager',context:{userId:'m1'},body:{status:'resolved',note:'x'},db});assert.equal(result.status,400)});
test('insight endpoint rejects invalid domain before query',async()=>{const db={query:async()=>{throw new Error('must not query')}};const result=await routePersistentRequest({method:'GET',url:'/api/v1/ai/insights',role:'support',context:{domain:'sales'},db});assert.equal(result.status,400)});
test('scan endpoint validates date',async()=>{const db={query:async()=>{throw new Error('must not query')}};const result=await routePersistentRequest({method:'POST',url:'/api/v1/ai/insights/run',role:'branch_manager',context:{userId:'m1'},body:{date:'today'},db});assert.equal(result.status,400)});
