import test from'node:test';import assert from'node:assert/strict';import{routePersistentRequest}from'../src/http/persistent-router.mjs';import{buildMarketingRecommendations,scanMarketingRecommendations,updateMarketingRecommendation}from'../src/ai/marketing.mjs';
function tx(handler){const calls=[];return{calls,db:{query:async()=>({rows:[]}),connect:async()=>({query:async(sql,p=[])=>{calls.push({sql,params:p});if(['BEGIN','COMMIT','ROLLBACK'].includes(sql))return{rows:[]};return handler(sql,p)},release(){}})}}}
test('builds recovery content and attribution recommendations',()=>{const list=buildMarketingRecommendations({active_carts:5,abandoned_value:6000,failed_deliveries:0,published_content:3,paid_orders:100,attributed_orders:50},[]);assert.ok(list.some(x=>x.type==='recovery_campaign'&&x.priority==='high'));assert.ok(list.some(x=>x.type==='content_plan'));assert.ok(list.some(x=>x.type==='attribution_fix'))});
test('recommends bounded budget test only for meaningful ROAS gap',()=>{const list=buildMarketingRecommendations({published_content:10,paid_orders:10,attributed_orders:10},[{name:'google',spend:1000,roas:6},{name:'instagram',spend:1000,roas:2}]);const budget=list.find(x=>x.type==='budget_shift');assert.ok(budget);assert.match(budget.action,/15%/);assert.match(budget.rationale,/google/)});
test('healthy marketing signals generate no recommendation',()=>{const list=buildMarketingRecommendations({active_carts:0,abandoned_value:0,failed_deliveries:0,published_content:10,paid_orders:10,attributed_orders:10},[{name:'google',spend:100,roas:4}]);assert.deepEqual(list,[])});
test('marketing scan upserts active recommendations and audits',async()=>{const metrics={active_carts:2,abandoned_value:900,failed_deliveries:0,published_content:10,paid_orders:10,attributed_orders:10};const{db,calls}=tx(async sql=>{if(/SELECT\(SELECT COUNT/.test(sql))return{rows:[metrics]};if(/SELECT lt.source/.test(sql))return{rows:[]};if(/INSERT INTO ai_marketing_recommendations/.test(sql))return{rows:[{id:'r1',status:'new'}]};if(/INSERT INTO audit_log/.test(sql))return{rows:[]};throw new Error(`unexpected ${sql}`)});const result=await scanMarketingRecommendations(db,{actorUserId:'m1'});assert.equal(result.recommendations.length,1);assert.ok(calls.some(x=>/ON CONFLICT\(organization_id,fingerprint\)/.test(x.sql)))});
test('marketing workflow transition is audited',async()=>{const{db,calls}=tx(async sql=>{if(/SELECT \* FROM ai_marketing/.test(sql))return{rows:[{id:'r1',status:'new'}]};if(/UPDATE ai_marketing/.test(sql))return{rows:[{id:'r1',status:'approved'}]};if(/INSERT INTO audit_log/.test(sql))return{rows:[]};throw new Error(`unexpected ${sql}`)});const result=await updateMarketingRecommendation(db,{recommendationId:'r1',status:'approved',actorUserId:'m1'});assert.equal(result.status,'approved');assert.ok(calls.some(x=>x.params[1]==='ai.marketing_approved'))});
test('marketing workflow blocks skipped state',async()=>{const{db}=tx(async sql=>{if(/SELECT \* FROM ai_marketing/.test(sql))return{rows:[{id:'r1',status:'new'}]};throw new Error(`unexpected ${sql}`)});await assert.rejects(()=>updateMarketingRecommendation(db,{recommendationId:'r1',status:'completed',actorUserId:'m1'}),/Invalid marketing/)});
test('support can read recommendations but cannot run scan',async()=>{const db={query:async()=>({rows:[]}),connect:async()=>{throw new Error('must not connect')}};const read=await routePersistentRequest({method:'GET',url:'/api/v1/ai/marketing/recommendations',role:'support',context:{},db});const scan=await routePersistentRequest({method:'POST',url:'/api/v1/ai/marketing/scan',role:'support',context:{userId:'u1'},db});assert.equal(read.status,200);assert.equal(scan.status,403)});
test('completion requires outcome note',async()=>{const db={query:async()=>{throw new Error('must not query')}};const result=await routePersistentRequest({method:'PATCH',url:'/api/v1/ai/marketing/recommendations/r1',role:'branch_manager',context:{userId:'m1'},body:{status:'completed',note:'x'},db});assert.equal(result.status,400)});
