import test from'node:test';import assert from'node:assert/strict';import{routePersistentRequest}from'../src/http/persistent-router.mjs';import{detectSalesSignals,scanSalesOpportunities,updateSalesOpportunity}from'../src/ai/sales.mjs';
function tx(handler){const calls=[];return{calls,db:{query:async()=>({rows:[]}),connect:async()=>({query:async(sql,p=[])=>{calls.push({sql,params:p});if(['BEGIN','COMMIT','ROLLBACK'].includes(sql))return{rows:[]};return handler(sql,p)},release(){}})}}}
test('detects maintenance and cart recovery opportunities',()=>{const result=detectSalesSignals({maintenance_due:2,abandoned_value:650,lifetime_value:1000,last_paid_at:'2026-09-01',pending_conversations:0},new Date('2026-09-16'));assert.equal(result[0].type,'maintenance_due');assert.ok(result.some(x=>x.type==='cart_recovery'));assert.equal(result.find(x=>x.type==='cart_recovery').value,650)});
test('detects high value cross sell and dormant win back',()=>{const result=detectSalesSignals({maintenance_due:0,abandoned_value:0,lifetime_value:5000,last_paid_at:'2026-01-01',pending_conversations:0},new Date('2026-09-16'));assert.ok(result.some(x=>x.type==='cross_sell'));assert.ok(result.some(x=>x.type==='win_back'));assert.ok(result.every(x=>x.score<=100))});
test('new customer without signals creates no opportunity',()=>{const result=detectSalesSignals({maintenance_due:0,abandoned_value:0,lifetime_value:0,last_paid_at:null,pending_conversations:0});assert.deepEqual(result,[])});
test('sales scan upserts active opportunities and audits batch',async()=>{const customer={id:'c1',maintenance_due:1,abandoned_value:0,lifetime_value:0,last_paid_at:null,pending_conversations:1};let n=0;const{db,calls}=tx(async sql=>{if(/FROM customers c LEFT JOIN orders/.test(sql))return{rows:[customer]};if(/INSERT INTO ai_sales_opportunities/.test(sql)){n++;return{rows:[{id:`o${n}`,inserted:true}]}}if(/INSERT INTO audit_log/.test(sql))return{rows:[]};throw new Error(`unexpected ${sql}`)});const result=await scanSalesOpportunities(db,{actorUserId:'m1',limit:100});assert.equal(result.created,2);assert.ok(calls.some(x=>/ON CONFLICT\(customer_id,opportunity_type\)/.test(x.sql)))});
test('opportunity transition is audited',async()=>{const{db,calls}=tx(async sql=>{if(/SELECT \* FROM ai_sales_opportunities/.test(sql))return{rows:[{id:'o1',status:'new'}]};if(/UPDATE ai_sales_opportunities/.test(sql))return{rows:[{id:'o1',status:'approved'}]};if(/INSERT INTO audit_log/.test(sql))return{rows:[]};throw new Error(`unexpected ${sql}`)});const result=await updateSalesOpportunity(db,{opportunityId:'o1',status:'approved',actorUserId:'u1'});assert.equal(result.status,'approved');assert.ok(calls.some(x=>x.params[1]==='ai.sales_approved'))});
test('invalid opportunity transition rolls back',async()=>{const{db,calls}=tx(async sql=>{if(/SELECT \* FROM ai_sales/.test(sql))return{rows:[{id:'o1',status:'new'}]};throw new Error(`unexpected ${sql}`)});await assert.rejects(()=>updateSalesOpportunity(db,{opportunityId:'o1',status:'converted',actorUserId:'u1'}),/Invalid sales/);assert.ok(calls.some(x=>x.sql==='ROLLBACK'))});
test('support can read and update but cannot run global scan',async()=>{const db={query:async()=>({rows:[]}),connect:async()=>{throw new Error('must not connect')}};const read=await routePersistentRequest({method:'GET',url:'/api/v1/ai/sales/opportunities',role:'support',context:{},db});const scan=await routePersistentRequest({method:'POST',url:'/api/v1/ai/sales/scan',role:'support',context:{userId:'u1'},db});assert.equal(read.status,200);assert.equal(scan.status,403)});
test('converted outcome requires note before database access',async()=>{const db={query:async()=>{throw new Error('must not query')}};const result=await routePersistentRequest({method:'PATCH',url:'/api/v1/ai/sales/opportunities/o1',role:'support',context:{userId:'u1'},body:{status:'converted',note:'x'},db});assert.equal(result.status,400)});
