import test from 'node:test';
import assert from 'node:assert/strict';
import { routePersistentRequest } from '../src/http/persistent-router.mjs';
import { ingestConversationMessage, replyToConversation, updateConversation } from '../src/marketing/conversations.mjs';

function tx(handler){const calls=[];return{calls,db:{query:async()=>({rows:[]}),connect:async()=>({query:async(sql,params=[])=>{calls.push({sql,params});if(['BEGIN','COMMIT','ROLLBACK'].includes(sql))return{rows:[]};return handler(sql,params)},release(){}})}}}

test('inbound message creates or refreshes a customer thread',async()=>{const{db,calls}=tx(async sql=>{if(/INSERT INTO customer_conversations/.test(sql))return{rows:[{id:'c1',unread_count:0,status:'pending_agent'}]};if(/INSERT INTO conversation_messages/.test(sql))return{rows:[{id:'m1',body:'مرحبا'}]};if(/UPDATE customer_conversations/.test(sql))return{rows:[]};throw new Error(`unexpected ${sql}`)});const result=await ingestConversationMessage(db,{channel:'whatsapp',externalThreadId:'wa-1',externalMessageId:'msg-1',body:'مرحبا',sentAt:'2026-09-16T00:00:00Z'});assert.equal(result.conversation.unread_count,1);assert.equal(result.duplicate,false);assert.ok(calls.some(call=>/ON CONFLICT\(channel,external_thread_id\)/.test(call.sql)))});
test('duplicate provider message does not increase unread count',async()=>{const{db,calls}=tx(async sql=>{if(/INSERT INTO customer_conversations/.test(sql))return{rows:[{id:'c1',unread_count:2}]};if(/INSERT INTO conversation_messages/.test(sql))return{rows:[]};throw new Error(`unexpected ${sql}`)});const result=await ingestConversationMessage(db,{channel:'email',externalThreadId:'mail-1',externalMessageId:'same',body:'again',sentAt:'2026-09-16T00:00:00Z'});assert.equal(result.duplicate,true);assert.equal(calls.filter(call=>/UPDATE customer_conversations SET unread_count/.test(call.sql)).length,0)});
test('agent reply is queued and audited atomically',async()=>{const{db,calls}=tx(async sql=>{if(/SELECT \* FROM customer_conversations/.test(sql))return{rows:[{id:'c1',status:'pending_agent',channel:'whatsapp'}]};if(/INSERT INTO conversation_messages/.test(sql))return{rows:[{id:'m2',sent_at:'2026-09-16'}]};if(/UPDATE customer_conversations/.test(sql))return{rows:[{id:'c1',status:'waiting_customer'}]};if(/INSERT INTO audit_log/.test(sql))return{rows:[]};throw new Error(`unexpected ${sql}`)});const result=await replyToConversation(db,{conversationId:'c1',body:'حياك الله',actorUserId:'u1'});assert.equal(result.conversation.status,'waiting_customer');assert.ok(calls.some(call=>call.params[1]==='conversation.replied'))});
test('closed conversation cannot receive an agent reply',async()=>{const{db}=tx(async sql=>{if(/SELECT \* FROM customer_conversations/.test(sql))return{rows:[{id:'c1',status:'closed'}]};throw new Error(`unexpected ${sql}`)});await assert.rejects(()=>replyToConversation(db,{conversationId:'c1',body:'test',actorUserId:'u1'}),/closed/)});
test('conversation status and assignment are audited',async()=>{const{db,calls}=tx(async sql=>{if(/SELECT \* FROM customer_conversations/.test(sql))return{rows:[{id:'c1'}]};if(/UPDATE customer_conversations/.test(sql))return{rows:[{id:'c1',status:'closed'}]};if(/INSERT INTO audit_log/.test(sql))return{rows:[]};throw new Error(`unexpected ${sql}`)});const result=await updateConversation(db,{conversationId:'c1',status:'closed',priority:'high',assignProvided:true,assignedTo:'u2',actorUserId:'u1'});assert.equal(result.status,'closed');assert.ok(calls.some(call=>call.params[1]==='conversation.updated'))});
test('support can read and reply but invalid inbound channel is rejected',async()=>{const db={query:async sql=>/COUNT\(\*\) FILTER/.test(sql)?{rows:[{active:2,unread:3}]}:{rows:[]},connect:async()=>{throw new Error('must not connect')}};const stats=await routePersistentRequest({method:'GET',url:'/api/v1/conversations/stats',role:'support',db});const invalid=await routePersistentRequest({method:'POST',url:'/api/v1/conversations/inbound',role:'support',body:{channel:'telegram',externalThreadId:'x',body:'hi'},db});assert.equal(stats.status,200);assert.equal(invalid.status,400)});
test('technician cannot read customer conversations',async()=>{const db={query:async()=>{throw new Error('must not query')}};const result=await routePersistentRequest({method:'GET',url:'/api/v1/conversations',role:'technician',context:{},db});assert.equal(result.status,403)});
test('conversation update validates status before database access',async()=>{const db={query:async()=>{throw new Error('must not query')}};const result=await routePersistentRequest({method:'PATCH',url:'/api/v1/conversations/c1',role:'support',context:{userId:'u1'},body:{status:'deleted'},db});assert.equal(result.status,400)});
