import test from'node:test';import assert from'node:assert/strict';import{routePersistentRequest}from'../src/http/persistent-router.mjs';import{attributeOrder,recordSpend,recordTouch}from'../src/marketing/attribution.mjs';function tx(handler){const calls=[];return{calls,db:{query:async()=>({rows:[]}),connect:async()=>({query:async(sql,p=[])=>{calls.push({sql,params:p});if(['BEGIN','COMMIT','ROLLBACK'].includes(sql))return{rows:[]};return handler(sql,p)},release(){}})}}}
test('touch requires a visitor or customer identity',async()=>{const db={query:async()=>{throw new Error('must not query')}};const r=await routePersistentRequest({method:'POST',url:'/api/v1/marketing/touches',role:'branch_manager',body:{source:'google'},db});assert.equal(r.status,400)});
test('records a first party marketing touch',async()=>{const db={query:async(sql,p)=>{assert.match(sql,/INSERT INTO marketing_touches/);assert.equal(p[2],'google');return{rows:[{id:'t1',source:'google'}]}}};const touch=await recordTouch(db,{visitorId:'v1',source:'google',medium:'cpc',occurredAt:'2026-09-16'});assert.equal(touch.id,'t1')});
test('order attribution stores first and last touches',async()=>{const{db,calls}=tx(async sql=>{if(/SELECT id,customer_id/.test(sql))return{rows:[{id:'o1',customer_id:'c1',paid_at:'2026-09-16'}]};if(/FROM marketing_touches/.test(sql))return{rows:[{id:'t1',source:'google'},{id:'t2',source:'instagram'}]};if(/INSERT INTO order_attribution/.test(sql))return{rows:[{order_id:'o1',first_touch_id:'t1',last_touch_id:'t2'}]};if(/INSERT INTO audit_log/.test(sql))return{rows:[]};throw new Error(`unexpected ${sql}`)});const r=await attributeOrder(db,{orderId:'o1',visitorId:'v1',actorUserId:'m1'});assert.equal(r.touchCount,2);assert.equal(r.first.source,'google');assert.equal(r.last.source,'instagram');assert.ok(calls.some(c=>/ON CONFLICT/.test(c.sql)))});
test('order without touches remains safely unattributed',async()=>{const{db}=tx(async sql=>{if(/SELECT id,customer_id/.test(sql))return{rows:[{id:'o1',customer_id:'c1'}]};if(/FROM marketing_touches/.test(sql))return{rows:[]};throw new Error(`unexpected ${sql}`)});const r=await attributeOrder(db,{orderId:'o1',actorUserId:'m1'});assert.deepEqual(r,{orderId:'o1',attributed:false})});
test('marketing spend is audited atomically',async()=>{const{db,calls}=tx(async(sql)=>{if(/INSERT INTO marketing_spend/.test(sql))return{rows:[{id:'s1',amount:'500'}]};if(/INSERT INTO audit_log/.test(sql))return{rows:[]};throw new Error(`unexpected ${sql}`)});const r=await recordSpend(db,{source:'google',campaign:'search',amount:500,spentOn:'2026-09-16',actorUserId:'m1'});assert.equal(r.id,'s1');assert.ok(calls.some(c=>c.params[1]==='marketing.spend_recorded'))});
test('spend endpoint validates date and amount',async()=>{const db={connect:async()=>{throw new Error('must not connect')},query:async()=>({rows:[]})};const r=await routePersistentRequest({method:'POST',url:'/api/v1/marketing/spend',role:'branch_manager',context:{userId:'m1'},body:{source:'google',amount:-1,spentOn:'today'},db});assert.equal(r.status,400)});
test('support reads attribution report but cannot record spend',async()=>{let calls=0;const db={query:async(sql)=>{calls++;if(/paid_orders/.test(sql))return{rows:[{paid_orders:2,attributed_orders:1,attributed_revenue:'500',spend:'100'}]};return{rows:[]}}};const read=await routePersistentRequest({method:'GET',url:'/api/v1/marketing/attribution',role:'support',context:{from:'2026-09-01',to:'2026-10-01'},db});const write=await routePersistentRequest({method:'POST',url:'/api/v1/marketing/spend',role:'support',db});assert.equal(read.status,200);assert.equal(read.data.summary.roas,5);assert.equal(calls,4);assert.equal(write.status,403)});
test('attribution rejects an excessive reporting range',async()=>{const db={query:async()=>{throw new Error('must not query')}};const r=await routePersistentRequest({method:'GET',url:'/api/v1/marketing/attribution',role:'support',context:{from:'2024-01-01',to:'2026-01-01'},db});assert.equal(r.status,400)});
