import test from'node:test';import assert from'node:assert/strict';import{routePersistentRequest}from'../src/http/persistent-router.mjs';import{createCampaign,createSegment,launchCampaign,previewAudience}from'../src/marketing/operations.mjs';
function tx(handler){const calls=[];return{calls,db:{query:async()=>({rows:[]}),connect:async()=>({query:async(sql,params=[])=>{calls.push({sql,params});if(['BEGIN','COMMIT','ROLLBACK'].includes(sql))return{rows:[]};return handler(sql,params)},release(){}})}}}
test('support reads marketing stats but cannot create campaigns',async()=>{const db={query:async sql=>{assert.match(sql,/total_recipients/);return{rows:[{total:3,queued:1}]}}};const read=await routePersistentRequest({method:'GET',url:'/api/v1/marketing/stats',role:'support',db});const write=await routePersistentRequest({method:'POST',url:'/api/v1/marketing/campaigns',role:'support',db});assert.equal(read.status,200);assert.equal(write.status,403)});
test('manager lists paginated campaigns',async()=>{const db={query:async(sql,params)=>{assert.match(sql,/campaign_recipients/);assert.deepEqual(params,['queued',10,20]);return{rows:[{id:'c1',total_count:4}]}}};const result=await routePersistentRequest({method:'GET',url:'/api/v1/marketing/campaigns',role:'branch_manager',context:{status:'queued',limit:'10',offset:'20'},db});assert.equal(result.status,200);assert.equal(result.data.pagination.total,4)});
test('segment validation rejects unknown rules before transaction',async()=>{const db={query:async()=>({rows:[]}),connect:async()=>{throw new Error('must not connect')}};const result=await routePersistentRequest({method:'POST',url:'/api/v1/marketing/segments',role:'branch_manager',context:{userId:'m1'},body:{name:'x',segmentType:'custom_sql'},db});assert.equal(result.status,400)});
test('segment creation is audited atomically',async()=>{const{db,calls}=tx(async(sql)=>{if(/INSERT INTO customer_segments/.test(sql))return{rows:[{id:'s1',name:'عملاء مميزون'}]};if(/INSERT INTO audit_log/.test(sql))return{rows:[]};throw new Error(`unexpected ${sql}`)});const result=await createSegment(db,{name:'عملاء مميزون',segmentType:'high_value',actorUserId:'m1'});assert.equal(result.id,'s1');assert.ok(calls.some(c=>c.params[1]==='marketing.segment_created'));assert.ok(calls.some(c=>c.sql==='COMMIT'))});
test('campaign creation requires an active segment',async()=>{const{db,calls}=tx(async sql=>{if(/SELECT id FROM customer_segments/.test(sql))return{rows:[]};throw new Error(`unexpected ${sql}`)});await assert.rejects(()=>createCampaign(db,{name:'عرض',segmentId:'missing',channel:'sms',message:'خصم',actorUserId:'m1'}),/not found/);assert.ok(calls.some(c=>c.sql==='ROLLBACK'))});
test('audience preview uses fixed server-side segment rules',async()=>{const db={query:async(sql,params)=>{assert.match(sql,/interval '90 days'/);assert.deepEqual(params,[10]);return{rows:[{id:'u1',name:'عميل',audience_count:18}]}}};const result=await previewAudience(db,'dormant_90d',10);assert.equal(result.count,18);assert.equal(result.customers[0].name,'عميل')});
test('launch materializes recipients and notification events atomically',async()=>{let event=0;const{db,calls}=tx(async(sql)=>{if(/SELECT mc\.\*/.test(sql))return{rows:[{id:'c1',status:'draft',segment_type:'repeat_customers',channel:'whatsapp',name:'عرض',message:'رسالة'}]};if(/FROM customers c/.test(sql))return{rows:[{id:'u1'},{id:'u2'}]};if(/INSERT INTO notification_events/.test(sql))return{rows:[{id:`n${++event}`}]};if(/INSERT INTO campaign_recipients|INSERT INTO audit_log/.test(sql))return{rows:[]};if(/UPDATE marketing_campaigns/.test(sql))return{rows:[{id:'c1',status:'queued'}]};throw new Error(`unexpected ${sql}`)});const result=await launchCampaign(db,{campaignId:'c1',actorUserId:'m1'});assert.equal(result.audienceCount,2);assert.equal(result.campaign.status,'queued');assert.equal(calls.filter(c=>/notification_events/.test(c.sql)).length,2);assert.ok(calls.some(c=>c.params[1]==='marketing.campaign_launched'))});
test('launched campaign cannot be launched twice',async()=>{const{db,calls}=tx(async sql=>{if(/SELECT mc\.\*/.test(sql))return{rows:[{id:'c1',status:'queued',segment_type:'all'}]};throw new Error(`unexpected ${sql}`)});await assert.rejects(()=>launchCampaign(db,{campaignId:'c1',actorUserId:'m1'}),/not launchable/);assert.ok(calls.some(c=>c.sql==='ROLLBACK'))});
