import test from'node:test';import assert from'node:assert/strict';import{routePersistentRequest}from'../src/http/persistent-router.mjs';import{createContent,scoreSeo,transitionContent}from'../src/marketing/content.mjs';function tx(handler){const calls=[];return{calls,db:{query:async()=>({rows:[]}),connect:async()=>({query:async(sql,p=[])=>{calls.push({sql,params:p});if(['BEGIN','COMMIT','ROLLBACK'].includes(sql))return{rows:[]};return handler(sql,p)},release(){}})}}}
test('SEO scoring rewards complete optimized content',()=>{const full=scoreSeo({title:'دليل شامل لاختيار فلتر المياه المناسب للمنزل',body:`فلتر المياه ${'محتوى '.repeat(60)}`,primaryKeyword:'فلتر المياه',metaDescription:'تعرف على طريقة اختيار فلتر المياه المناسب لمنزلك ومقارنة الأنواع والمراحل والتكلفة والصيانة الدورية لضمان مياه نقية وآمنة لأسرتك.',slug:'فلتر-المياه'});const weak=scoreSeo({title:'عرض',body:'قصير',primaryKeyword:'فلاتر',metaDescription:'',slug:'offer'});assert.equal(full,100);assert.ok(weak<full)});
test('support reads content stats but cannot create',async()=>{const db={query:async sql=>{assert.match(sql,/average_seo_score/);return{rows:[{total:5}]}}};assert.equal((await routePersistentRequest({method:'GET',url:'/api/v1/marketing/content/stats',role:'support',db})).status,200);assert.equal((await routePersistentRequest({method:'POST',url:'/api/v1/marketing/content',role:'support',db})).status,403)});
test('manager filters content calendar',async()=>{const db={query:async(sql,p)=>{assert.match(sql,/marketing_content/);assert.deepEqual(p,['scheduled','instagram',null,null,10,0]);return{rows:[{id:'m1',total_count:2}]}}};const r=await routePersistentRequest({method:'GET',url:'/api/v1/marketing/content',role:'branch_manager',context:{status:'scheduled',channel:'instagram',limit:'10'},db});assert.equal(r.status,200);assert.equal(r.data.pagination.total,2)});
test('invalid slug is rejected before transaction',async()=>{const db={connect:async()=>{throw new Error('must not connect')},query:async()=>({rows:[]})};const r=await routePersistentRequest({method:'POST',url:'/api/v1/marketing/content',role:'branch_manager',context:{userId:'m1'},body:{title:'عنوان جيد',slug:'bad slug!',contentType:'blog',channel:'website'},db});assert.equal(r.status,400)});
test('content creation stores SEO score and audit',async()=>{const{db,calls}=tx(async(sql,p)=>{if(/INSERT INTO marketing_content/.test(sql))return{rows:[{id:'m1',seo_score:p[7],status:'draft'}]};if(/INSERT INTO audit_log/.test(sql))return{rows:[]};throw new Error(`unexpected ${sql}`)});const item=await createContent(db,{title:'مقال طويل عن فلاتر المياه المنزلية',slug:'water-filter',contentType:'blog',channel:'website',body:'محتوى '.repeat(60),primaryKeyword:'فلاتر المياه',metaDescription:'وصف '.repeat(20),actorUserId:'u1'});assert.ok(item.seo_score>0);assert.ok(calls.some(c=>c.params[1]==='marketing.content_created'))});
test('reviewed content can be approved atomically',async()=>{const{db,calls}=tx(async(sql)=>{if(/SELECT \* FROM marketing_content/.test(sql))return{rows:[{id:'m1',status:'review'}]};if(/UPDATE marketing_content/.test(sql))return{rows:[{id:'m1',status:'approved'}]};if(/INSERT INTO audit_log/.test(sql))return{rows:[]};throw new Error(`unexpected ${sql}`)});const item=await transitionContent(db,{contentId:'m1',to:'approved',actorUserId:'u1'});assert.equal(item.status,'approved');assert.ok(calls.some(c=>c.sql==='COMMIT'))});
test('workflow blocks publishing an unreviewed draft',async()=>{const{db,calls}=tx(async sql=>{if(/SELECT \* FROM marketing_content/.test(sql))return{rows:[{id:'m1',status:'draft'}]};throw new Error(`unexpected ${sql}`)});await assert.rejects(()=>transitionContent(db,{contentId:'m1',to:'published',actorUserId:'u1'}),/Invalid content transition/);assert.ok(calls.some(c=>c.sql==='ROLLBACK'))});
test('scheduling requires a time',async()=>{const{db}=tx(async sql=>{if(/SELECT \* FROM marketing_content/.test(sql))return{rows:[{id:'m1',status:'approved',scheduled_at:null}]};throw new Error(`unexpected ${sql}`)});await assert.rejects(()=>transitionContent(db,{contentId:'m1',to:'scheduled',actorUserId:'u1'}),/Schedule time required/)});
