import test from 'node:test';
import assert from 'node:assert/strict';
import { listDispatchCandidates, assignPersistentJob, reassignPersistentJob } from '../src/dispatch/persistent-dispatch.mjs';

test('candidate query ranks by proximity and uses true interval overlap',async()=>{const calls=[];const db={query:async(sql,params)=>{calls.push({sql,params});if(/FROM service_jobs j LEFT JOIN service_locations/.test(sql))return{rows:[{id:'j1',city_id:'riyadh',status:'pending_assignment',scheduled_at:'2026-09-15T09:00:00Z',required_skill_code:'ro-install',service_duration_minutes:90,latitude:'24.700000',longitude:'46.680000'}]};if(/FROM technicians t/.test(sql))return{rows:[{technician_id:'near',distance_km:'1.20',jobs_in_window:0,avg_rating:'4.70'}]};throw new Error(`unexpected query: ${sql}`)}};const result=await listDispatchCandidates(db,'j1');assert.equal(result.windowEnd,'2026-09-15T10:30:00.000Z');const q=calls.find(c=>/FROM technicians t/.test(c.sql));assert.match(q.sql,/technician_locations/);assert.match(q.sql,/6371/);assert.match(q.sql,/scheduled_at < \$3/);assert.match(q.sql,/service_duration_minutes \* interval '1 minute'/);assert.match(q.sql,/distance_km ASC NULLS LAST, jobs_in_window ASC, avg_rating DESC/);});

function assignmentDb({skill=true,available=true,conflict=false,status='pending_assignment',cityEligible=true,duration=60}={}){const calls=[];const client={async query(sql,params=[]){calls.push({sql,params});if(['BEGIN','COMMIT','ROLLBACK'].includes(sql))return{rows:[]};if(/service_jobs WHERE id=\$1 AND/.test(sql))return{rows:[{id:'j1',organization_id:'org-1',city_id:'riyadh',status,required_skill_code:'ro-install',service_duration_minutes:duration,technician_id:'old-tech',scheduled_at:'2026-09-15T09:00:00Z'}]};if(/FROM technicians t JOIN users/.test(sql))return{rows:cityEligible?[{id:'t1',city_id:'riyadh',is_active:true}]:[]};if(/FROM technician_skills/.test(sql))return{rows:skill?[{'?column?':1}]:[]};if(/FROM technician_availability/.test(sql))return{rows:available?[{'?column?':1}]:[]};if(/SELECT id FROM service_jobs/.test(sql))return{rows:conflict?[{id:'j-conflict'}]:[]};if(/UPDATE service_jobs/.test(sql))return{rows:[{id:'j1',technician_id:'t1',status:'scheduled',scheduled_at:params[2],service_duration_minutes:params[3]}]};if(/INSERT INTO audit_log/.test(sql))return{rows:[]};throw new Error(`unexpected query: ${sql}`)},release(){calls.push({sql:'RELEASE'})}};return{db:{connect:async()=>client},calls};}

test('assignment is tenant constrained for both job and technician',async()=>{const{db,calls}=assignmentDb();await assignPersistentJob(db,{jobId:'j1',technicianId:'t1',scheduledAt:'2026-09-15T10:00:00Z',actorUserId:'d1',tenantId:'org-1'});const job=calls.find(c=>/service_jobs WHERE id=\$1 AND/.test(c.sql));const technician=calls.find(c=>/FROM technicians t JOIN users/.test(c.sql));assert.equal(job.params[1],'org-1');assert.equal(technician.params[2],'org-1');});

test('assignment stores service duration and interval conflict query',async()=>{const{db,calls}=assignmentDb({duration:90});const job=await assignPersistentJob(db,{jobId:'j1',technicianId:'t1',scheduledAt:'2026-09-15T10:00:00Z',actorUserId:'d1'});assert.equal(job.service_duration_minutes,90);const conflict=calls.find(c=>/SELECT id FROM service_jobs/.test(c.sql));assert.match(conflict.sql,/scheduled_at < \$4/);assert.match(conflict.sql,/service_duration_minutes \* interval '1 minute'/);assert.equal(conflict.params[2],'2026-09-15T10:00:00.000Z');assert.equal(conflict.params[3],'2026-09-15T11:30:00.000Z');assert.ok(calls.some(c=>c.sql==='COMMIT'));});

test('touching boundary is not modeled as overlap',async()=>{const{db,calls}=assignmentDb({duration:90});await assignPersistentJob(db,{jobId:'j1',technicianId:'t1',scheduledAt:'2026-09-15T10:00:00Z',actorUserId:'d1'});const conflict=calls.find(c=>/SELECT id FROM service_jobs/.test(c.sql));assert.match(conflict.sql,/scheduled_at < \$4/);assert.match(conflict.sql,/\) > \$3/);});

test('second dispatcher cannot overwrite an already scheduled job',async()=>{const{db,calls}=assignmentDb({status:'scheduled'});await assert.rejects(()=>assignPersistentJob(db,{jobId:'j1',technicianId:'t1',scheduledAt:'2026-09-15T10:00:00Z',actorUserId:'d2'}),/already assigned/);assert.ok(calls.some(c=>c.sql==='ROLLBACK'));assert.ok(!calls.some(c=>/UPDATE service_jobs/.test(c.sql)));});

test('explicit reassignment requires reason and preserves duration in audit',async()=>{const{db}=assignmentDb({status:'scheduled'});await assert.rejects(()=>reassignPersistentJob(db,{jobId:'j1',technicianId:'t1',scheduledAt:'2026-09-15T10:00:00Z',actorUserId:'d1'}),/reason is required/);const second=assignmentDb({status:'scheduled',duration:75});await reassignPersistentJob(second.db,{jobId:'j1',technicianId:'t1',scheduledAt:'2026-09-15T10:00:00Z',actorUserId:'d1',reason:'customer requested new slot'});const audit=second.calls.find(c=>/INSERT INTO audit_log/.test(c.sql));assert.match(audit.params[2],/"serviceDurationMinutes":75/);assert.match(audit.params[2],/customer requested new slot/);});

test('invalid service duration is rejected and rolled back',async()=>{const{db,calls}=assignmentDb();await assert.rejects(()=>assignPersistentJob(db,{jobId:'j1',technicianId:'t1',scheduledAt:'2026-09-15T10:00:00Z',serviceDurationMinutes:0,actorUserId:'d1'}),/Invalid service duration/);assert.ok(calls.some(c=>c.sql==='ROLLBACK'));});

test('reassignment conflict and cross-city assignment roll back',async()=>{const a=assignmentDb({status:'scheduled',conflict:true});await assert.rejects(()=>reassignPersistentJob(a.db,{jobId:'j1',technicianId:'t1',scheduledAt:'2026-09-15T10:00:00Z',actorUserId:'d1',reason:'operations'}),/scheduling conflict/);assert.ok(a.calls.some(c=>c.sql==='ROLLBACK'));const b=assignmentDb({cityEligible:false});await assert.rejects(()=>assignPersistentJob(b.db,{jobId:'j1',technicianId:'t1',scheduledAt:'2026-09-15T10:00:00Z',actorUserId:'d1'}),/not eligible for this city/);assert.ok(b.calls.some(c=>c.sql==='ROLLBACK'));});

test('assignment rejects missing skill unavailable technician and conflicts',async()=>{for(const [opts,msg] of [[{skill:false},/lacks required skill/],[{available:false},/unavailable/],[{conflict:true},/scheduling conflict/]]){const{db,calls}=assignmentDb(opts);await assert.rejects(()=>assignPersistentJob(db,{jobId:'j1',technicianId:'t1',scheduledAt:'2026-09-15T10:00:00Z',actorUserId:'d1'}),msg);assert.ok(calls.some(c=>c.sql==='ROLLBACK'));}});
