import test from 'node:test';
import assert from 'node:assert/strict';
import { listDispatchCandidates, assignPersistentJob, reassignPersistentJob } from '../src/dispatch/persistent-dispatch.mjs';

test('candidate query ranks eligible technicians by proximity then workload and rating', async()=>{const calls=[];const db={query:async(sql,params)=>{calls.push({sql,params});if(/FROM service_jobs j LEFT JOIN service_locations/.test(sql))return{rows:[{id:'j1',city_id:'riyadh',status:'pending_assignment',scheduled_at:'2026-09-15T09:00:00Z',required_skill_code:'ro-install',latitude:'24.700000',longitude:'46.680000'}]};if(/FROM technicians t/.test(sql))return{rows:[{technician_id:'near',distance_km:'1.20',jobs_in_window:0,avg_rating:'4.70'}]};throw new Error(`unexpected query: ${sql}`)}};const result=await listDispatchCandidates(db,'j1',{windowEnd:'2026-09-15T13:00:00Z'});assert.equal(result.candidates[0].technician_id,'near');const q=calls.find(c=>/FROM technicians t/.test(c.sql));assert.match(q.sql,/technician_locations/);assert.match(q.sql,/6371/);assert.match(q.sql,/distance_km ASC NULLS LAST, jobs_in_window ASC, avg_rating DESC/);});

function assignmentDb({skill=true,available=true,conflict=false,status='pending_assignment',cityEligible=true}={}){const calls=[];const client={async query(sql,params=[]){calls.push({sql,params});if(['BEGIN','COMMIT','ROLLBACK'].includes(sql))return{rows:[]};if(/service_jobs WHERE id=\$1 FOR UPDATE/.test(sql))return{rows:[{id:'j1',city_id:'riyadh',status,required_skill_code:'ro-install',technician_id:'old-tech',scheduled_at:'2026-09-15T09:00:00Z'}]};if(/FROM technicians WHERE/.test(sql))return{rows:cityEligible?[{id:'t1',city_id:'riyadh',is_active:true}]:[]};if(/FROM technician_skills/.test(sql))return{rows:skill?[{'?column?':1}]:[]};if(/FROM technician_availability/.test(sql))return{rows:available?[{'?column?':1}]:[]};if(/SELECT id FROM service_jobs/.test(sql))return{rows:conflict?[{id:'j-conflict'}]:[]};if(/UPDATE service_jobs/.test(sql))return{rows:[{id:'j1',technician_id:'t1',status:'scheduled',scheduled_at:params[2]}]};if(/INSERT INTO audit_log/.test(sql))return{rows:[]};throw new Error(`unexpected query: ${sql}`)},release(){calls.push({sql:'RELEASE'})}};return{db:{connect:async()=>client},calls};}

test('assignment commits only for pending job',async()=>{const{db,calls}=assignmentDb();const job=await assignPersistentJob(db,{jobId:'j1',technicianId:'t1',scheduledAt:'2026-09-15T10:00:00Z',actorUserId:'d1'});assert.equal(job.status,'scheduled');assert.ok(calls.some(c=>c.sql==='COMMIT'));});

test('second dispatcher cannot overwrite an already scheduled job',async()=>{const{db,calls}=assignmentDb({status:'scheduled'});await assert.rejects(()=>assignPersistentJob(db,{jobId:'j1',technicianId:'t1',scheduledAt:'2026-09-15T10:00:00Z',actorUserId:'d2'}),/already assigned/);assert.ok(calls.some(c=>c.sql==='ROLLBACK'));assert.ok(!calls.some(c=>/UPDATE service_jobs/.test(c.sql)));});

test('explicit reassignment requires a reason',async()=>{const{db}=assignmentDb({status:'scheduled'});await assert.rejects(()=>reassignPersistentJob(db,{jobId:'j1',technicianId:'t1',scheduledAt:'2026-09-15T10:00:00Z',actorUserId:'d1'}),/reason is required/);});

test('explicit reassignment revalidates eligibility and records audit',async()=>{const{db,calls}=assignmentDb({status:'scheduled'});const job=await reassignPersistentJob(db,{jobId:'j1',technicianId:'t1',scheduledAt:'2026-09-15T10:00:00Z',actorUserId:'d1',reason:'customer requested new slot'});assert.equal(job.technician_id,'t1');const audit=calls.find(c=>/INSERT INTO audit_log/.test(c.sql));assert.ok(audit);assert.match(audit.sql,/job.reassigned/);assert.match(audit.params[2],/old-tech/);assert.match(audit.params[2],/customer requested new slot/);assert.ok(calls.some(c=>c.sql==='COMMIT'));});

test('reassignment conflict rolls back',async()=>{const{db,calls}=assignmentDb({status:'scheduled',conflict:true});await assert.rejects(()=>reassignPersistentJob(db,{jobId:'j1',technicianId:'t1',scheduledAt:'2026-09-15T10:00:00Z',actorUserId:'d1',reason:'operations'}),/scheduling conflict/);assert.ok(calls.some(c=>c.sql==='ROLLBACK'));});

test('cross-city technician is rejected and rolled back',async()=>{const{db,calls}=assignmentDb({cityEligible:false});await assert.rejects(()=>assignPersistentJob(db,{jobId:'j1',technicianId:'t1',scheduledAt:'2026-09-15T10:00:00Z',actorUserId:'d1'}),/not eligible for this city/);assert.ok(calls.some(c=>c.sql==='ROLLBACK'));});

test('assignment rejects missing skill unavailable technician and conflicts',async()=>{for(const [opts,msg] of [[{skill:false},/lacks required skill/],[{available:false},/unavailable/],[{conflict:true},/scheduling conflict/]]){const{db,calls}=assignmentDb(opts);await assert.rejects(()=>assignPersistentJob(db,{jobId:'j1',technicianId:'t1',scheduledAt:'2026-09-15T10:00:00Z',actorUserId:'d1'}),msg);assert.ok(calls.some(c=>c.sql==='ROLLBACK'));}});
