import test from 'node:test';
import assert from 'node:assert/strict';
import { routePersistentRequest } from '../src/http/persistent-router.mjs';
import { approvePurchaseOrder, createPurchaseOrder, createSupplier, receivePurchaseOrder } from '../src/purchasing/operations.mjs';

function transactionalClient(handler){const calls=[];return{calls,db:{query:async()=>({rows:[]}),connect:async()=>({query:async(sql,params=[])=>{calls.push({sql,params});if(['BEGIN','COMMIT','ROLLBACK'].includes(sql))return{rows:[]};return handler(sql,params);},release(){}})}};}

test('finance reads purchasing counters',async()=>{const db={query:async sql=>{assert.match(sql,/open_orders/);return{rows:[{open_orders:3,pending_approval:1}]};}};const result=await routePersistentRequest({method:'GET',url:'/api/v1/purchasing/stats',role:'finance',db});assert.equal(result.status,200);assert.equal(result.data.stats.open_orders,3);});

test('manager lists overdue purchase orders with line details',async()=>{const db={query:async(sql,params)=>{assert.match(sql,/JSON_AGG/);assert.deepEqual(params,['فلتر','overdue',10,0]);return{rows:[{id:'po1',items:[],total_count:2}]};}};const result=await routePersistentRequest({method:'GET',url:'/api/v1/purchasing/orders',role:'branch_manager',context:{query:'فلتر',status:'overdue',limit:'10'},db});assert.equal(result.status,200);assert.equal(result.data.pagination.total,2);});

test('unauthorized support cannot read or mutate purchasing',async()=>{const db={query:async()=>{throw new Error('must not query');}};assert.equal((await routePersistentRequest({method:'GET',url:'/api/v1/purchasing/orders',role:'support',db})).status,403);assert.equal((await routePersistentRequest({method:'POST',url:'/api/v1/purchasing/suppliers',role:'support',db})).status,403);});

test('supplier creation writes audit in one transaction',async()=>{const {db,calls}=transactionalClient(async(sql)=>{if(/INSERT INTO suppliers/.test(sql))return{rows:[{id:'s1',name:'مورد سبيل'}]};if(/INSERT INTO audit_log/.test(sql))return{rows:[]};throw new Error(`unexpected ${sql}`);});const supplier=await createSupplier(db,{name:'مورد سبيل',actorUserId:'m1'});assert.equal(supplier.id,'s1');assert.ok(calls.some(c=>c.sql==='COMMIT'));assert.ok(calls.some(c=>c.params[1]==='supplier.created'));});

test('purchase order calculates subtotal and persists its lines',async()=>{let line=0;const {db,calls}=transactionalClient(async(sql,params)=>{if(/CROSS JOIN warehouses/.test(sql))return{rows:[{supplier_id:'s1',warehouse_id:'main'}]};if(/FROM inventory_items/.test(sql))return{rows:[{id:'i1'},{id:'i2'}]};if(/INSERT INTO purchase_orders/.test(sql))return{rows:[{id:'po1',subtotal:140}]};if(/INSERT INTO purchase_order_items/.test(sql))return{rows:[{id:`l${++line}`,item_id:params[1]}]};if(/INSERT INTO audit_log/.test(sql))return{rows:[]};throw new Error(`unexpected ${sql}`);});const result=await createPurchaseOrder(db,{poNumber:'PO-1',supplierId:'s1',warehouseId:'main',notes:'',items:[{itemId:'i1',quantity:2,unitCost:50},{itemId:'i2',quantity:4,unitCost:10}],actorUserId:'m1'});assert.equal(result.items.length,2);assert.ok(calls.some(c=>/INSERT INTO purchase_orders/.test(c.sql)&&c.params[5]===140));});

test('only draft purchase orders can be approved',async()=>{const {db}=transactionalClient(async sql=>{if(/SELECT \* FROM purchase_orders/.test(sql))return{rows:[{id:'po1',status:'received'}]};throw new Error(`unexpected ${sql}`);});await assert.rejects(()=>approvePurchaseOrder(db,{purchaseOrderId:'po1',actorUserId:'m1'}),/not approvable/);});

test('partial purchase receipt updates inventory and order status atomically',async()=>{const {db,calls}=transactionalClient(async(sql)=>{if(/SELECT \* FROM purchase_orders/.test(sql))return{rows:[{id:'po1',status:'approved',warehouse_id:'main',po_number:'PO-1'}]};if(/FROM purchase_order_items/.test(sql))return{rows:[{id:'l1',item_id:'i1',ordered_quantity:'10',received_quantity:'0',unit_cost:'42'}]};if(/UPDATE purchase_order_items|INSERT INTO inventory_balances|UPDATE inventory_items|INSERT INTO inventory_movements|INSERT INTO audit_log/.test(sql))return{rows:[]};if(/UPDATE purchase_orders SET status/.test(sql))return{rows:[{id:'po1',status:'partially_received'}]};throw new Error(`unexpected ${sql}`);});const order=await receivePurchaseOrder(db,{purchaseOrderId:'po1',lines:[{purchaseOrderItemId:'l1',quantity:4}],actorUserId:'m1'});assert.equal(order.status,'partially_received');assert.ok(calls.some(c=>/inventory_movements/.test(c.sql)));assert.ok(calls.some(c=>c.sql==='COMMIT'));});

test('purchase receipt rejects quantity above remaining order',async()=>{const {db,calls}=transactionalClient(async sql=>{if(/SELECT \* FROM purchase_orders/.test(sql))return{rows:[{id:'po1',status:'approved'}]};if(/FROM purchase_order_items/.test(sql))return{rows:[{id:'l1',ordered_quantity:'10',received_quantity:'8'}]};throw new Error(`unexpected ${sql}`);});await assert.rejects(()=>receivePurchaseOrder(db,{purchaseOrderId:'po1',lines:[{purchaseOrderItemId:'l1',quantity:3}],actorUserId:'m1'}),/over-receipt/);assert.ok(calls.some(c=>c.sql==='ROLLBACK'));});

test('purchase order route validates duplicate lines before transaction',async()=>{const db={query:async()=>({rows:[]}),connect:async()=>{throw new Error('must not connect');}};const body={poNumber:'PO-1',supplierId:'s1',warehouseId:'main',items:[{itemId:'i1',quantity:1,unitCost:2},{itemId:'i1',quantity:2,unitCost:2}]};const result=await routePersistentRequest({method:'POST',url:'/api/v1/purchasing/orders',role:'branch_manager',context:{userId:'m1'},body,db});assert.equal(result.status,400);});
