"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import PreviewAuthGuard from "../preview-auth-guard";

const apiBase=process.env.NEXT_PUBLIC_SUBIL_API_URL?.replace(/\/$/,"")||"";
type Filter="all"|"active"|"inactive";
type Stats={total:number;active:number;inactive:number;available_now:number;busy_now:number;avg_rating:number|string};
type Technician={id:string;mobile:string;city_id:string;branch_id?:string;compensation_policy_id?:string;is_active:boolean;skills:string[];jobs_today:number;active_jobs:number;completed_30d:number;on_time_30d:number;avg_rating:number|string;rating_count:number};
type Performance=Technician&{assigned:number;completed:number;cancelled:number;active:number;on_time:number;avg_completion_minutes:number|string;total_payout:number|string;pending_payout:number|string};
type RecentJob={id:string;external_order_id?:string;customer_name:string;address_text?:string;status:string;scheduled_at?:string;completed_at?:string};

const seed:Technician[]=[
  {id:"TECH-12",mobile:"+966501234567",city_id:"الرياض",branch_id:"الرياض",compensation_policy_id:"initial-margin-30",is_active:true,skills:["ro-install","ro-maintenance"],jobs_today:4,active_jobs:1,completed_30d:38,on_time_30d:35,avg_rating:4.9,rating_count:31},
  {id:"TECH-08",mobile:"+966502345678",city_id:"الرياض",branch_id:"الرياض",compensation_policy_id:"initial-margin-30",is_active:true,skills:["jumbo","tank-cleaning"],jobs_today:3,active_jobs:0,completed_30d:32,on_time_30d:27,avg_rating:4.7,rating_count:26},
  {id:"TECH-04",mobile:"+966503456789",city_id:"الرياض",branch_id:"الرياض",compensation_policy_id:"initial-margin-30",is_active:true,skills:["ro-maintenance"],jobs_today:2,active_jobs:1,completed_30d:29,on_time_30d:25,avg_rating:4.8,rating_count:23},
  {id:"TECH-02",mobile:"+966504567890",city_id:"الرياض",branch_id:"الرياض",compensation_policy_id:"initial-margin-30",is_active:false,skills:["ro-install"],jobs_today:0,active_jobs:0,completed_30d:8,on_time_30d:6,avg_rating:4.4,rating_count:9}
];
const initialStats:Stats={total:4,active:3,inactive:1,available_now:1,busy_now:2,avg_rating:4.7};
const dateFormatter=new Intl.DateTimeFormat("ar-SA",{dateStyle:"medium",timeStyle:"short"});
const number=(value:number|string)=>Number(value||0).toLocaleString("ar-SA",{maximumFractionDigits:1});
const percent=(part:number,total:number)=>total?Math.round(part/total*100):0;
function jobStatus(value:string){return({scheduled:"مجدولة",en_route:"في الطريق",arrived:"وصل",in_progress:"قيد التنفيذ",completed:"مكتملة",cancelled:"ملغاة"} as Record<string,string>)[value]||value;}

export default function TechniciansPage(){
  const [technicians,setTechnicians]=useState<Technician[]>(apiBase?[]:seed),[stats,setStats]=useState<Stats>(initialStats),[filter,setFilter]=useState<Filter>("all"),[query,setQuery]=useState(""),[search,setSearch]=useState(""),[page,setPage]=useState(0),[total,setTotal]=useState(apiBase?0:seed.length),[loading,setLoading]=useState(Boolean(apiBase)),[error,setError]=useState(""),[reloadKey,setReloadKey]=useState(0);
  const [performance,setPerformance]=useState<Performance|null>(null),[recentJobs,setRecentJobs]=useState<RecentJob[]>([]),[performanceLoading,setPerformanceLoading]=useState(false),[period,setPeriod]=useState(30);
  const [statusTarget,setStatusTarget]=useState<Technician|null>(null),[statusSaving,setStatusSaving]=useState(false),[statusError,setStatusError]=useState(""),[canManage,setCanManage]=useState(!apiBase);
  const shown=useMemo(()=>{if(apiBase)return technicians;const q=query.trim().toLowerCase();return technicians.filter(item=>(filter==="all"||(filter==="active")===item.is_active)&&(!q||[item.id,item.mobile,item.city_id,item.branch_id,...item.skills].some(value=>value?.toLowerCase().includes(q))));},[technicians,filter,query]);
  useEffect(()=>{const role=sessionStorage.getItem("subil_role");setCanManage(!apiBase||["branch_manager","admin","super_admin"].includes(role||""));},[]);
  useEffect(()=>{if(!apiBase)return;const timer=window.setTimeout(()=>{setPage(0);setSearch(query.trim());},300);return()=>window.clearTimeout(timer);},[query]);
  useEffect(()=>{if(!apiBase)return;const controller=new AbortController(),token=sessionStorage.getItem("subil_session"),params=new URLSearchParams({status:filter,limit:"20",offset:String(page*20)});if(search)params.set("q",search);setLoading(true);fetch(`${apiBase}/api/v1/technicians?${params}`,{headers:{Authorization:`Bearer ${token}`},signal:controller.signal}).then(async response=>{const payload=await response.json();if(!response.ok)throw new Error(response.status===401?"انتهت جلسة الدخول.":"تعذر تحميل الفنيين.");return payload;}).then(payload=>{setTechnicians(payload.technicians||[]);setTotal(Number(payload.pagination?.total||0));setError("");}).catch(reason=>{if(reason instanceof DOMException&&reason.name==="AbortError")return;setError(reason instanceof Error?reason.message:"تعذر تحميل الفنيين.");}).finally(()=>setLoading(false));return()=>controller.abort();},[filter,page,search,reloadKey]);
  useEffect(()=>{if(!apiBase)return;const controller=new AbortController(),token=sessionStorage.getItem("subil_session");fetch(`${apiBase}/api/v1/technicians/stats`,{headers:{Authorization:`Bearer ${token}`},signal:controller.signal}).then(async response=>{if(!response.ok)throw new Error("تعذر تحميل مؤشرات الفنيين.");return response.json();}).then(payload=>setStats(payload.stats)).catch(reason=>{if(reason instanceof DOMException&&reason.name==="AbortError")return;setError(reason instanceof Error?reason.message:"تعذر تحميل المؤشرات.");});return()=>controller.abort();},[reloadKey]);
  async function openPerformance(item:Technician,nextPeriod=period){setPerformanceLoading(true);setPerformance({...item,assigned:0,completed:0,cancelled:0,active:0,on_time:0,avg_completion_minutes:0,total_payout:0,pending_payout:0});setRecentJobs([]);if(!apiBase){setPerformance({...item,assigned:item.completed_30d+item.active_jobs+2,completed:item.completed_30d,cancelled:2,active:item.active_jobs,on_time:item.on_time_30d,avg_completion_minutes:82,total_payout:item.completed_30d*74,pending_payout:220});setRecentJobs([{id:"JOB-1048",external_order_id:"1048",customer_name:"محمد القحطاني",address_text:"حي الياسمين",status:"completed",scheduled_at:"2026-09-15T08:30:00Z",completed_at:"2026-09-15T09:45:00Z"}]);setPerformanceLoading(false);return;}try{const to=new Date(),from=new Date(to.getTime()-nextPeriod*86400000),token=sessionStorage.getItem("subil_session"),params=new URLSearchParams({from:from.toISOString(),to:to.toISOString()}),response=await fetch(`${apiBase}/api/v1/technicians/${encodeURIComponent(item.id)}/performance?${params}`,{headers:{Authorization:`Bearer ${token}`}}),payload=await response.json();if(!response.ok)throw new Error("تعذر تحميل تفاصيل الأداء.");setPerformance(payload.technician);setRecentJobs(payload.recentJobs||[]);}catch(reason){setError(reason instanceof Error?reason.message:"تعذر تحميل تفاصيل الأداء.");setPerformance(null);}finally{setPerformanceLoading(false);}}
  async function changePeriod(value:number){setPeriod(value);if(performance){const item=technicians.find(entry=>entry.id===performance.id)||performance;await openPerformance(item,value);}}
  async function saveStatus(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!statusTarget)return;const next=!statusTarget.is_active,reason=String(new FormData(event.currentTarget).get("reason")||"").trim();if(!next&&reason.length<3){setStatusError("اكتب سبب تعطيل الفني.");return;}setStatusSaving(true);setStatusError("");try{if(apiBase){const token=sessionStorage.getItem("subil_session"),response=await fetch(`${apiBase}/api/v1/technicians/${encodeURIComponent(statusTarget.id)}/status`,{method:"PATCH",headers:{"content-type":"application/json",Authorization:`Bearer ${token}`},body:JSON.stringify({isActive:next,reason})}),payload=await response.json();if(!response.ok)throw new Error(payload.error==="technician_status_unchanged"?"حالة الفني محدثة مسبقًا.":"تعذر تحديث حالة الفني.");setReloadKey(value=>value+1);}else{setTechnicians(list=>list.map(item=>item.id===statusTarget.id?{...item,is_active:next}:item));setStats(value=>({...value,active:value.active+(next?1:-1),inactive:value.inactive+(next?-1:1)}));}setStatusTarget(null);}catch(reasonValue){setStatusError(reasonValue instanceof Error?reasonValue.message:"تعذر تحديث حالة الفني.");}finally{setStatusSaving(false);}}
  const displayTotal=apiBase?total:shown.length;
  return <PreviewAuthGuard><main className="customers-page technicians-page"><header className="customers-top"><a className="customers-brand" href="/"><span>S</span><strong>سبيل</strong><small>نظام التشغيل</small></a><nav className="section-nav" aria-label="تنقل الأقسام"><a href="/">لوحة التحكم</a><a href="/jobs">المهام</a><a href="/customers">العملاء</a><a className="active" href="/technicians">الفنيون</a><a href="/maintenance">الصيانة</a></nav><div className="profile-avatar">م</div></header><div className="customers-wrap">
    <div className="demo-notice"><span>نسخة المعاينة</span> إدارة الفريق مبنية على الصلاحيات وسجل التدقيق.</div>
    <div className="page-head"><div><p>التشغيل الميداني</p><h1>إدارة الفنيين</h1><span>متابعة الجاهزية والحمل والأداء وجودة الخدمة</span></div></div>
    <section className="technician-stats" aria-label="مؤشرات الفنيين"><button className={filter==="all"?"active":""} onClick={()=>{setFilter("all");setPage(0);}}><span>إجمالي الفنيين</span><strong>{number(stats.total)}</strong></button><button className={filter==="active"?"active":""} onClick={()=>{setFilter("active");setPage(0);}}><span>النشطون</span><strong>{number(stats.active)}</strong></button><button><span>متاحون الآن</span><strong>{number(stats.available_now)}</strong></button><button><span>في مهمة</span><strong>{number(stats.busy_now)}</strong></button><button className={filter==="inactive"?"active danger":""} onClick={()=>{setFilter("inactive");setPage(0);}}><span>غير النشطين</span><strong>{number(stats.inactive)}</strong></button><button><span>متوسط التقييم</span><strong>★ {number(stats.avg_rating)}</strong></button></section>
    {error&&<div className="api-error" role="alert">{error}</div>}
    <section className="panel technicians-worklist"><div className="customers-toolbar"><div><h2>فريق الفنيين</h2><p>{loading?"جارٍ التحميل...":`${displayTotal.toLocaleString("ar-SA")} فني`}</p></div><div className="jobs-toolbar-actions"><select value={filter} onChange={event=>{setFilter(event.target.value as Filter);setPage(0);}} aria-label="تصفية الفنيين"><option value="all">الكل</option><option value="active">نشط</option><option value="inactive">غير نشط</option></select><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="ابحث بالجوال أو المدينة أو المهارة" aria-label="بحث في الفنيين"/></div></div>
      {shown.length?<><div className="table-wrap"><table><thead><tr><th>الفني</th><th>المدينة والفرع</th><th>المهارات</th><th>حمل اليوم</th><th>إنجاز ٣٠ يومًا</th><th>الالتزام</th><th>التقييم</th><th>الحالة والإجراء</th></tr></thead><tbody>{shown.map(item=><tr key={item.id}><td><button className="technician-link" onClick={()=>openPerformance(item)}><strong>{item.id}</strong><small dir="ltr">{item.mobile}</small></button></td><td><strong>{item.city_id}</strong><small>{item.branch_id||"دون فرع"}</small></td><td><div className="skill-list">{item.skills?.length?item.skills.map(skill=><span key={skill}>{skill}</span>):<small>مهارة عامة</small>}</div></td><td><strong>{number(item.jobs_today)} مهام</strong><small>{number(item.active_jobs)} جارية</small></td><td><strong>{number(item.completed_30d)} مكتملة</strong><small>آخر ٣٠ يومًا</small></td><td><span className={`performance-rate ${percent(item.on_time_30d,item.completed_30d)>=85?"good":"warn"}`}>{percent(item.on_time_30d,item.completed_30d).toLocaleString("ar-SA")}%</span></td><td><strong>★ {number(item.avg_rating)}</strong><small>{number(item.rating_count)} تقييم</small></td><td><span className={`technician-state ${item.is_active?"active":"inactive"}`}>{item.is_active?"نشط":"غير نشط"}</span>{canManage&&<button className="text-action" onClick={()=>{setStatusTarget(item);setStatusError("");}}>{item.is_active?"تعطيل":"تفعيل"}</button>}</td></tr>)}</tbody></table></div>{apiBase&&total>20&&<nav className="customers-pagination"><button className="secondary-button" disabled={loading||page===0} onClick={()=>setPage(value=>value-1)}>السابق</button><span>صفحة {(page+1).toLocaleString("ar-SA")} من {Math.ceil(total/20).toLocaleString("ar-SA")}</span><button className="secondary-button" disabled={loading||(page+1)*20>=total} onClick={()=>setPage(value=>value+1)}>التالي</button></nav>}</>:<div className="empty-state">لا يوجد فنيون مطابقون.</div>}
    </section>
    {performance&&<div className="modal-backdrop" onMouseDown={event=>{if(event.target===event.currentTarget&&!performanceLoading)setPerformance(null);}}><section className="customer-modal technician-performance-modal" role="dialog" aria-modal="true"><div className="modal-head"><div><h2>أداء الفني {performance.id}</h2><p dir="ltr">{performance.mobile}</p></div><button onClick={()=>setPerformance(null)} aria-label="إغلاق">×</button></div><div className="period-tabs"><button className={period===30?"active":""} onClick={()=>changePeriod(30)}>٣٠ يومًا</button><button className={period===90?"active":""} onClick={()=>changePeriod(90)}>٩٠ يومًا</button></div>{performanceLoading?<div className="detail-loading">جارٍ تحميل الأداء...</div>:<><div className="performance-grid"><article><span>المهام المكتملة</span><strong>{number(performance.completed)}</strong></article><article><span>الالتزام بالموعد</span><strong>{percent(performance.on_time,performance.completed).toLocaleString("ar-SA")}%</strong></article><article><span>متوسط التقييم</span><strong>★ {number(performance.avg_rating)}</strong></article><article><span>المستحقات المعتمدة</span><strong>{number(performance.total_payout)} ر.س</strong></article><article><span>تحت الاعتماد</span><strong>{number(performance.pending_payout)} ر.س</strong></article><article><span>المهام الجارية</span><strong>{number(performance.active)}</strong></article></div><div className="performance-jobs"><h3>أحدث المهام</h3>{recentJobs.length?recentJobs.map(job=><div key={job.id}><span><strong>#{job.external_order_id||job.id} · {job.customer_name}</strong><small>{job.address_text||"—"}</small></span><span><b>{jobStatus(job.status)}</b><small>{job.scheduled_at?dateFormatter.format(new Date(job.scheduled_at)):"غير مجدولة"}</small></span></div>):<p>لا توجد مهام خلال الفترة.</p>}</div></>}</section></div>}
    {statusTarget&&<div className="modal-backdrop"><section className="customer-modal" role="dialog" aria-modal="true"><div className="modal-head"><div><h2>{statusTarget.is_active?"تعطيل الفني":"تفعيل الفني"}</h2><p>{statusTarget.id}</p></div><button disabled={statusSaving} onClick={()=>setStatusTarget(null)} aria-label="إغلاق">×</button></div><form onSubmit={saveStatus}>{statusTarget.is_active?<label>سبب التعطيل<input name="reason" placeholder="مثال: إجازة أو انتهاء التعاقد" disabled={statusSaving}/></label>:<p className="activation-note">سيصبح الفني متاحًا للإسناد بعد التفعيل وفق جدول توفره ومهاراته.</p>}{statusError&&<p className="form-error" role="alert">{statusError}</p>}<div className="modal-actions"><button className="secondary-button" type="button" disabled={statusSaving} onClick={()=>setStatusTarget(null)}>إلغاء</button><button className={`primary-button ${statusTarget.is_active?"danger-button":""}`} disabled={statusSaving}>{statusSaving?"جارٍ الحفظ...":statusTarget.is_active?"تأكيد التعطيل":"تأكيد التفعيل"}</button></div></form></section></div>}
  </div></main></PreviewAuthGuard>;
}
