import { withTransaction } from '../persistence/transactions.mjs';
export async function savePushSubscription(db,{userId,endpoint,p256dh,auth,userAgent=''}){const{rows:[row]}=await db.query(`INSERT INTO push_subscriptions(user_id,endpoint,p256dh,auth_secret,user_agent)VALUES($1,$2,$3,$4,$5)ON CONFLICT(user_id,endpoint)DO UPDATE SET p256dh=EXCLUDED.p256dh,auth_secret=EXCLUDED.auth_secret,user_agent=EXCLUDED.user_agent,is_active=true,last_seen_at=now(),updated_at=now()RETURNING id,user_id,endpoint,is_active,created_at,updated_at`,[userId,endpoint,p256dh,auth,userAgent]);return row}
export async function disablePushSubscription(db,{userId,endpoint}){const{rows:[row]}=await db.query(`UPDATE push_subscriptions SET is_active=false,updated_at=now()WHERE user_id=$1 AND endpoint=$2 AND is_active RETURNING id,endpoint,is_active`,[userId,endpoint]);return row||null}
export async function getNotificationSettings(db,userId){const{rows:[preferences]}=await db.query(`INSERT INTO notification_preferences(user_id)VALUES($1)ON CONFLICT(user_id)DO UPDATE SET user_id=EXCLUDED.user_id RETURNING service_updates,maintenance_reminders,marketing,updated_at`,[userId]);const{rows:[counts]}=await db.query(`SELECT COUNT(*)FILTER(WHERE is_active)::integer AS active_devices FROM push_subscriptions WHERE user_id=$1`,[userId]);return{preferences,activeDevices:counts?.active_devices||0}}
export async function updateNotificationSettings(db,{userId,serviceUpdates,maintenanceReminders,marketing}){const{rows:[row]}=await db.query(`INSERT INTO notification_preferences(user_id,service_updates,maintenance_reminders,marketing)VALUES($1,$2,$3,$4)ON CONFLICT(user_id)DO UPDATE SET service_updates=EXCLUDED.service_updates,maintenance_reminders=EXCLUDED.maintenance_reminders,marketing=EXCLUDED.marketing,updated_at=now()RETURNING service_updates,maintenance_reminders,marketing,updated_at`,[userId,serviceUpdates,maintenanceReminders,marketing]);return row}
export async function preparePushDeliveries(db,{limit=100}={}){return withTransaction(db,async c=>{const{rows:events}=await c.query(`SELECT ne.id,ne.event_type,ne.payload,ne.customer_id FROM notification_events ne WHERE ne.status='pending'AND 'push'=ANY(ne.channels)ORDER BY ne.created_at LIMIT $1 FOR UPDATE SKIP LOCKED`,[limit]);let created=0;for(const event of events){const result=await c.query(`INSERT INTO push_deliveries(event_id,subscription_id)SELECT $1,ps.id FROM push_subscriptions ps JOIN customers cst ON cst.user_id=ps.user_id LEFT JOIN notification_preferences np ON np.user_id=ps.user_id WHERE cst.id=$2 AND ps.is_active AND CASE WHEN $3 LIKE 'marketing.%'THEN COALESCE(np.marketing,false)WHEN $3 LIKE 'maintenance.%'THEN COALESCE(np.maintenance_reminders,true)ELSE COALESCE(np.service_updates,true)END ON CONFLICT DO NOTHING`,[event.id,event.customer_id,event.event_type]);created+=result.rowCount||0}return{events:events.length,deliveries:created}})}

export async function claimPushDeliveries(db,{limit=50}={}){return withTransaction(db,async c=>{const{rows}=await c.query(`SELECT pd.id,pd.event_id,pd.subscription_id,pd.attempts,ps.endpoint,ps.p256dh,ps.auth_secret,ne.event_type,ne.payload FROM push_deliveries pd JOIN push_subscriptions ps ON ps.id=pd.subscription_id JOIN notification_events ne ON ne.id=pd.event_id WHERE pd.status IN('pending','failed')AND pd.next_attempt_at<=now()AND pd.attempts<5 AND ps.is_active ORDER BY pd.next_attempt_at,pd.created_at LIMIT $1 FOR UPDATE OF pd SKIP LOCKED`,[limit]);if(rows.length)await c.query(`UPDATE push_deliveries SET status='processing',attempts=attempts+1,updated_at=now()WHERE id=ANY($1::uuid[])`,[rows.map(x=>x.id)]);return rows.map(x=>({...x,attempts:Number(x.attempts)+1}))})}

export async function settlePushDelivery(db,{delivery,success,providerMessageId=null,error=null,expired=false}){return withTransaction(db,async c=>{const terminal=!success&&delivery.attempts>=5;const status=success?'sent':terminal||expired?'cancelled':'failed';const delay=Math.min(3600,30*2**Math.max(0,delivery.attempts-1));await c.query(`UPDATE push_deliveries SET status=$2,provider_message_id=$3,last_error=$4,sent_at=CASE WHEN $2='sent'THEN now()ELSE sent_at END,next_attempt_at=CASE WHEN $2='failed'THEN now()+($5||' seconds')::interval ELSE next_attempt_at END,updated_at=now()WHERE id=$1`,[delivery.id,status,providerMessageId,error?String(error).slice(0,500):null,delay]);if(expired)await c.query(`UPDATE push_subscriptions SET is_active=false,updated_at=now()WHERE id=$1`,[delivery.subscription_id]);await c.query(`UPDATE notification_events ne SET status=summary.final_status,sent_at=CASE WHEN summary.final_status='sent'THEN COALESCE(ne.sent_at,now())ELSE ne.sent_at END FROM(SELECT event_id,CASE WHEN COUNT(*)FILTER(WHERE status IN('pending','processing','failed')AND attempts<5)>0 THEN 'processing'WHEN COUNT(*)FILTER(WHERE status='sent')>0 THEN 'sent'ELSE 'failed'END AS final_status FROM push_deliveries WHERE event_id=$1 GROUP BY event_id)summary WHERE ne.id=summary.event_id`,[delivery.event_id]);return{status,nextAttemptSeconds:status==='failed'?delay:null}})}

export async function processPushBatch(db,{sendPush,limit=50}={}){if(typeof sendPush!=='function')throw new Error('Push sender unavailable');await preparePushDeliveries(db,{limit:limit*2});const deliveries=await claimPushDeliveries(db,{limit}),result={claimed:deliveries.length,sent:0,retry:0,cancelled:0};for(const delivery of deliveries){try{const sent=await sendPush({subscription:{endpoint:delivery.endpoint,keys:{p256dh:delivery.p256dh,auth:delivery.auth_secret}},notification:notificationPayload(delivery)});await settlePushDelivery(db,{delivery,success:true,providerMessageId:sent?.messageId||null});result.sent++}catch(error){const expired=[404,410].includes(Number(error.status));const settled=await settlePushDelivery(db,{delivery,success:false,error:error.message||'push_failed',expired});if(settled.status==='failed')result.retry++;else result.cancelled++}}return result}

function notificationPayload(delivery){const payload=delivery.payload&&typeof delivery.payload==='object'?delivery.payload:{};return{title:payload.title||titleFor(delivery.event_type),body:payload.body||payload.message||'لديك تحديث جديد في سبيل',url:payload.url||'/',eventType:delivery.event_type}}
function titleFor(type){if(type?.startsWith('service.'))return'تحديث خدمة سبيل';if(type?.startsWith('maintenance.'))return'تذكير صيانة سبيل';if(type?.startsWith('marketing.'))return'عرض من سبيل';return'سبيل'}
