import{withTransaction}from'../persistence/transactions.mjs';
const riskWords=['استرجاع','تعويض','شكوى','ضمان','سعر','خصم','دفع','فاتورة','محامي','وزارة','refund','warranty','price','complaint'];
const tokenize=value=>String(value||'').toLowerCase().replace(/[^a-z0-9\u0600-\u06ff ]/g,' ').split(/\s+/).filter(x=>x.length>2);

export async function createCareSuggestion(db,{conversationId,actorUserId}){return withTransaction(db,async c=>{
 const conversation=(await c.query(`SELECT cc.id,cc.channel,cc.customer_id,c.name AS customer_name FROM customer_conversations cc LEFT JOIN customers c ON c.id=cc.customer_id WHERE cc.id=$1 FOR SHARE`,[conversationId])).rows[0];if(!conversation)return null;
 const messages=(await c.query(`SELECT direction,body,sent_at FROM conversation_messages WHERE conversation_id=$1 ORDER BY sent_at DESC LIMIT 8`,[conversationId])).rows.reverse();
 const articles=(await c.query(`SELECT id,title,category,content,keywords FROM ai_knowledge_articles WHERE status='approved' ORDER BY updated_at DESC LIMIT 100`)).rows;
 const latest=[...messages].reverse().find(x=>x.direction==='inbound')?.body||'';const terms=new Set(tokenize(latest));
 const scored=articles.map(article=>{const articleTerms=tokenize(`${article.title} ${(article.keywords||[]).join(' ')} ${article.content}`);return{article,score:articleTerms.reduce((n,x)=>n+(terms.has(x)?1:0),0)}}).sort((a,b)=>b.score-a.score);const match=scored[0]?.score>0?scored[0].article:null;
 const risk=riskWords.some(word=>latest.toLowerCase().includes(word))?'high':match?'low':'medium';const confidence=match?Math.min(.95,.65+scored[0].score*.05):.35;
 const generated=match?`شكرًا لتواصلك مع سبيل. ${match.content.slice(0,1200)}\n\nهل يمكنني مساعدتك في أي تفاصيل إضافية؟`:`شكرًا لتواصلك مع سبيل. تم استلام استفسارك وسيقوم الفريق بمراجعته وتزويدك بالمعلومة الدقيقة في أقرب وقت.`;
 const suggestion=(await c.query(`INSERT INTO ai_suggestions(conversation_id,prompt_snapshot,generated_text,confidence,risk_level,sources,created_by)VALUES($1,$2::jsonb,$3,$4,$5,$6::jsonb,$7)RETURNING *`,[conversationId,JSON.stringify({channel:conversation.channel,messageCount:messages.length,latestInbound:latest.slice(0,1000)}),generated,confidence,risk,JSON.stringify(match?[{id:match.id,title:match.title,category:match.category}]:[]),actorUserId])).rows[0];
 await audit(c,actorUserId,'ai.suggestion_created','ai_suggestion',suggestion.id,{conversationId,risk,confidence,sourceCount:match?1:0});return suggestion;
})}

export async function reviewSuggestion(db,{suggestionId,decision,actorUserId}){return withTransaction(db,async c=>{const suggestion=(await c.query(`UPDATE ai_suggestions SET status=$2,reviewed_by=$3,reviewed_at=now(),updated_at=now()WHERE id=$1 AND status='draft' RETURNING *`,[suggestionId,decision,actorUserId])).rows[0];if(!suggestion)return null;await audit(c,actorUserId,`ai.suggestion_${decision}`,'ai_suggestion',suggestionId,{risk:suggestion.risk_level});return suggestion})}

export async function useSuggestion(db,{suggestionId,actorUserId}){return withTransaction(db,async c=>{const suggestion=(await c.query(`SELECT * FROM ai_suggestions WHERE id=$1 FOR UPDATE`,[suggestionId])).rows[0];if(!suggestion)return null;if(suggestion.status!=='approved')throw new Error('Suggestion is not approved');const conversation=(await c.query(`SELECT * FROM customer_conversations WHERE id=$1 FOR UPDATE`,[suggestion.conversation_id])).rows[0];if(!conversation||conversation.status==='closed')throw new Error('Conversation is unavailable');const message=(await c.query(`INSERT INTO conversation_messages(conversation_id,direction,sender_type,body,delivery_status,sent_by,metadata)VALUES($1,'outbound','agent',$2,'queued',$3,$4::jsonb)RETURNING *`,[conversation.id,suggestion.generated_text,actorUserId,JSON.stringify({aiSuggestionId:suggestion.id})])).rows[0];await c.query(`UPDATE customer_conversations SET status='waiting_customer',assigned_to=COALESCE(assigned_to,$2),unread_count=0,last_message_at=$3,updated_at=now()WHERE id=$1`,[conversation.id,actorUserId,message.sent_at]);await c.query(`UPDATE ai_suggestions SET status='used',updated_at=now()WHERE id=$1`,[suggestion.id]);await audit(c,actorUserId,'ai.suggestion_used','ai_suggestion',suggestion.id,{conversationId:conversation.id,messageId:message.id});return{suggestion:{...suggestion,status:'used'},message}})}

export async function createKnowledgeArticle(db,input){return withTransaction(db,async c=>{const article=(await c.query(`INSERT INTO ai_knowledge_articles(title,category,content,keywords,status,created_by,approved_by)VALUES($1,$2,$3,$4,$5,$6,CASE WHEN $5='approved'THEN $6 ELSE NULL END)RETURNING *`,[input.title,input.category,input.content,input.keywords,input.status,input.actorUserId])).rows[0];await audit(c,input.actorUserId,'ai.knowledge_created','ai_knowledge_article',article.id,{category:input.category,status:input.status});return article})}
async function audit(c,u,a,t,id,d){await c.query(`INSERT INTO audit_log(actor_user_id,action,entity_type,entity_id,data)VALUES($1,$2,$3,$4,$5::jsonb)`,[u,a,t,id,JSON.stringify(d)])}
