import{withTransaction}from'../persistence/transactions.mjs';import{listDispatchCandidates}from'../dispatch/persistent-dispatch.mjs';
const DEFAULT_ORG='00000000-0000-4000-8000-000000000001';

export function scoreDispatchCandidates(candidates){return candidates.map(candidate=>{const distance=candidate.distance_km===null?null:Number(candidate.distance_km),rating=Number(candidate.avg_rating||0),jobs=Number(candidate.jobs_in_window||0);const distancePoints=distance===null?10:Math.max(0,40-distance*2),ratingPoints=Math.min(25,rating*5),loadPoints=Math.max(0,20-jobs*5),eligibilityPoints=15;const score=Math.round((distancePoints+ratingPoints+loadPoints+eligibilityPoints)*100)/100;const reasons=[distance===null?'الموقع غير متاح':`يبعد ${distance.toFixed(1)} كم`,rating?`تقييم ${rating.toFixed(1)} من 5`:'لا يوجد تقييم بعد',jobs?`${jobs} مهمة متداخلة في النافذة`:'لا توجد مهام متداخلة','متاح ويمتلك المهارة المطلوبة'];const risks=[];if(distance===null)risks.push('المسافة غير معروفة');if(rating&&rating<3.5)risks.push('التقييم أقل من المستهدف');if(jobs>2)risks.push('ضغط مهام مرتفع');return{...candidate,score,reasons,risks}}).sort((a,b)=>b.score-a.score||String(a.technician_id).localeCompare(String(b.technician_id)))}

export async function createDispatchRecommendation(db,{jobId,windowStart,windowEnd,limit=10,actorUserId,organizationId=DEFAULT_ORG}){const result=await listDispatchCandidates(db,jobId,{windowStart,windowEnd,limit,tenantId:organizationId});const ranked=scoreDispatchCandidates(result.candidates),best=ranked[0]||null,risk=!best?'high':best.risks.length?'medium':'low',explanation=best?`المرشح الأعلى هو ${best.technician_id} بنتيجة ${best.score}؛ ${best.reasons.join('، ')}.`:'لا يوجد فني مؤهل ومتاح ضمن النافذة المطلوبة.';return withTransaction(db,async c=>{await c.query(`UPDATE ai_dispatch_recommendations SET status='expired'WHERE organization_id=$1 AND job_id=$2 AND status='pending'`,[organizationId,jobId]);const recommendation=(await c.query(`INSERT INTO ai_dispatch_recommendations(organization_id,job_id,window_start,window_end,candidates,recommended_technician_id,recommended_score,explanation,risk_level,created_by)VALUES($1,$2,$3,$4,$5::jsonb,$6,$7,$8,$9,$10)RETURNING *`,[organizationId,jobId,result.windowStart,result.windowEnd,JSON.stringify(ranked),best?.technician_id||null,best?.score||null,explanation,risk,actorUserId])).rows[0];await audit(c,actorUserId,'ai.dispatch_recommended','ai_dispatch_recommendation',recommendation.id,{organizationId,jobId,candidateCount:ranked.length,recommendedTechnicianId:best?.technician_id||null,score:best?.score||null});return{recommendation,job:result.job,candidates:ranked}})}

export async function reviewDispatchRecommendation(db,{recommendationId,decision,technicianId,note,actorUserId,organizationId=DEFAULT_ORG}){return withTransaction(db,async c=>{const current=(await c.query(`SELECT * FROM ai_dispatch_recommendations WHERE id=$1 AND organization_id=$2 AND status='pending' FOR UPDATE`,[recommendationId,organizationId])).rows[0];if(!current)return null;const candidates=Array.isArray(current.candidates)?current.candidates:JSON.parse(current.candidates||'[]');const selected=decision==='approved'?(technicianId||current.recommended_technician_id):null;if(decision==='approved'&&!candidates.some(x=>x.technician_id===selected))throw new Error('Selected technician is not a candidate');const updated=(await c.query(`UPDATE ai_dispatch_recommendations SET status=$3,selected_technician_id=$4,reviewed_by=$5,reviewed_at=now(),review_note=$6 WHERE id=$1 AND organization_id=$2 RETURNING *`,[recommendationId,organizationId,decision,selected,actorUserId,note||''])).rows[0];await audit(c,actorUserId,`ai.dispatch_${decision}`,'ai_dispatch_recommendation',recommendationId,{organizationId,jobId:current.job_id,selectedTechnicianId:selected,note:note||''});return updated})}
async function audit(c,u,a,t,id,d){await c.query(`INSERT INTO audit_log(actor_user_id,action,entity_type,entity_id,data)VALUES($1,$2,$3,$4,$5::jsonb)`,[u,a,t,id,JSON.stringify(d)])}
