import{withTransaction}from'../persistence/transactions.mjs';

export async function generateExecutiveInsights(db,{actorUserId,date=new Date().toISOString().slice(0,10)}){return withTransaction(db,async c=>{
 const metrics=(await c.query(`SELECT
  (SELECT COUNT(*)::integer FROM service_jobs WHERE status NOT IN('completed','cancelled')AND scheduled_at<now())AS overdue_jobs,
  (SELECT COUNT(*)::integer FROM job_escalations WHERE resolved_at IS NULL)AS open_escalations,
  (SELECT COUNT(*)::integer FROM inventory_items i WHERE i.is_active AND COALESCE((SELECT SUM(quantity)FROM inventory_balances WHERE item_id=i.id),0)<=i.reorder_level)AS low_stock_items,
  (SELECT COUNT(*)::integer FROM technician_settlements WHERE status='pending_approval')AS pending_settlements,
  (SELECT COALESCE(SUM(payout_amount),0)::numeric(14,2) FROM technician_settlements WHERE status='pending_approval')AS pending_settlement_value,
  (SELECT COUNT(*)::integer FROM abandoned_carts WHERE status IN('open','notified'))AS abandoned_carts,
  (SELECT COALESCE(SUM(cart_value),0)::numeric(14,2) FROM abandoned_carts WHERE status IN('open','notified'))AS abandoned_cart_value,
  (SELECT COUNT(*)::integer FROM campaign_recipients WHERE status='failed'AND created_at>=now()-interval '7 days')AS failed_campaign_deliveries,
  (SELECT COUNT(*)::integer FROM customer_conversations WHERE status='pending_agent')AS pending_conversations`)).rows[0];
 const definitions=[];
 add(definitions,Number(metrics.overdue_jobs)>0,{fingerprint:'overdue_jobs',domain:'operations',severity:Number(metrics.overdue_jobs)>10?'critical':'high',title:'مهام ميدانية متأخرة',summary:`يوجد ${metrics.overdue_jobs} مهمة تجاوزت وقتها المجدول.`,action:'مراجعة قائمة المهام المتأخرة وإعادة توزيعها حسب المدينة والطاقة المتاحة.',metrics:{count:Number(metrics.overdue_jobs)}});
 add(definitions,Number(metrics.open_escalations)>0,{fingerprint:'open_escalations',domain:'operations',severity:'high',title:'تصعيدات تشغيلية مفتوحة',summary:`يوجد ${metrics.open_escalations} تصعيد يحتاج إلى تدخل.`,action:'تكليف مسؤول مناوب بمعالجة التصعيدات الأعلى عمرًا أولًا.',metrics:{count:Number(metrics.open_escalations)}});
 add(definitions,Number(metrics.low_stock_items)>0,{fingerprint:'low_stock',domain:'inventory',severity:'high',title:'أصناف عند حد إعادة الطلب',summary:`وصل ${metrics.low_stock_items} صنفًا إلى حد إعادة الطلب أو أقل.`,action:'مراجعة أوامر الشراء المفتوحة وإنشاء طلب توريد للأصناف الحرجة.',metrics:{count:Number(metrics.low_stock_items)}});
 add(definitions,Number(metrics.pending_settlements)>0,{fingerprint:'pending_settlements',domain:'finance',severity:'medium',title:'تسويات تنتظر الاعتماد',summary:`توجد ${metrics.pending_settlements} تسوية بقيمة ${Number(metrics.pending_settlement_value).toFixed(2)} ر.س.`,action:'مراجعة أدلة الإنجاز واعتماد أو رفض التسويات المتوقفة.',metrics:{count:Number(metrics.pending_settlements),value:Number(metrics.pending_settlement_value)}});
 add(definitions,Number(metrics.abandoned_carts)>0,{fingerprint:'abandoned_carts',domain:'marketing',severity:Number(metrics.abandoned_cart_value)>5000?'high':'medium',title:'قيمة مبيعات معرضة للفقد',summary:`هناك ${metrics.abandoned_carts} سلة متروكة بقيمة ${Number(metrics.abandoned_cart_value).toFixed(2)} ر.س.`,action:'تشغيل حملة الاستعادة ومراجعة السلال الأعلى قيمة أولًا.',metrics:{count:Number(metrics.abandoned_carts),value:Number(metrics.abandoned_cart_value)}});
 add(definitions,Number(metrics.failed_campaign_deliveries)>0,{fingerprint:'campaign_failures',domain:'marketing',severity:'medium',title:'فشل في تسليم رسائل الحملات',summary:`فشل تسليم ${metrics.failed_campaign_deliveries} رسالة خلال آخر 7 أيام.`,action:'فحص بيانات الاتصال وحالة مزود الإرسال قبل الحملة القادمة.',metrics:{count:Number(metrics.failed_campaign_deliveries)}});
 add(definitions,Number(metrics.pending_conversations)>0,{fingerprint:'pending_conversations',domain:'customer_care',severity:Number(metrics.pending_conversations)>20?'high':'medium',title:'محادثات تنتظر رد الفريق',summary:`يوجد ${metrics.pending_conversations} محادثة بانتظار الرد.`,action:'توزيع المحادثات حسب الأولوية وزمن الانتظار.',metrics:{count:Number(metrics.pending_conversations)}});
 const insights=[];for(const item of definitions){const row=(await c.query(`INSERT INTO ai_insights(fingerprint,detected_on,domain,severity,title,summary,recommended_action,metrics)VALUES($1,$2,$3,$4,$5,$6,$7,$8::jsonb)ON CONFLICT(fingerprint,detected_on)DO UPDATE SET severity=EXCLUDED.severity,title=EXCLUDED.title,summary=EXCLUDED.summary,recommended_action=EXCLUDED.recommended_action,metrics=EXCLUDED.metrics,updated_at=now()RETURNING *`,[item.fingerprint,date,item.domain,item.severity,item.title,item.summary,item.action,JSON.stringify(item.metrics)])).rows[0];insights.push(row)}
 const order={critical:0,high:1,medium:2,info:3};insights.sort((a,b)=>order[a.severity]-order[b.severity]);const priorities=insights.slice(0,5).map(x=>({insightId:x.id,severity:x.severity,title:x.title,action:x.recommended_action}));const summary=insights.length?`تم رصد ${insights.length} أولوية تنفيذية؛ منها ${insights.filter(x=>['critical','high'].includes(x.severity)).length} ذات أولوية مرتفعة.`:'لا توجد استثناءات تشغيلية مهمة اليوم.';
 const brief=(await c.query(`INSERT INTO ai_executive_briefs(brief_date,summary,metrics,priorities,generated_by)VALUES($1,$2,$3::jsonb,$4::jsonb,$5)ON CONFLICT(brief_date)DO UPDATE SET summary=EXCLUDED.summary,metrics=EXCLUDED.metrics,priorities=EXCLUDED.priorities,generated_by=EXCLUDED.generated_by,updated_at=now()RETURNING *`,[date,summary,JSON.stringify(metrics),JSON.stringify(priorities),actorUserId])).rows[0];await audit(c,actorUserId,'ai.executive_scan_run','ai_executive_brief',brief.id,{date,insightCount:insights.length});return{brief,insights,metrics};
})}

export async function updateInsight(db,{insightId,status,note,actorUserId}){return withTransaction(db,async c=>{const insight=(await c.query(`UPDATE ai_insights SET status=$2,acknowledged_by=CASE WHEN $2='acknowledged'THEN $3 ELSE acknowledged_by END,resolved_by=CASE WHEN $2 IN('resolved','dismissed')THEN $3 ELSE resolved_by END,resolved_at=CASE WHEN $2 IN('resolved','dismissed')THEN now()ELSE resolved_at END,resolution_note=$4,updated_at=now()WHERE id=$1 AND status='open' RETURNING *`,[insightId,status,actorUserId,note||''])).rows[0];if(!insight)return null;await audit(c,actorUserId,`ai.insight_${status}`,'ai_insight',insightId,{note:note||''});return insight})}
function add(list,condition,item){if(condition)list.push(item)}
async function audit(c,u,a,t,id,d){await c.query(`INSERT INTO audit_log(actor_user_id,action,entity_type,entity_id,data)VALUES($1,$2,$3,$4,$5::jsonb)`,[u,a,t,id,JSON.stringify(d)])}
