import{withTransaction}from'../persistence/transactions.mjs';

export function buildMarketingRecommendations(metrics,channels=[]){const list=[],cartValue=Number(metrics.abandoned_value||0),activeCarts=Number(metrics.active_carts||0),failed=Number(metrics.failed_deliveries||0),published=Number(metrics.published_content||0),paid=Number(metrics.paid_orders||0),attributed=Number(metrics.attributed_orders||0),coverage=paid?attributed/paid*100:100;
 if(activeCarts>0)list.push({fingerprint:'cart-recovery',type:'recovery_campaign',priority:cartValue>=5000?'high':'medium',title:'حملة استعادة السلال الأعلى قيمة',rationale:`هناك ${activeCarts} سلة نشطة بقيمة ${cartValue.toFixed(2)} ر.س.`,action:'إنشاء حملة واتساب مخصصة للسلال الأعلى قيمة ثم تشغيلها بعد المراجعة.',impact:`استعادة جزء من ${cartValue.toFixed(2)} ر.س.`,evidence:{activeCarts,cartValue}});
 if(failed>0)list.push({fingerprint:'delivery-quality',type:'delivery_fix',priority:failed>20?'high':'medium',title:'تحسين جودة بيانات الاتصال',rationale:`فشل تسليم ${failed} رسالة خلال 7 أيام.`,action:'مراجعة الأرقام والبريد وحالة المزود قبل إطلاق حملة جديدة.',impact:'رفع معدل الوصول وخفض تكلفة الرسالة المهدرة',evidence:{failedDeliveries:failed}});
 if(published<8)list.push({fingerprint:'content-cadence',type:'content_plan',priority:'medium',title:'رفع وتيرة المحتوى المنشور',rationale:`نُشر ${published} محتوى فقط خلال 30 يومًا.`,action:'إعداد خطة أسبوعية تجمع محتوى تعليميًا وعروض الصيانة وقصص العملاء.',impact:'زيادة الزيارات العضوية ونقاط الاتصال المؤهلة',evidence:{publishedLast30Days:published,target:8}});
 if(coverage<70)list.push({fingerprint:'attribution-coverage',type:'attribution_fix',priority:'high',title:'معالجة فجوة الإسناد التسويقي',rationale:`نسبة الطلبات المنسوبة إلى مصدر تسويقي ${coverage.toFixed(1)}% فقط.`,action:'توحيد وسوم UTM وربط معرّف الزائر بالعميل عند الدخول والدفع.',impact:'قرارات ميزانية أدق وقياس حقيقي للعائد',evidence:{paidOrders:paid,attributedOrders:attributed,coverage}});
 const usable=channels.filter(x=>Number(x.spend)>0&&Number(x.roas)>0).sort((a,b)=>Number(b.roas)-Number(a.roas));if(usable.length>1&&Number(usable[0].roas)>=Number(usable.at(-1).roas)*1.5)list.push({fingerprint:`budget-${usable[0].name}-${usable.at(-1).name}`,type:'budget_shift',priority:'medium',title:`مراجعة توزيع ميزانية ${usable[0].name}`,rationale:`عائد ${usable[0].name} هو ${Number(usable[0].roas).toFixed(2)}× مقابل ${Number(usable.at(-1).roas).toFixed(2)}× لقناة ${usable.at(-1).name}.`,action:`اختبار تحويل 15% من ميزانية ${usable.at(-1).name} إلى ${usable[0].name} لمدة أسبوع مع حد إيقاف واضح.`,impact:'تحسين العائد دون زيادة إجمالي الميزانية',evidence:{best:usable[0],weakest:usable.at(-1)}});return list}

export async function scanMarketingRecommendations(db,{actorUserId}){return withTransaction(db,async c=>{const metrics=(await c.query(`SELECT(SELECT COUNT(*)::integer FROM abandoned_carts WHERE status IN('open','notified'))AS active_carts,(SELECT COALESCE(SUM(cart_value),0)::numeric(14,2)FROM abandoned_carts WHERE status IN('open','notified'))AS abandoned_value,(SELECT COUNT(*)::integer FROM campaign_recipients WHERE status='failed'AND created_at>=now()-interval '7 days')AS failed_deliveries,(SELECT COUNT(*)::integer FROM marketing_content WHERE status='published'AND published_at>=now()-interval '30 days')AS published_content,(SELECT COUNT(*)::integer FROM orders WHERE paid_at>=now()-interval '30 days')AS paid_orders,(SELECT COUNT(*)::integer FROM order_attribution oa JOIN orders o ON o.id=oa.order_id WHERE o.paid_at>=now()-interval '30 days')AS attributed_orders`)).rows[0];const channels=(await c.query(`SELECT lt.source AS name,COALESCE(SUM(o.total_ex_vat),0)::numeric(14,2)AS revenue,COALESCE(sp.spend,0)::numeric(14,2)AS spend,CASE WHEN COALESCE(sp.spend,0)=0 THEN NULL ELSE ROUND(SUM(o.total_ex_vat)/sp.spend,2)END AS roas FROM order_attribution oa JOIN orders o ON o.id=oa.order_id JOIN marketing_touches lt ON lt.id=oa.last_touch_id LEFT JOIN LATERAL(SELECT SUM(amount)AS spend FROM marketing_spend WHERE source=lt.source AND spent_on>=CURRENT_DATE-30)sp ON true WHERE o.paid_at>=now()-interval '30 days'GROUP BY lt.source,sp.spend`)).rows;const definitions=buildMarketingRecommendations(metrics,channels),recommendations=[];for(const item of definitions){recommendations.push((await c.query(`INSERT INTO ai_marketing_recommendations(fingerprint,recommendation_type,priority,title,rationale,recommended_action,projected_impact,evidence,created_by)VALUES($1,$2,$3,$4,$5,$6,$7,$8::jsonb,$9)ON CONFLICT(fingerprint)WHERE status IN('new','approved','scheduled')DO UPDATE SET priority=EXCLUDED.priority,title=EXCLUDED.title,rationale=EXCLUDED.rationale,recommended_action=EXCLUDED.recommended_action,projected_impact=EXCLUDED.projected_impact,evidence=EXCLUDED.evidence,updated_at=now()RETURNING *`,[item.fingerprint,item.type,item.priority,item.title,item.rationale,item.action,item.impact,JSON.stringify(item.evidence),actorUserId])).rows[0])}await audit(c,actorUserId,'ai.marketing_scan_run','ai_marketing_recommendation','batch',{recommendationCount:recommendations.length});return{metrics,channels,recommendations}})}

export async function updateMarketingRecommendation(db,{recommendationId,status,note,actorUserId}){return withTransaction(db,async c=>{const current=(await c.query(`SELECT * FROM ai_marketing_recommendations WHERE id=$1 FOR UPDATE`,[recommendationId])).rows[0];if(!current)return null;const allowed={new:['approved','dismissed'],approved:['scheduled','dismissed'],scheduled:['completed','dismissed']}[current.status]||[];if(!allowed.includes(status))throw new Error('Invalid marketing recommendation transition');const updated=(await c.query(`UPDATE ai_marketing_recommendations SET status=$2,reviewed_by=$3,reviewed_at=now(),outcome_note=$4,updated_at=now()WHERE id=$1 RETURNING *`,[recommendationId,status,actorUserId,note||''])).rows[0];await audit(c,actorUserId,`ai.marketing_${status}`,'ai_marketing_recommendation',recommendationId,{from:current.status,to:status,note:note||''});return updated})}
async function audit(c,u,a,t,id,d){await c.query(`INSERT INTO audit_log(actor_user_id,action,entity_type,entity_id,data)VALUES($1,$2,$3,$4,$5::jsonb)`,[u,a,t,id,JSON.stringify(d)])}
