import{createWooCommerceCatalogClient}from'../integrations/woocommerce-catalog.mjs';
import{withTransaction}from'../persistence/transactions.mjs';
const DEFAULT_ORG='00000000-0000-4000-8000-000000000001';
export function evaluateRecommendationOutcome({baseline=0,current=0,direction='increase'}={}){
 const b=Number(baseline||0),n=Number(current||0),delta=n-b,pct=b?delta/Math.abs(b)*100:null;
 const improved=direction==='decrease'?n<b:n>b;
 return{baseline:b,current:n,delta:Number(delta.toFixed(2)),changePct:pct===null?null:Number(pct.toFixed(1)),improved};
}

export function buildMarketingMemoryEntry({recommendationId,type,action,baseline,current,direction='increase',observedAt=new Date().toISOString()}={}){
 const outcome=evaluateRecommendationOutcome({baseline,current,direction});
 return{recommendationId:recommendationId||null,type:type||'unknown',action:action||'',direction,outcome,observedAt,
  lesson:outcome.improved?'repeat_or_scale':'revise_or_stop'};
}

export function applyMarketingMemory(recommendations=[],memory=[]){
 const lessons=new Map();
 for(const m of memory){const key=String(m?.type||'');if(!key)continue;const x=lessons.get(key)||{wins:0,losses:0};m?.lesson==='repeat_or_scale'?x.wins++:m?.lesson==='revise_or_stop'&&x.losses++;lessons.set(key,x)}
 return recommendations.map(item=>{const x=lessons.get(String(item.type))||{wins:0,losses:0},total=x.wins+x.losses,confidence=total?x.wins/total:null;
  return{...item,memory:{samples:total,wins:x.wins,losses:x.losses,confidence:confidence===null?null:Number(confidence.toFixed(2))},
   learnedAction:total>=2&&confidence>=.6?'prefer':total>=2&&confidence<=.3?'deprioritize':'neutral'};
 });
}

export function rankLearnedRecommendations(recommendations=[]){
 const priority={high:3,medium:2,low:1},learned={prefer:2,neutral:1,deprioritize:0};
 return recommendations.map((item,index)=>({...item,decisionScore:(priority[item.priority]||1)*10+(learned[item.learnedAction]??1)*3+Math.min(3,Number(item?.memory?.samples||0)),_index:index}))
  .sort((a,b)=>b.decisionScore-a.decisionScore||a._index-b._index)
  .map(({_index,...item})=>item);
}

export function buildMarketingRecommendations(metrics,channels=[],store=null){const list=[],cartValue=Number(metrics.abandoned_value||0),activeCarts=Number(metrics.active_carts||0),failed=Number(metrics.failed_deliveries||0),published=Number(metrics.published_content||0),paid=Number(metrics.paid_orders||0),attributed=Number(metrics.attributed_orders||0),coverage=paid?attributed/paid*100:100;
 if(activeCarts>0)list.push({fingerprint:'cart-recovery',type:'recovery_campaign',priority:cartValue>=5000?'high':'medium',title:'حملة استعادة السلال الأعلى قيمة',rationale:`هناك ${activeCarts} سلة نشطة بقيمة ${cartValue.toFixed(2)} ر.س.`,action:'إنشاء حملة واتساب مخصصة للسلال الأعلى قيمة ثم تشغيلها بعد المراجعة.',impact:`استعادة جزء من ${cartValue.toFixed(2)} ر.س.`,evidence:{activeCarts,cartValue}});
 if(failed>0)list.push({fingerprint:'delivery-quality',type:'delivery_fix',priority:failed>20?'high':'medium',title:'تحسين جودة بيانات الاتصال',rationale:`فشل تسليم ${failed} رسالة خلال 7 أيام.`,action:'مراجعة الأرقام والبريد وحالة المزود قبل إطلاق حملة جديدة.',impact:'رفع معدل الوصول وخفض تكلفة الرسالة المهدرة',evidence:{failedDeliveries:failed}});
 if(published<8)list.push({fingerprint:'content-cadence',type:'content_plan',priority:'medium',title:'رفع وتيرة المحتوى المنشور',rationale:`نُشر ${published} محتوى فقط خلال 30 يومًا.`,action:'إعداد خطة أسبوعية تجمع محتوى تعليميًا وعروض الصيانة وقصص العملاء.',impact:'زيادة الزيارات العضوية ونقاط الاتصال المؤهلة',evidence:{publishedLast30Days:published,target:8}});
 if(coverage<70)list.push({fingerprint:'attribution-coverage',type:'attribution_fix',priority:'high',title:'معالجة فجوة الإسناد التسويقي',rationale:`نسبة الطلبات المنسوبة إلى مصدر تسويقي ${coverage.toFixed(1)}% فقط.`,action:'توحيد وسوم UTM وربط معرّف الزائر بالعميل عند الدخول والدفع.',impact:'قرارات ميزانية أدق وقياس حقيقي للعائد',evidence:{paidOrders:paid,attributedOrders:attributed,coverage}});
 if(store?.products?.seo?.needsWork>0)list.push({fingerprint:'store-seo-queue',type:'content_plan',priority:store.products.seo.highPriority>0?'high':'medium',title:'تنفيذ قائمة تحسين SEO للمنتجات',rationale:`هناك ${store.products.seo.needsWork} منتجًا يحتاج تحسين SEO، منها ${store.products.seo.highPriority} بأولوية عالية.`,action:'معالجة العناوين والأوصاف وAlt للصور بدءًا من أعلى المنتجات أولوية، مع الحفاظ على الروابط الحالية.',impact:'رفع جودة صفحات المنتجات وفرص الظهور العضوي والتحويل',evidence:{seo:store.products.seo}});
 if(store?.customers?.atRisk>0)list.push({fingerprint:'store-winback-risk',type:'recovery_campaign',priority:store.customers.atRisk>=10?'high':'medium',title:'رحلة Win-back للعملاء المعرضين للفقد',rationale:`تم رصد ${store.customers.atRisk} عميلًا متكررًا دون طلب حديث خلال 90 يومًا.`,action:'إنشاء رحلة استعادة تعتمد على المحتوى والصيانة والمنتج التالي المناسب، ثم إرسالها فقط للعملاء الموافقين على التسويق.',impact:'استعادة جزء من العملاء السابقين ورفع معدل إعادة الشراء',evidence:{atRisk:store.customers.atRisk,dormant90d:store.customers.dormant90d}});
 if(store?.orders?.aov>0)list.push({fingerprint:'store-aov-growth',type:'content_plan',priority:'medium',title:'رفع متوسط قيمة الطلب عبر الباقات',rationale:`متوسط قيمة الطلب في العينة الحالية ${Number(store.orders.aov).toFixed(2)} ر.س.`,action:'اختبار إبراز الباقات والمنتجات المكملة في صفحات المنتجات والسلة، وقياس أثر Cross-sell وUpsell أسبوعيًا.',impact:'رفع متوسط قيمة الطلب دون الاعتماد على زيادة الزيارات فقط',evidence:{aov:store.orders.aov,revenue:store.orders.revenue}});
 const usable=channels.filter(x=>Number(x.spend)>0&&Number(x.roas)>0).sort((a,b)=>Number(b.roas)-Number(a.roas));if(usable.length>1&&Number(usable[0].roas)>=Number(usable.at(-1).roas)*1.5)list.push({fingerprint:`budget-${usable[0].name}-${usable.at(-1).name}`,type:'budget_shift',priority:'medium',title:`مراجعة توزيع ميزانية ${usable[0].name}`,rationale:`عائد ${usable[0].name} هو ${Number(usable[0].roas).toFixed(2)}× مقابل ${Number(usable.at(-1).roas).toFixed(2)}× لقناة ${usable.at(-1).name}.`,action:`اختبار تحويل 15% من ميزانية ${usable.at(-1).name} إلى ${usable[0].name} لمدة أسبوع مع حد إيقاف واضح.`,impact:'تحسين العائد دون زيادة إجمالي الميزانية',evidence:{best:usable[0],weakest:usable.at(-1)}});return list}

export async function scanMarketingRecommendations(db,{actorUserId,organizationId=DEFAULT_ORG}){
 const woo=createWooCommerceCatalogClient();let store=null;
 if(woo.configured){try{store=await woo.getStoreIntelligence()}catch{}}
 return withTransaction(db,async c=>{const metrics=(await c.query(`SELECT(SELECT COUNT(*)::integer FROM abandoned_carts WHERE organization_id=$1 AND status IN('open','notified'))AS active_carts,(SELECT COALESCE(SUM(cart_value),0)::numeric(14,2)FROM abandoned_carts WHERE organization_id=$1 AND status IN('open','notified'))AS abandoned_value,(SELECT COUNT(*)::integer FROM campaign_recipients WHERE organization_id=$1 AND status='failed'AND created_at>=now()-interval '7 days')AS failed_deliveries,(SELECT COUNT(*)::integer FROM marketing_content WHERE organization_id=$1 AND status='published'AND published_at>=now()-interval '30 days')AS published_content,(SELECT COUNT(*)::integer FROM orders o JOIN customers c ON c.id=o.customer_id WHERE c.organization_id=$1 AND o.paid_at>=now()-interval '30 days')AS paid_orders,(SELECT COUNT(*)::integer FROM order_attribution oa JOIN orders o ON o.id=oa.order_id JOIN customers c ON c.id=o.customer_id WHERE oa.organization_id=$1 AND c.organization_id=$1 AND o.paid_at>=now()-interval '30 days')AS attributed_orders`,[organizationId])).rows[0];const channels=(await c.query(`SELECT lt.source AS name,COALESCE(SUM(o.total_ex_vat),0)::numeric(14,2)AS revenue,COALESCE(sp.spend,0)::numeric(14,2)AS spend,CASE WHEN COALESCE(sp.spend,0)=0 THEN NULL ELSE ROUND(SUM(o.total_ex_vat)/sp.spend,2)END AS roas FROM order_attribution oa JOIN orders o ON o.id=oa.order_id JOIN customers cst ON cst.id=o.customer_id JOIN marketing_touches lt ON lt.id=oa.last_touch_id AND lt.organization_id=$1 LEFT JOIN LATERAL(SELECT SUM(amount)AS spend FROM marketing_spend WHERE organization_id=$1 AND source=lt.source AND spent_on>=CURRENT_DATE-30)sp ON true WHERE oa.organization_id=$1 AND cst.organization_id=$1 AND o.paid_at>=now()-interval '30 days'GROUP BY lt.source,sp.spend`,[organizationId])).rows;const definitions=buildMarketingRecommendations(metrics,channels,store),recommendations=[];for(const item of definitions){recommendations.push((await c.query(`INSERT INTO ai_marketing_recommendations(organization_id,fingerprint,recommendation_type,priority,title,rationale,recommended_action,projected_impact,evidence,created_by)VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9::jsonb,$10)ON CONFLICT(organization_id,fingerprint)WHERE status IN('new','approved','scheduled')DO UPDATE SET priority=EXCLUDED.priority,title=EXCLUDED.title,rationale=EXCLUDED.rationale,recommended_action=EXCLUDED.recommended_action,projected_impact=EXCLUDED.projected_impact,evidence=EXCLUDED.evidence,updated_at=now()RETURNING *`,[organizationId,item.fingerprint,item.type,item.priority,item.title,item.rationale,item.action,item.impact,JSON.stringify(item.evidence),actorUserId])).rows[0])}await audit(c,actorUserId,'ai.marketing_scan_run','ai_marketing_recommendation','batch',{organizationId,recommendationCount:recommendations.length});return{metrics,channels,store,recommendations}})}

export async function updateMarketingRecommendation(db,{recommendationId,status,note,actorUserId,organizationId=DEFAULT_ORG}){return withTransaction(db,async c=>{const current=(await c.query(`SELECT * FROM ai_marketing_recommendations WHERE id=$1 AND organization_id=$2 FOR UPDATE`,[recommendationId,organizationId])).rows[0];if(!current)return null;const allowed={new:['approved','dismissed'],approved:['scheduled','dismissed'],scheduled:['completed','dismissed']}[current.status]||[];if(!allowed.includes(status))throw new Error('Invalid marketing recommendation transition');const updated=(await c.query(`UPDATE ai_marketing_recommendations SET status=$3,reviewed_by=$4,reviewed_at=now(),outcome_note=$5,updated_at=now()WHERE id=$1 AND organization_id=$2 RETURNING *`,[recommendationId,organizationId,status,actorUserId,note||''])).rows[0];await audit(c,actorUserId,`ai.marketing_${status}`,'ai_marketing_recommendation',recommendationId,{organizationId,from:current.status,to:status,note:note||''});return updated})}
async function audit(c,u,a,t,id,d){await c.query(`INSERT INTO audit_log(actor_user_id,action,entity_type,entity_id,data)VALUES($1,$2,$3,$4,$5::jsonb)`,[u,a,t,id,JSON.stringify(d)])}
