import{withTransaction}from'../persistence/transactions.mjs';
const DEFAULT_ORG='00000000-0000-4000-8000-000000000001';

export function detectSalesSignals(customer,now=new Date()){const opportunities=[],days=value=>value?Math.floor((now-new Date(value))/86400000):9999,lifetime=Number(customer.lifetime_value||0),cart=Number(customer.abandoned_value||0),due=Number(customer.maintenance_due||0),pending=Number(customer.pending_conversations||0),recency=days(customer.last_paid_at);
 if(due>0)opportunities.push({type:'maintenance_due',score:Math.min(98,80+due*5),value:due*250,reason:`لدى العميل ${due} أصل مستحق للصيانة.`,action:'التواصل لحجز موعد الصيانة وعرض باقة القطع الدورية.',signals:{maintenanceDue:due}});
 if(cart>0)opportunities.push({type:'cart_recovery',score:Math.min(96,65+Math.round(cart/100)),value:cart,reason:`لدى العميل سلة متروكة بقيمة ${cart.toFixed(2)} ر.س.`,action:'مراجعة السلة والتواصل لمعالجة عائق إتمام الطلب.',signals:{abandonedValue:cart}});
 if(lifetime>=3000&&recency>=45)opportunities.push({type:'cross_sell',score:Math.min(92,65+Math.round(lifetime/1000)*3),value:Math.min(1500,lifetime*.2),reason:`عميل مرتفع القيمة بإجمالي مشتريات ${lifetime.toFixed(2)} ر.س. وآخر شراء قبل ${recency} يومًا.`,action:'اقتراح منتج مكمل أو باقة صيانة مناسبة لمشترياته السابقة.',signals:{lifetimeValue:lifetime,daysSincePurchase:recency}});
 if(customer.last_paid_at&&recency>=90)opportunities.push({type:'win_back',score:Math.min(90,55+Math.floor(recency/10)),value:Math.max(300,lifetime*.15),reason:`لم يشترِ العميل منذ ${recency} يومًا.`,action:'التواصل بعرض عودة مرتبط بآخر منتج أو خدمة اشتراها.',signals:{daysSincePurchase:recency,lifetimeValue:lifetime}});
 if(pending>0)opportunities.push({type:'conversation_followup',score:Math.min(85,60+pending*5),value:0,reason:`لدى العميل ${pending} محادثة تنتظر متابعة.`,action:'مراجعة المحادثة المفتوحة وتحويل الاستفسار إلى خطوة بيع واضحة.',signals:{pendingConversations:pending}});return opportunities.sort((a,b)=>b.score-a.score)}

export async function scanSalesOpportunities(db,{actorUserId,limit=500,organizationId=DEFAULT_ORG}){return withTransaction(db,async c=>{const customers=(await c.query(`SELECT c.id,c.name,u.mobile,COUNT(DISTINCT o.id)::integer AS order_count,COALESCE(SUM(o.total_ex_vat),0)::numeric(14,2)AS lifetime_value,MAX(o.paid_at)AS last_paid_at,(SELECT COUNT(*)::integer FROM installed_assets ia WHERE ia.customer_id=c.id AND ia.status='active'AND ia.next_maintenance_at<=now()+interval '30 days')AS maintenance_due,(SELECT COALESCE(SUM(cart_value),0)::numeric(14,2)FROM abandoned_carts ac WHERE ac.customer_id=c.id AND ac.organization_id=$1 AND ac.status IN('open','notified'))AS abandoned_value,(SELECT COUNT(*)::integer FROM customer_conversations cc WHERE cc.customer_id=c.id AND cc.organization_id=$1 AND cc.status='pending_agent')AS pending_conversations FROM customers c LEFT JOIN users u ON u.id=c.user_id LEFT JOIN orders o ON o.customer_id=c.id AND o.paid_at IS NOT NULL WHERE c.organization_id=$1 GROUP BY c.id,u.mobile ORDER BY c.created_at DESC LIMIT $2`,[organizationId,limit])).rows;let created=0,updated=0;const results=[];for(const customer of customers){for(const signal of detectSalesSignals(customer)){const row=(await c.query(`INSERT INTO ai_sales_opportunities(organization_id,customer_id,opportunity_type,score,estimated_value,reason,recommended_action,signals,created_by)VALUES($1,$2,$3,$4,$5,$6,$7,$8::jsonb,$9)ON CONFLICT(organization_id,customer_id,opportunity_type)WHERE status IN('new','approved','contacted')DO UPDATE SET score=EXCLUDED.score,estimated_value=EXCLUDED.estimated_value,reason=EXCLUDED.reason,recommended_action=EXCLUDED.recommended_action,signals=EXCLUDED.signals,updated_at=now()RETURNING *, (xmax=0)AS inserted`,[organizationId,customer.id,signal.type,signal.score,signal.value,signal.reason,signal.action,JSON.stringify(signal.signals),actorUserId])).rows[0];if(row.inserted)created++;else updated++;results.push(row)}}await audit(c,actorUserId,'ai.sales_scan_run','ai_sales_opportunity','batch',{organizationId,customersScanned:customers.length,created,updated});return{customersScanned:customers.length,created,updated,opportunities:results}})}

export async function updateSalesOpportunity(db,{opportunityId,status,assignedTo,note,actorUserId,organizationId=DEFAULT_ORG}){return withTransaction(db,async c=>{const current=(await c.query(`SELECT * FROM ai_sales_opportunities WHERE id=$1 AND organization_id=$2 FOR UPDATE`,[opportunityId,organizationId])).rows[0];if(!current)return null;const allowed={new:['approved','dismissed'],approved:['contacted','dismissed'],contacted:['converted','lost']}[current.status]||[];if(!allowed.includes(status))throw new Error('Invalid sales opportunity transition');const updated=(await c.query(`UPDATE ai_sales_opportunities SET status=$3,assigned_to=COALESCE($4,assigned_to),reviewed_by=$5,reviewed_at=now(),outcome_note=$6,updated_at=now()WHERE id=$1 AND organization_id=$2 RETURNING *`,[opportunityId,organizationId,status,assignedTo||null,actorUserId,note||''])).rows[0];await audit(c,actorUserId,`ai.sales_${status}`,'ai_sales_opportunity',opportunityId,{organizationId,from:current.status,to:status,note:note||''});return updated})}
async function audit(c,u,a,t,id,d){await c.query(`INSERT INTO audit_log(actor_user_id,action,entity_type,entity_id,data)VALUES($1,$2,$3,$4,$5::jsonb)`,[u,a,t,id,JSON.stringify(d)])}
