export type OfflineJob={id:string;status:string};
type Command={id:string;jobId:string;status:string;createdAt:string};
const DB="subil-technician-offline",VERSION=1;
function open(){return new Promise<IDBDatabase>((resolve,reject)=>{const request=indexedDB.open(DB,VERSION);request.onupgradeneeded=()=>{const db=request.result;if(!db.objectStoreNames.contains("cache"))db.createObjectStore("cache");if(!db.objectStoreNames.contains("commands"))db.createObjectStore("commands",{keyPath:"id"})};request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error)})}
async function transaction<T>(store:string,mode:IDBTransactionMode,work:(object:IDBObjectStore,done:(value:T)=>void)=>void){const db=await open();return new Promise<T>((resolve,reject)=>{const tx=db.transaction(store,mode),object=tx.objectStore(store);let value!:T;work(object,result=>{value=result});tx.oncomplete=()=>{db.close();resolve(value)};tx.onerror=()=>{db.close();reject(tx.error)};tx.onabort=()=>{db.close();reject(tx.error)}})}
export async function cacheJobs(jobs:OfflineJob[]){await transaction<void>("cache","readwrite",(s,done)=>{s.put({jobs,savedAt:new Date().toISOString()},"today");done()})}
export async function readCachedJobs(){return transaction<OfflineJob[]>("cache","readonly",(s,done)=>{const r=s.get("today");r.onsuccess=()=>done(Array.isArray(r.result?.jobs)?r.result.jobs:[])})}
export async function queueStatus(jobId:string,status:string){const command:Command={id:`${Date.now()}-${crypto.randomUUID()}`,jobId,status,createdAt:new Date().toISOString()};await transaction<void>("commands","readwrite",(s,done)=>{s.add(command);done()});return command}
export async function pendingCount(){return transaction<number>("commands","readonly",(s,done)=>{const r=s.count();r.onsuccess=()=>done(r.result)})}
async function commands(){return transaction<Command[]>("commands","readonly",(s,done)=>{const r=s.getAll();r.onsuccess=()=>done((r.result||[]).sort((a,b)=>a.createdAt.localeCompare(b.createdAt)))})}
async function removeCommand(id:string){await transaction<void>("commands","readwrite",(s,done)=>{s.delete(id);done()})}
export async function flushCommands(apiBase:string,token:string){const result={synced:0,conflicted:0,pending:0};for(const command of await commands()){try{const response=await fetch(`${apiBase}/api/v1/technicians/me/jobs/${command.jobId}/status`,{method:"PATCH",headers:{Authorization:`Bearer ${token}`,"content-type":"application/json"},body:JSON.stringify({status:command.status})});if(response.ok){await removeCommand(command.id);result.synced++;continue}if([404,409,422].includes(response.status)){await removeCommand(command.id);result.conflicted++;continue}if(response.status===401)break;result.pending++}catch{result.pending++;break}}result.pending=await pendingCount();return result}
export async function clearOfflineData(){await Promise.all([transaction<void>("cache","readwrite",(s,d)=>{s.clear();d()}),transaction<void>("commands","readwrite",(s,d)=>{s.clear();d()})])}
