import{withTransaction}from'../persistence/transactions.mjs';
export function scoreSeo({title='',body='',primaryKeyword='',metaDescription='',slug=''}){let score=0;const key=primaryKeyword.trim().toLowerCase();if(title.length>=20&&title.length<=65)score+=20;if(metaDescription.length>=70&&metaDescription.length<=160)score+=20;if(body.length>=300)score+=20;if(key&&title.toLowerCase().includes(key))score+=15;if(key&&body.toLowerCase().includes(key))score+=15;if(slug&&(!key||slug.toLowerCase().includes(key.replace(/\s+/g,'-'))))score+=10;return score}
export async function createContent(db,input){return withTransaction(db,async c=>{const seoScore=scoreSeo(input),item=(await c.query(
 `INSERT INTO marketing_content(title,slug,content_type,channel,body,primary_keyword,meta_description,seo_score,status,scheduled_at,created_by)
 VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11) RETURNING *`,[input.title,input.slug,input.contentType,input.channel,input.body,input.primaryKeyword,input.metaDescription,seoScore,input.scheduledAt?'scheduled':'draft',input.scheduledAt||null,input.actorUserId])).rows[0];await audit(c,input.actorUserId,'marketing.content_created','marketing_content',item.id,{seoScore,channel:input.channel});return item})}
const allowed={idea:['draft','cancelled'],draft:['review','scheduled','cancelled'],review:['draft','approved','cancelled'],approved:['scheduled','published','cancelled'],scheduled:['draft','published','cancelled'],published:[],cancelled:['draft']};
export async function transitionContent(db,{contentId,to,scheduledAt,actorUserId}){return withTransaction(db,async c=>{const current=(await c.query('SELECT * FROM marketing_content WHERE id=$1 FOR UPDATE',[contentId])).rows[0];if(!current)return null;if(!(allowed[current.status]||[]).includes(to))throw new Error(`Invalid content transition: ${current.status} -> ${to}`);if(to==='scheduled'&&!scheduledAt&&!current.scheduled_at)throw new Error('Schedule time required');const item=(await c.query(
 `UPDATE marketing_content SET status=$2,scheduled_at=CASE WHEN $2='scheduled' THEN COALESCE($3,scheduled_at) ELSE scheduled_at END,
 approved_by=CASE WHEN $2='approved' THEN $4 ELSE approved_by END,published_at=CASE WHEN $2='published' THEN now() ELSE published_at END,updated_at=now() WHERE id=$1 RETURNING *`,[contentId,to,scheduledAt||null,actorUserId])).rows[0];await audit(c,actorUserId,'marketing.content_transitioned','marketing_content',contentId,{from:current.status,to,scheduledAt:scheduledAt||null});return item})}
async function audit(c,u,a,t,id,d){await c.query(`INSERT INTO audit_log(actor_user_id,action,entity_type,entity_id,data)VALUES($1,$2,$3,$4,$5::jsonb)`,[u,a,t,id,JSON.stringify(d)])}
