"use client";

import {useEffect,useMemo,useState} from "react";
import {useRouter} from "next/navigation";

type Product={id:string;name:string;category:string;price:number;note:string;emoji:string};
type Cart=Record<string,number>;

const products:Product[]=[
  {id:"cooler-table",name:"برادة طاولة ذاتية التعبئة",category:"برادات",price:399,note:"مناسبة للمنزل والمكتب",emoji:"💧"},
  {id:"heater-instant",name:"سخان ماء فوري",category:"سخانات",price:249,note:"تسخين سريع واستخدام عملي",emoji:"♨️"},
  {id:"aqua-gold-7",name:"جهاز تحلية Aqua Gold 7 مراحل",category:"أجهزة التحلية",price:650,note:"جهاز تحلية منزلي 7 مراحل",emoji:"🚰"},
  {id:"jumbo-20",name:"فلتر جامبو 20 بوصة",category:"فلاتر",price:180,note:"فلترة أولية للمياه المنزلية",emoji:"🧊"},
  {id:"membrane-75",name:"ممبرين RO 75 GPD",category:"فلاتر",price:95,note:"غشاء تناضح عكسي للاستخدام المنزلي",emoji:"🔹"},
  {id:"pump-ro",name:"مضخة جهاز تحلية",category:"مضخات",price:145,note:"مضخة ضغط لأجهزة RO",emoji:"⚙️"}
];

export default function Store(){
  const router=useRouter();
  const [category,setCategory]=useState("الكل"),[cart,setCart]=useState<Cart>({}),[checkout,setCheckout]=useState(false),[address,setAddress]=useState(""),[done,setDone]=useState<string|null>(null);
  useEffect(()=>{if(!sessionStorage.getItem("subil_customer_session"))router.replace("/login")},[router]);
  const categories=["الكل",...Array.from(new Set(products.map(p=>p.category)))];
  const visible=category==="الكل"?products:products.filter(p=>p.category===category);
  const count=Object.values(cart).reduce((a,b)=>a+b,0);
  const total=useMemo(()=>products.reduce((sum,p)=>sum+p.price*(cart[p.id]||0),0),[cart]);
  function add(id:string){setCart(v=>({...v,[id]:(v[id]||0)+1}))}
  function sub(id:string){setCart(v=>{const n=Math.max(0,(v[id]||0)-1),next={...v};if(n)next[id]=n;else delete next[id];return next})}
  function confirm(){if(address.trim().length<5)return;const number=`S-${String(Date.now()).slice(-6)}`;localStorage.setItem("subil_demo_store_order",JSON.stringify({number,cart,total,address,createdAt:new Date().toISOString()}));setDone(number)}
  if(done)return <main style={s.page}><section style={s.card}><div style={s.success}>✓</div><h1 style={s.title}>تم استلام طلب الشراء</h1><p style={s.muted}>رقم الطلب: <b>{done}</b></p><p style={s.muted}>الإجمالي: <b>{total.toLocaleString("ar-SA")} ر.س</b></p><button style={s.primary} onClick={()=>router.replace("/")}>العودة للرئيسية</button></section></main>;
  if(checkout)return <main style={s.page}><section style={s.card}><div style={s.head}><button style={s.back} onClick={()=>setCheckout(false)}>‹</button><div><small style={s.kicker}>إتمام الطلب</small><h1 style={s.title}>التوصيل والدفع</h1></div></div><div style={s.summary}><span>عدد المنتجات</span><b>{count}</b><span>الإجمالي</span><b>{total.toLocaleString("ar-SA")} ر.س</b></div><label style={s.label}>عنوان التوصيل<textarea style={{...s.input,minHeight:90}} value={address} onChange={e=>setAddress(e.target.value)} placeholder="الرياض - الحي - الشارع - رقم المبنى"/></label><div style={s.pay}><b>طريقة الدفع</b><span>الدفع الإلكتروني سيُربط ببوابات المتجر في النسخة النهائية</span></div><button style={s.primary} disabled={address.trim().length<5} onClick={confirm}>تأكيد الطلب</button></section></main>;
  return <main style={s.page}><section style={s.card}><div style={s.head}><button style={s.back} onClick={()=>router.back()}>‹</button><div><small style={s.kicker}>متجر سبيل</small><h1 style={s.title}>تسوّق من داخل التطبيق</h1><p style={s.muted}>برادات، سخانات، أجهزة تحلية، فلاتر وإكسسوارات.</p></div></div><div style={s.categories}>{categories.map(c=><button key={c} style={{...s.chip,...(category===c?s.chipOn:{})}} onClick={()=>setCategory(c)}>{c}</button>)}</div><div style={s.grid}>{visible.map(p=><article key={p.id} style={s.product}><div style={s.pic}>{p.emoji}</div><small style={s.category}>{p.category}</small><b style={s.productName}>{p.name}</b><span style={s.note}>{p.note}</span><strong style={s.price}>{p.price.toLocaleString("ar-SA")} ر.س</strong><div style={s.qty}>{cart[p.id]?<><button style={s.qbtn} onClick={()=>sub(p.id)}>−</button><b>{cart[p.id]}</b></>:null}<button style={s.add} onClick={()=>add(p.id)}>{cart[p.id]?"+":"أضف للسلة"}</button></div></article>)}</div>{count>0&&<div style={s.cartbar}><div><small>{count} منتج</small><b>{total.toLocaleString("ar-SA")} ر.س</b></div><button style={s.primarySmall} onClick={()=>setCheckout(true)}>إتمام الشراء</button></div>}</section></main>;
}

const s:Record<string,React.CSSProperties>={page:{minHeight:"100vh",background:"#f4f7f6",padding:"16px",fontFamily:"inherit"},card:{maxWidth:620,margin:"0 auto",background:"#fff",borderRadius:24,padding:18,boxShadow:"0 14px 40px rgba(0,0,0,.06)"},head:{display:"flex",gap:12,alignItems:"flex-start",marginBottom:18},back:{width:42,height:42,borderRadius:14,border:"1px solid #e5e7eb",background:"#fff",fontSize:28},kicker:{color:"#20a957",fontWeight:800},title:{margin:"4px 0 5px",fontSize:25},muted:{margin:0,color:"#6b7280",lineHeight:1.6},categories:{display:"flex",gap:8,overflowX:"auto",paddingBottom:10,marginBottom:8},chip:{whiteSpace:"nowrap",border:"1px solid #dfe5e2",background:"#fff",borderRadius:999,padding:"9px 13px",fontWeight:700},chipOn:{background:"#eaf8f0",borderColor:"#20a957",color:"#168744"},grid:{display:"grid",gridTemplateColumns:"repeat(2,minmax(0,1fr))",gap:12},product:{border:"1px solid #edf0ee",borderRadius:18,padding:13,display:"grid",gap:6,alignContent:"start"},pic:{height:92,borderRadius:14,background:"#f3faf6",display:"grid",placeItems:"center",fontSize:42},category:{color:"#20a957",fontWeight:800},productName:{fontSize:15,lineHeight:1.5},note:{fontSize:12,color:"#6b7280",minHeight:36},price:{fontSize:17,color:"#111827"},qty:{display:"flex",gap:8,alignItems:"center",marginTop:4},add:{flex:1,border:0,borderRadius:12,padding:"10px 8px",background:"#20a957",color:"#fff",fontWeight:800},qbtn:{width:34,height:34,borderRadius:10,border:"1px solid #dfe5e2",background:"#fff",fontSize:20},cartbar:{position:"sticky",bottom:10,marginTop:16,background:"#0f3d2d",color:"#fff",borderRadius:18,padding:12,display:"flex",justifyContent:"space-between",alignItems:"center",gap:12,boxShadow:"0 12px 30px rgba(0,0,0,.18)"},primarySmall:{border:0,borderRadius:13,padding:"12px 16px",background:"#20a957",color:"#fff",fontWeight:900},primary:{width:"100%",border:0,borderRadius:15,padding:"15px 18px",background:"#20a957",color:"#fff",fontSize:17,fontWeight:800,marginTop:16},summary:{display:"grid",gridTemplateColumns:"1fr auto",gap:"10px 16px",background:"#f7faf8",borderRadius:16,padding:16,margin:"16px 0"},label:{display:"grid",gap:8,fontWeight:800},input:{width:"100%",boxSizing:"border-box",border:"1px solid #dfe5e2",borderRadius:14,padding:"13px 14px",fontFamily:"inherit",fontSize:16},pay:{display:"grid",gap:5,background:"#f7faf8",borderRadius:14,padding:14,marginTop:14,color:"#374151"},success:{width:64,height:64,borderRadius:22,display:"grid",placeItems:"center",background:"#eaf8f0",color:"#20a957",fontSize:34,fontWeight:900,margin:"4px auto 14px"}};
