"use client";
import {useState} from "react";import{useRouter}from"next/navigation";
type Msg={from:"ai"|"user";text:string};
const answers=[[/صيان|فلتر|تغيير/, "أقدر أساعدك في الصيانة. افتح «أجهزتي» واختر الجهاز لمراجعة موعد الصيانة أو طلب خدمة."],[/طلب|شحن|وصل|موعد/, "أقدر أتابع طلبك من «طلباتي». إذا كان لديك طلب نشط ستظهر حالته وموعد الخدمة في الرئيسية."],[/ضمان/, "بيانات الضمان تظهر داخل «أجهزتي» لكل جهاز مسجل في حسابك."],[/دفع|تابي|تمارا|أموال|tap/i,"إذا واجهت مشكلة دفع، لا تكرر العملية عدة مرات. جرّب وسيلة أخرى مؤقتًا، ويمكنني تصعيد الحالة إذا استمرت."],[/منتج|فلتر|تحلية|برادة|سخان/,"أقدر أساعدك باختيار المنتج المناسب. اذكر احتياجك وعدد الأشخاص أو نوع الجهاز المطلوب."]];
function reply(q:string){for(const[a,b]of answers)if(a.test(q))return b;return"أفهم طلبك. أعطني تفاصيل أكثر قليلًا وسأحاول حله هنا قبل تحويله لموظف خدمة العملاء."}
export default function Support(){const router=useRouter(),[messages,setMessages]=useState<Msg[]>([{from:"ai",text:"مرحبًا بك في مساعد سبيل. كيف أقدر أخدمك؟ سأحاول حل طلبك مباشرة، وإذا احتجنا تدخلًا بشريًا سأجهز لك التصعيد."}]),[q,setQ]=useState(""),[unresolved,setUnresolved]=useState(0);
function send(){const x=q.trim();if(!x)return;const a=reply(x);setMessages(v=>[...v,{from:"user",text:x},{from:"ai",text:a}]);setUnresolved(v=>a.startsWith("أفهم")?v+1:0);setQ("")}
return <main style={s.page} dir="rtl"><section style={s.card}><header style={s.head}><button style={s.back} onClick={()=>router.back()}>رجوع</button><div><small style={s.kicker}>خدمة عملاء سبيل</small><h1 style={s.title}>المساعد الذكي</h1><p style={s.note}>حل سريع أولًا، والتصعيد لموظف عند الحاجة فقط.</p></div></header><div style={s.chat}>{messages.map((m,i)=><div key={i} style={{...s.msg,...(m.from==="user"?s.user:s.ai)}}>{m.text}</div>)}</div>{unresolved>=2&&<section style={s.escalate}><b>يبدو أن الحالة تحتاج متابعة بشرية</b><span>سأجهز لك التواصل مع خدمة العملاء مع تفاصيل المشكلة.</span><a style={s.human} href="https://subil.store/contact" target="_blank" rel="noreferrer">التواصل مع موظف خدمة العملاء</a></section>}<div style={s.quick}><button onClick={()=>setQ("أين وصل طلبي؟")}>متابعة طلب</button><button onClick={()=>setQ("أحتاج صيانة فلتر")}>صيانة</button><button onClick={()=>setQ("عندي مشكلة في الدفع")}>مشكلة دفع</button></div><div style={s.form}><input style={s.input} value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>{if(e.key==="Enter")send()}} placeholder="اكتب سؤالك هنا…"/><button style={s.send} onClick={send}>إرسال</button></div><small style={s.disclaimer}>المساعد لا يطلب بيانات بطاقتك أو رمز التحقق.</small></section></main>}
const s:Record<string,React.CSSProperties>={page:{minHeight:"100vh",background:"#f4f7f6",padding:12},card:{maxWidth:720,margin:"0 auto",background:"#fff",borderRadius:22,padding:16,minHeight:"calc(100vh - 24px)",boxSizing:"border-box",display:"flex",flexDirection:"column"},head:{display:"flex",gap:12,borderBottom:"1px solid #edf0ee",paddingBottom:14},back:{border:"1px solid #dfe5e2",background:"#fff",borderRadius:10,padding:"8px 11px",height:38,fontWeight:800},kicker:{color:"#20a957",fontWeight:800},title:{margin:"3px 0",fontSize:23},note:{margin:0,color:"#6b7280",fontSize:13},chat:{display:"flex",flexDirection:"column",gap:9,padding:"18px 0",flex:1,overflowY:"auto"},msg:{maxWidth:"82%",padding:"11px 13px",borderRadius:15,lineHeight:1.7,fontSize:14},ai:{background:"#eef8f2",alignSelf:"flex-start"},user:{background:"#0f3d2d",color:"#fff",alignSelf:"flex-end"},quick:{display:"flex",gap:7,overflowX:"auto",paddingBottom:9},form:{display:"flex",gap:8},input:{flex:1,border:"1px solid #dfe5e2",borderRadius:13,padding:"12px",fontFamily:"inherit",fontSize:15},send:{border:0,borderRadius:13,background:"#20a957",color:"#fff",padding:"0 18px",fontWeight:800},escalate:{display:"grid",gap:7,background:"#fff8e8",padding:12,borderRadius:14,marginBottom:10},human:{background:"#111827",color:"#fff",padding:11,borderRadius:11,textDecoration:"none",textAlign:"center",fontWeight:800},disclaimer:{color:"#6b7280",marginTop:8,textAlign:"center"}};
