"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import PreviewAuthGuard from "../preview-auth-guard";

const apiBase=process.env.NEXT_PUBLIC_SUBIL_API_URL?.replace(/\/$/,"")||"";
type Filter="all"|"pending_approval"|"approved"|"rejected"|"paid";
type Stats={total:number;pending_approval:number;approved:number;rejected:number;paid:number;pending_amount:number|string;approved_amount:number|string;paid_this_month:number|string};
type Settlement={id:string;job_id:string;technician_id:string;technician_mobile?:string;customer_id:string;customer_name:string;external_order_id?:string;sale_ex_vat:number|string;product_cost:number|string;other_costs:number|string;margin:number|string;policy_version:string;commission_rate?:number|string;fixed_amount?:number|string;payout_amount:number|string;status:Filter;approved_at?:string;created_at:string};
type Action="reject"|"paid";
const seed:Settlement[]=[
  {id:"SET-109",job_id:"JOB-1045",technician_id:"TECH-04",technician_mobile:"+966503456789",customer_id:"CUS-1045",customer_name:"سعد العتيبي",external_order_id:"1045",sale_ex_vat:650,product_cost:330,other_costs:40,margin:280,policy_version:"initial-1",commission_rate:.3,payout_amount:84,status:"pending_approval",created_at:"2026-09-15T08:20:00Z"},
  {id:"SET-108",job_id:"JOB-1044",technician_id:"TECH-12",technician_mobile:"+966501234567",customer_id:"CUS-1044",customer_name:"شركة روافد",external_order_id:"1044",sale_ex_vat:1200,product_cost:620,other_costs:80,margin:500,policy_version:"initial-1",commission_rate:.3,payout_amount:150,status:"approved",approved_at:"2026-09-15T07:00:00Z",created_at:"2026-09-14T16:00:00Z"},
  {id:"SET-107",job_id:"JOB-1043",technician_id:"TECH-08",technician_mobile:"+966502345678",customer_id:"CUS-1043",customer_name:"نورة الدوسري",external_order_id:"1043",sale_ex_vat:500,product_cost:260,other_costs:20,margin:220,policy_version:"initial-1",commission_rate:.3,payout_amount:66,status:"paid",approved_at:"2026-09-13T10:00:00Z",created_at:"2026-09-13T09:00:00Z"}
];
const initialStats:Stats={total:3,pending_approval:1,approved:1,rejected:0,paid:1,pending_amount:84,approved_amount:150,paid_this_month:66};
const money=(value:number|string)=>Number(value||0).toLocaleString("ar-SA",{minimumFractionDigits:2,maximumFractionDigits:2});
const date=new Intl.DateTimeFormat("ar-SA",{dateStyle:"medium",timeStyle:"short"});
function label(status:string){return({pending_approval:"بانتظار الاعتماد",approved:"معتمدة",rejected:"مرفوضة",paid:"مدفوعة"} as Record<string,string>)[status]||status;}

export default function FinancePage(){
 const [items,setItems]=useState<Settlement[]>(apiBase?[]:seed),[stats,setStats]=useState<Stats>(initialStats),[filter,setFilter]=useState<Filter>("pending_approval"),[query,setQuery]=useState(""),[search,setSearch]=useState(""),[page,setPage]=useState(0),[total,setTotal]=useState(apiBase?0:seed.length),[loading,setLoading]=useState(Boolean(apiBase)),[error,setError]=useState(""),[reloadKey,setReloadKey]=useState(0),[savingId,setSavingId]=useState("");
 const [actionTarget,setActionTarget]=useState<Settlement|null>(null),[action,setAction]=useState<Action>("reject"),[actionError,setActionError]=useState(""),[canApprove,setCanApprove]=useState(!apiBase);
 const shown=useMemo(()=>{if(apiBase)return items;const q=query.trim().toLowerCase();return items.filter(item=>(filter==="all"||item.status===filter)&&(!q||[item.id,item.job_id,item.technician_id,item.technician_mobile,item.customer_name,item.external_order_id].some(value=>value?.toLowerCase().includes(q))));},[items,filter,query]);
 useEffect(()=>{setCanApprove(!apiBase||["finance","admin","super_admin"].includes(sessionStorage.getItem("subil_role")||""));},[]);
 useEffect(()=>{if(!apiBase)return;const timer=window.setTimeout(()=>{setPage(0);setSearch(query.trim());},300);return()=>window.clearTimeout(timer);},[query]);
 useEffect(()=>{if(!apiBase)return;const controller=new AbortController(),token=sessionStorage.getItem("subil_session"),params=new URLSearchParams({status:filter,limit:"20",offset:String(page*20)});if(search)params.set("q",search);setLoading(true);fetch(`${apiBase}/api/v1/settlements?${params}`,{headers:{Authorization:`Bearer ${token}`},signal:controller.signal}).then(async response=>{const payload=await response.json();if(!response.ok)throw new Error(response.status===401?"انتهت جلسة الدخول.":"تعذر تحميل المستحقات.");return payload;}).then(payload=>{setItems(payload.settlements||[]);setTotal(Number(payload.pagination?.total||0));setError("");}).catch(reason=>{if(reason instanceof DOMException&&reason.name==="AbortError")return;setError(reason instanceof Error?reason.message:"تعذر تحميل المستحقات.");}).finally(()=>setLoading(false));return()=>controller.abort();},[filter,page,search,reloadKey]);
 useEffect(()=>{if(!apiBase)return;const controller=new AbortController(),token=sessionStorage.getItem("subil_session");fetch(`${apiBase}/api/v1/settlements/stats`,{headers:{Authorization:`Bearer ${token}`},signal:controller.signal}).then(async response=>{if(!response.ok)throw new Error("تعذر تحميل مؤشرات المالية.");return response.json();}).then(payload=>setStats(payload.stats)).catch(reason=>{if(reason instanceof DOMException&&reason.name==="AbortError")return;setError(reason instanceof Error?reason.message:"تعذر تحميل مؤشرات المالية.");});return()=>controller.abort();},[reloadKey]);
 async function approve(item:Settlement){setSavingId(item.id);setError("");try{if(apiBase){const token=sessionStorage.getItem("subil_session"),response=await fetch(`${apiBase}/api/v1/settlements/${encodeURIComponent(item.id)}/approve`,{method:"POST",headers:{Authorization:`Bearer ${token}`}}),payload=await response.json();if(!response.ok)throw new Error("تعذر اعتماد المستحق.");setReloadKey(value=>value+1);}else{setItems(list=>list.map(entry=>entry.id===item.id?{...entry,status:"approved",approved_at:new Date().toISOString()}:entry));setStats(value=>({...value,pending_approval:value.pending_approval-1,approved:value.approved+1,pending_amount:Number(value.pending_amount)-Number(item.payout_amount),approved_amount:Number(value.approved_amount)+Number(item.payout_amount)}));}}catch(reason){setError(reason instanceof Error?reason.message:"تعذر اعتماد المستحق.");}finally{setSavingId("");}}
 async function submitAction(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!actionTarget)return;const value=String(new FormData(event.currentTarget).get("value")||"").trim();if(value.length<3){setActionError(action==="reject"?"اكتب سبب الرفض.":"أدخل مرجع عملية الدفع.");return;}setSavingId(actionTarget.id);setActionError("");try{const next=action==="reject"?"rejected":"paid";if(apiBase){const token=sessionStorage.getItem("subil_session"),response=await fetch(`${apiBase}/api/v1/settlements/${encodeURIComponent(actionTarget.id)}/${action}`,{method:"POST",headers:{"content-type":"application/json",Authorization:`Bearer ${token}`},body:JSON.stringify(action==="reject"?{reason:value}:{paymentReference:value})}),payload=await response.json();if(!response.ok)throw new Error(action==="reject"?"تعذر رفض المستحق.":"تعذر تسجيل الدفع.");setReloadKey(count=>count+1);}else setItems(list=>list.map(entry=>entry.id===actionTarget.id?{...entry,status:next}:entry));setActionTarget(null);}catch(reason){setActionError(reason instanceof Error?reason.message:"تعذر حفظ الإجراء.");}finally{setSavingId("");}}
 const cards:Array<{title:string;value:number|string;filter:Filter;money?:boolean}>=[{title:"بانتظار الاعتماد",value:stats.pending_approval,filter:"pending_approval"},{title:"قيمة معلقة",value:stats.pending_amount,filter:"pending_approval",money:true},{title:"معتمدة للدفع",value:stats.approved_amount,filter:"approved",money:true},{title:"مدفوع هذا الشهر",value:stats.paid_this_month,filter:"paid",money:true},{title:"مرفوضة",value:stats.rejected,filter:"rejected"}];
 return <PreviewAuthGuard><main className="customers-page finance-page"><header className="customers-top"><a className="customers-brand" href="/"><span>S</span><strong>سبيل</strong><small>نظام التشغيل</small></a><nav className="section-nav"><a href="/">لوحة التحكم</a><a href="/jobs">المهام</a><a href="/customers">العملاء</a><a href="/technicians">الفنيون</a><a href="/maintenance">الصيانة</a><a className="active" href="/finance">المالية</a></nav><div className="profile-avatar">م</div></header><div className="customers-wrap">
  <div className="demo-notice"><span>نسخة المعاينة</span> الاعتماد والدفع محكومان بالصلاحيات وسجل التدقيق.</div><div className="page-head"><div><p>المالية والتسويات</p><h1>مستحقات الفنيين</h1><span>مراجعة هامش الطلب والعمولة والاعتماد والدفع</span></div></div>
  <section className="finance-stats">{cards.map((card,index)=><button key={card.title} className={`${filter===card.filter?"active ":""}${index===0?"pending":""}`} onClick={()=>{setFilter(card.filter);setPage(0);}}><span>{card.title}</span><strong>{card.money?`${money(card.value)} ر.س`:Number(card.value||0).toLocaleString("ar-SA")}</strong></button>)}</section>{error&&<div className="api-error" role="alert">{error}</div>}
  <section className="panel finance-worklist"><div className="customers-toolbar"><div><h2>سجل المستحقات</h2><p>{loading?"جارٍ التحميل...":`${(apiBase?total:shown.length).toLocaleString("ar-SA")} مستحق`}</p></div><div className="jobs-toolbar-actions"><select value={filter} onChange={event=>{setFilter(event.target.value as Filter);setPage(0);}}><option value="all">الكل</option><option value="pending_approval">بانتظار الاعتماد</option><option value="approved">معتمدة</option><option value="paid">مدفوعة</option><option value="rejected">مرفوضة</option></select><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="ابحث بالعميل أو الفني أو الطلب"/></div></div>
   {shown.length?<><div className="table-wrap"><table><thead><tr><th>الطلب والعميل</th><th>الفني</th><th>الإيراد والتكلفة</th><th>الهامش</th><th>السياسة</th><th>المستحق</th><th>الحالة</th><th>الإجراء</th></tr></thead><tbody>{shown.map(item=><tr key={item.id}><td><strong>#{item.external_order_id||item.job_id} · {item.customer_name}</strong><small>{date.format(new Date(item.created_at))}</small></td><td><strong>{item.technician_id}</strong><small dir="ltr">{item.technician_mobile||"—"}</small></td><td><strong>{money(item.sale_ex_vat)} ر.س</strong><small>تكلفة {money(Number(item.product_cost)+Number(item.other_costs))}</small></td><td><strong>{money(item.margin)} ر.س</strong><small>{Number(item.sale_ex_vat)?Math.round(Number(item.margin)/Number(item.sale_ex_vat)*100).toLocaleString("ar-SA"):0}%</small></td><td><strong>{item.policy_version}</strong><small>{item.commission_rate?`${Math.round(Number(item.commission_rate)*100).toLocaleString("ar-SA")}% من الهامش`:`ثابت ${money(item.fixed_amount||0)}`}</small></td><td><strong className="settlement-amount">{money(item.payout_amount)} ر.س</strong></td><td><span className={`settlement-state ${item.status}`}>{label(item.status)}</span></td><td><div className="settlement-actions">{canApprove&&item.status==="pending_approval"&&<><button disabled={savingId===item.id} onClick={()=>approve(item)}>اعتماد</button><button className="reject" disabled={savingId===item.id} onClick={()=>{setAction("reject");setActionTarget(item);setActionError("");}}>رفض</button></>}{canApprove&&item.status==="approved"&&<button disabled={savingId===item.id} onClick={()=>{setAction("paid");setActionTarget(item);setActionError("");}}>تسجيل الدفع</button>}{(!canApprove||!["pending_approval","approved"].includes(item.status))&&"—"}</div></td></tr>)}</tbody></table></div>{apiBase&&total>20&&<nav className="customers-pagination"><button className="secondary-button" disabled={loading||page===0} onClick={()=>setPage(value=>value-1)}>السابق</button><span>صفحة {(page+1).toLocaleString("ar-SA")} من {Math.ceil(total/20).toLocaleString("ar-SA")}</span><button className="secondary-button" disabled={loading||(page+1)*20>=total} onClick={()=>setPage(value=>value+1)}>التالي</button></nav>}</>:<div className="empty-state">لا توجد مستحقات مطابقة.</div>}
  </section>{actionTarget&&<div className="modal-backdrop"><section className="customer-modal" role="dialog" aria-modal="true"><div className="modal-head"><div><h2>{action==="reject"?"رفض المستحق":"تسجيل دفع المستحق"}</h2><p>{actionTarget.id} · {money(actionTarget.payout_amount)} ر.س</p></div><button disabled={Boolean(savingId)} onClick={()=>setActionTarget(null)}>×</button></div><form onSubmit={submitAction}><label>{action==="reject"?"سبب الرفض":"مرجع عملية الدفع"}<input name="value" placeholder={action==="reject"?"مثال: بيانات التكلفة غير مكتملة":"رقم التحويل أو مرجع البنك"}/></label>{actionError&&<p className="form-error">{actionError}</p>}<div className="modal-actions"><button className="secondary-button" type="button" onClick={()=>setActionTarget(null)}>إلغاء</button><button className={`primary-button ${action==="reject"?"danger-button":""}`} disabled={Boolean(savingId)}>{savingId?"جارٍ الحفظ...":"تأكيد"}</button></div></form></section></div>}
 </div></main></PreviewAuthGuard>;
}
