"use client";import Header from"../components/Header";

import { FormEvent, useEffect, useMemo, useState } from "react";
import PreviewAuthGuard from "../preview-auth-guard";

const apiBase=process.env.NEXT_PUBLIC_SUBIL_API_URL?.replace(/\/$/,"")||"";
const roleName:Record<string,string>={dispatcher:"التوزيع",support:"خدمة العملاء",finance:"المالية",branch_manager:"مدير فرع",admin:"مدير النظام",super_admin:"مدير أعلى"};
type User={id:string;mobile:string;role:string;is_active:boolean;created_at?:string};

export default function UsersPage(){
 const [users,setUsers]=useState<User[]>([]),[roles,setRoles]=useState<string[]>([]),[query,setQuery]=useState(""),[status,setStatus]=useState("all"),[loading,setLoading]=useState(true),[error,setError]=useState(""),[saving,setSaving]=useState(""),[allowed,setAllowed]=useState(false),[reload,setReload]=useState(0);
 const token=()=>sessionStorage.getItem("subil_session")||"";
 useEffect(()=>{const role=sessionStorage.getItem("subil_role")||"";setAllowed(["admin","super_admin"].includes(role));},[]);
 useEffect(()=>{if(!apiBase||!allowed){setLoading(false);return;}const controller=new AbortController(),params=new URLSearchParams({limit:"100",status});if(query.trim())params.set("q",query.trim());setLoading(true);Promise.all([
  fetch(`${apiBase}/api/v1/users?${params}`,{headers:{Authorization:`Bearer ${token()}`},signal:controller.signal}),
  fetch(`${apiBase}/api/v1/users/roles`,{headers:{Authorization:`Bearer ${token()}`},signal:controller.signal})
 ]).then(async([a,b])=>{const usersPayload=await a.json(),rolesPayload=await b.json();if(!a.ok||!b.ok)throw new Error("تعذر تحميل المستخدمين والصلاحيات.");setUsers(usersPayload.users||[]);setRoles(rolesPayload.roles||[]);setError("");}).catch(reason=>{if(reason instanceof DOMException&&reason.name==="AbortError")return;setError(reason instanceof Error?reason.message:"تعذر تحميل المستخدمين.");}).finally(()=>setLoading(false));return()=>controller.abort();},[allowed,status,reload]);
 const shown=useMemo(()=>{if(apiBase)return users;const q=query.trim();return users.filter(user=>(!q||user.mobile.includes(q))&&(status==="all"||(status==="active")===user.is_active));},[users,query,status]);
 async function createUser(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget),mobile=String(form.get("mobile")||""),role=String(form.get("role")||"");setSaving("new");setError("");try{if(!apiBase)throw new Error("اربط API لإنشاء المستخدمين.");const response=await fetch(`${apiBase}/api/v1/users`,{method:"POST",headers:{"content-type":"application/json",Authorization:`Bearer ${token()}`},body:JSON.stringify({mobile,role})}),payload=await response.json();if(!response.ok)throw new Error(payload.error==="mobile_already_exists"?"رقم الجوال مستخدم مسبقًا.":"تعذر إنشاء المستخدم.");event.currentTarget.reset();setReload(v=>v+1);}catch(reason){setError(reason instanceof Error?reason.message:"تعذر إنشاء المستخدم.");}finally{setSaving("");}}
 async function updateUser(user:User,changes:{role?:string;isActive?:boolean}){setSaving(user.id);setError("");try{const response=await fetch(`${apiBase}/api/v1/users/${encodeURIComponent(user.id)}`,{method:"PATCH",headers:{"content-type":"application/json",Authorization:`Bearer ${token()}`},body:JSON.stringify(changes)}),payload=await response.json();if(!response.ok)throw new Error(payload.error==="cannot_modify_own_access"?"لا يمكن تعديل صلاحيات حسابك الحالي.":"تعذر تحديث المستخدم.");setUsers(list=>list.map(x=>x.id===user.id?payload.user:x));}catch(reason){setError(reason instanceof Error?reason.message:"تعذر تحديث المستخدم.");}finally{setSaving("");}}
 return <PreviewAuthGuard><main className="customers-page"><Header active="/users"/><div className="customers-wrap">
  <div className="page-head"><div><p>الإدارة والأمان</p><h1>المستخدمون والصلاحيات</h1><span>إدارة حسابات الموظفين والأدوار وحالة الوصول للنظام</span></div></div>
  {!allowed?<div className="api-error">هذه الصفحة متاحة لمدير النظام فقط.</div>:<>
   {error&&<div className="api-error" role="alert">{error}</div>}
   <section className="panel"><div className="customers-toolbar"><div><h2>إضافة مستخدم</h2><p>يتم تسجيل الدخول لاحقًا برقم الجوال وOTP.</p></div></div><form onSubmit={createUser} className="users-create-form" style={{display:"grid",gridTemplateColumns:"2fr 1fr auto",gap:12,padding:"0 20px 20px"}}><input name="mobile" required placeholder="05xxxxxxxx" dir="ltr"/><select name="role" required defaultValue=""><option value="" disabled>اختر الدور</option>{roles.map(role=><option key={role} value={role}>{roleName[role]||role}</option>)}</select><button className="primary-button" disabled={saving==="new"}>{saving==="new"?"جارٍ الحفظ...":"إضافة مستخدم"}</button></form></section>
   <section className="panel"><div className="customers-toolbar"><div><h2>المستخدمون</h2><p>{loading?"جارٍ التحميل...":`${shown.length.toLocaleString("ar-SA")} مستخدم`}</p></div><div className="jobs-toolbar-actions"><select value={status} onChange={e=>setStatus(e.target.value)}><option value="all">الكل</option><option value="active">نشط</option><option value="inactive">معطل</option></select><input value={query} onChange={e=>setQuery(e.target.value)} onKeyDown={e=>{if(e.key==="Enter")setReload(v=>v+1)}} placeholder="بحث برقم الجوال" dir="rtl"/></div></div>
   <div className="table-wrap"><table><thead><tr><th>رقم الجوال</th><th>الدور</th><th>الحالة</th><th>الإجراء</th></tr></thead><tbody>{shown.map(user=><tr key={user.id}><td dir="ltr"><strong>{user.mobile}</strong></td><td><select value={user.role} disabled={saving===user.id} onChange={e=>updateUser(user,{role:e.target.value})}>{roles.includes(user.role)?roles.map(role=><option key={role} value={role}>{roleName[role]||role}</option>):<option value={user.role}>{roleName[user.role]||user.role}</option>}</select></td><td><span className={`technician-state ${user.is_active?"active":"inactive"}`}>{user.is_active?"نشط":"معطل"}</span></td><td><button className="text-action" disabled={saving===user.id} onClick={()=>updateUser(user,{isActive:!user.is_active})}>{user.is_active?"تعطيل":"تفعيل"}</button></td></tr>)}</tbody></table></div>{!loading&&!shown.length&&<div className="empty-state">لا يوجد مستخدمون مطابقون.</div>}</section>
  </>}
 </div></main></PreviewAuthGuard>;
}
