"use client";import Header from"../components/Header";

import { FormEvent, useEffect, useMemo, useState } from "react";
import PreviewAuthGuard from "../preview-auth-guard";

const apiBase=process.env.NEXT_PUBLIC_SUBIL_API_URL?.replace(/\/$/,"")||"";
type Filter="all"|"low"|"out";type Action="receive"|"technician-issue"|"transfer";
type Balance={warehouse_id:string;warehouse_name:string;quantity:number|string};
type Item={id:string;sku:string;name:string;unit:string;reorder_level:number|string;unit_cost:number|string;total_quantity:number|string;technician_quantity:number|string;stock_status:"ok"|"low"|"out";balances:Balance[]};
type Stats={total_skus:number;total_units:number|string;stock_value:number|string;out_of_stock:number;low_stock:number};
type Movement={id:string;movement_type:string;sku:string;item_name:string;quantity:number|string;from_warehouse_name?:string;to_warehouse_name?:string;technician_id?:string;reference?:string;created_at:string};
const seed:Item[]=[
 {id:"ITEM-RO7",sku:"RO-7-STAGE",name:"جهاز تحلية 7 مراحل",unit:"جهاز",reorder_level:5,unit_cost:330,total_quantity:18,technician_quantity:4,stock_status:"ok",balances:[{warehouse_id:"main-riyadh",warehouse_name:"المستودع الرئيسي",quantity:18}]},
 {id:"ITEM-M75",sku:"MEM-75GPD",name:"شمعة ممبرين 75 GPD",unit:"حبة",reorder_level:10,unit_cost:42,total_quantity:7,technician_quantity:6,stock_status:"low",balances:[{warehouse_id:"main-riyadh",warehouse_name:"المستودع الرئيسي",quantity:7}]},
 {id:"ITEM-J20",sku:"JUMBO-20",name:"فلتر جامبو 20 بوصة",unit:"حبة",reorder_level:4,unit_cost:105,total_quantity:0,technician_quantity:1,stock_status:"out",balances:[]}
];
const seedMovements:Movement[]=[{id:"MOV-1",movement_type:"receipt",sku:"RO-7-STAGE",item_name:"جهاز تحلية 7 مراحل",quantity:10,to_warehouse_name:"المستودع الرئيسي",reference:"PO-104",created_at:"2026-09-16T07:30:00Z"},{id:"MOV-2",movement_type:"technician_issue",sku:"MEM-75GPD",item_name:"شمعة ممبرين",quantity:3,from_warehouse_name:"المستودع الرئيسي",technician_id:"TECH-12",reference:"JOB-1048",created_at:"2026-09-16T08:00:00Z"}];
const initialStats:Stats={total_skus:3,total_units:25,stock_value:6234,out_of_stock:1,low_stock:1};
const num=(value:number|string)=>Number(value||0).toLocaleString("ar-SA",{maximumFractionDigits:2});const money=(value:number|string)=>Number(value||0).toLocaleString("ar-SA",{minimumFractionDigits:2,maximumFractionDigits:2});const date=new Intl.DateTimeFormat("ar-SA",{dateStyle:"medium",timeStyle:"short"});
function movementLabel(value:string){return({receipt:"استلام",issue:"صرف",transfer:"تحويل",technician_issue:"عهدة فني",technician_return:"إرجاع فني",adjustment:"تسوية"} as Record<string,string>)[value]||value;}

export default function InventoryPage(){
 const [items,setItems]=useState<Item[]>(apiBase?[]:seed),[stats,setStats]=useState<Stats>(initialStats),[movements,setMovements]=useState<Movement[]>(apiBase?[]:seedMovements),[filter,setFilter]=useState<Filter>("all"),[query,setQuery]=useState(""),[search,setSearch]=useState(""),[page,setPage]=useState(0),[total,setTotal]=useState(apiBase?0:seed.length),[loading,setLoading]=useState(Boolean(apiBase)),[error,setError]=useState(""),[reloadKey,setReloadKey]=useState(0),[canManage,setCanManage]=useState(!apiBase);
 const [itemModal,setItemModal]=useState(false),[actionTarget,setActionTarget]=useState<Item|null>(null),[action,setAction]=useState<Action>("receive"),[saving,setSaving]=useState(false),[formError,setFormError]=useState("");
 const shown=useMemo(()=>{if(apiBase)return items;const q=query.trim().toLowerCase();return items.filter(item=>(filter==="all"||item.stock_status===filter)&&(!q||item.sku.toLowerCase().includes(q)||item.name.toLowerCase().includes(q)));},[items,filter,query]);
 useEffect(()=>{setCanManage(!apiBase||["branch_manager","admin","super_admin"].includes(sessionStorage.getItem("subil_role")||""));},[]);useEffect(()=>{if(!apiBase)return;const timer=window.setTimeout(()=>{setPage(0);setSearch(query.trim());},300);return()=>window.clearTimeout(timer);},[query]);
 useEffect(()=>{if(!apiBase)return;const controller=new AbortController(),token=sessionStorage.getItem("subil_session"),params=new URLSearchParams({status:filter,limit:"20",offset:String(page*20)});if(search)params.set("q",search);setLoading(true);fetch(`${apiBase}/api/v1/inventory?${params}`,{headers:{Authorization:`Bearer ${token}`},signal:controller.signal}).then(async response=>{const payload=await response.json();if(!response.ok)throw new Error("تعذر تحميل المخزون.");return payload;}).then(payload=>{setItems(payload.items||[]);setTotal(Number(payload.pagination?.total||0));setError("");}).catch(reason=>{if(reason instanceof DOMException&&reason.name==="AbortError")return;setError(reason instanceof Error?reason.message:"تعذر تحميل المخزون.");}).finally(()=>setLoading(false));return()=>controller.abort();},[filter,page,search,reloadKey]);
 useEffect(()=>{if(!apiBase)return;const controller=new AbortController(),token=sessionStorage.getItem("subil_session");Promise.all([fetch(`${apiBase}/api/v1/inventory/stats`,{headers:{Authorization:`Bearer ${token}`},signal:controller.signal}),fetch(`${apiBase}/api/v1/inventory/movements?limit=8`,{headers:{Authorization:`Bearer ${token}`},signal:controller.signal})]).then(async responses=>{if(responses.some(response=>!response.ok))throw new Error("تعذر تحميل مؤشرات المخزون.");return Promise.all(responses.map(response=>response.json()));}).then(([statsPayload,movementPayload])=>{setStats(statsPayload.stats);setMovements(movementPayload.movements||[]);}).catch(reason=>{if(reason instanceof DOMException&&reason.name==="AbortError")return;setError(reason instanceof Error?reason.message:"تعذر تحميل المؤشرات.");});return()=>controller.abort();},[reloadKey]);
 async function createItem(event:FormEvent<HTMLFormElement>){event.preventDefault();const data=new FormData(event.currentTarget),payload={sku:String(data.get("sku")||"").trim(),name:String(data.get("name")||"").trim(),unit:String(data.get("unit")||"piece").trim(),reorderLevel:Number(data.get("reorderLevel")||0),unitCost:Number(data.get("unitCost")||0)};if(payload.sku.length<2||payload.name.length<2||payload.reorderLevel<0||payload.unitCost<0){setFormError("أكمل بيانات الصنف بصورة صحيحة.");return;}setSaving(true);try{if(apiBase){const token=sessionStorage.getItem("subil_session"),response=await fetch(`${apiBase}/api/v1/inventory/items`,{method:"POST",headers:{"content-type":"application/json",Authorization:`Bearer ${token}`},body:JSON.stringify(payload)}),result=await response.json();if(!response.ok)throw new Error(result.error==="inventory_sku_exists"?"رمز الصنف مستخدم مسبقًا.":"تعذر إضافة الصنف.");setReloadKey(value=>value+1);}else{const item:Item={id:`ITEM-${Date.now()}`,sku:payload.sku.toUpperCase(),name:payload.name,unit:payload.unit,reorder_level:payload.reorderLevel,unit_cost:payload.unitCost,total_quantity:0,technician_quantity:0,stock_status:"out",balances:[]};setItems(list=>[item,...list]);setStats(value=>({...value,total_skus:value.total_skus+1,out_of_stock:value.out_of_stock+1}));}setItemModal(false);setFormError("");}catch(reason){setFormError(reason instanceof Error?reason.message:"تعذر إضافة الصنف.");}finally{setSaving(false);}}
 async function saveMovement(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!actionTarget)return;const data=new FormData(event.currentTarget),quantity=Number(data.get("quantity")),warehouseId=String(data.get("warehouseId")||"main-riyadh"),reference=String(data.get("reference")||""),common={itemId:actionTarget.id,quantity,reference,notes:String(data.get("notes")||"")};if(!Number.isFinite(quantity)||quantity<=0){setFormError("أدخل كمية صحيحة.");return;}const payload=action==="receive"?{...common,warehouseId,unitCost:Number(data.get("unitCost")||actionTarget.unit_cost)}:action==="technician-issue"?{...common,warehouseId,technicianId:String(data.get("technicianId")||"")}:{...common,fromWarehouseId:warehouseId,toWarehouseId:String(data.get("toWarehouseId")||"")};setSaving(true);try{if(apiBase){const token=sessionStorage.getItem("subil_session"),response=await fetch(`${apiBase}/api/v1/inventory/${action}`,{method:"POST",headers:{"content-type":"application/json",Authorization:`Bearer ${token}`},body:JSON.stringify(payload)}),result=await response.json();if(!response.ok)throw new Error(result.error==="inventory_movement_conflict"?"الرصيد غير كافٍ أو التحويل غير صالح.":"تعذر تسجيل الحركة.");setReloadKey(value=>value+1);}else{setItems(list=>list.map(item=>item.id===actionTarget.id?{...item,total_quantity:Number(item.total_quantity)+(action==="receive"?quantity:action==="technician-issue"?-quantity:0),technician_quantity:Number(item.technician_quantity)+(action==="technician-issue"?quantity:0),stock_status:"ok"}:item));}setActionTarget(null);setFormError("");}catch(reason){setFormError(reason instanceof Error?reason.message:"تعذر تسجيل الحركة.");}finally{setSaving(false);}}
 const cards=[{title:"الأصناف",value:num(stats.total_skus),filter:"all" as Filter},{title:"إجمالي الوحدات",value:num(stats.total_units),filter:"all" as Filter},{title:"قيمة المخزون",value:`${money(stats.stock_value)} ر.س`,filter:"all" as Filter},{title:"مخزون منخفض",value:num(stats.low_stock),filter:"low" as Filter},{title:"نافد",value:num(stats.out_of_stock),filter:"out" as Filter}];
 return <PreviewAuthGuard><main className="customers-page inventory-page"><Header active="/inventory"/><div className="customers-wrap">
  <div className="demo-notice"><span>نسخة المعاينة</span> حركات المخزون ذرّية وتمنع الرصيد السالب.</div><div className="page-head"><div><p>المخزون والمستودعات</p><h1>مركز المخزون</h1><span>الأرصدة والتنبيهات وعهد الفنيين وحركات الاستلام والصرف</span></div>{canManage&&<button className="primary-button" onClick={()=>{setItemModal(true);setFormError("");}}><span>+</span>إضافة صنف</button>}</div>
  <section className="inventory-stats">{cards.map(card=><button key={card.title} className={filter===card.filter?"active":""} onClick={()=>{setFilter(card.filter);setPage(0);}}><span>{card.title}</span><strong>{card.value}</strong></button>)}</section>{error&&<div className="api-error">{error}</div>}
  <section className="panel inventory-worklist"><div className="customers-toolbar"><div><h2>أرصدة الأصناف</h2><p>{loading?"جارٍ التحميل...":`${(apiBase?total:shown.length).toLocaleString("ar-SA")} صنف`}</p></div><div className="jobs-toolbar-actions"><select value={filter} onChange={event=>{setFilter(event.target.value as Filter);setPage(0);}}><option value="all">كل المخزون</option><option value="low">منخفض</option><option value="out">نافد</option></select><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="ابحث باسم الصنف أو SKU"/></div></div>{shown.length?<div className="table-wrap"><table><thead><tr><th>الصنف</th><th>تكلفة الوحدة</th><th>رصيد المستودعات</th><th>عهد الفنيين</th><th>حد الطلب</th><th>الحالة</th><th>الإجراء</th></tr></thead><tbody>{shown.map(item=><tr key={item.id}><td><strong>{item.name}</strong><small dir="ltr">{item.sku}</small></td><td><strong>{money(item.unit_cost)} ر.س</strong><small>{item.unit}</small></td><td><strong>{num(item.total_quantity)} {item.unit}</strong><small>{item.balances?.map(balance=>`${balance.warehouse_name}: ${num(balance.quantity)}`).join(" · ")||"دون رصيد"}</small></td><td><strong>{num(item.technician_quantity)} {item.unit}</strong></td><td>{num(item.reorder_level)}</td><td><span className={`stock-state ${item.stock_status}`}>{item.stock_status==="ok"?"متوفر":item.stock_status==="low"?"منخفض":"نافد"}</span></td><td>{canManage?<div className="inventory-actions"><button onClick={()=>{setAction("receive");setActionTarget(item);setFormError("");}}>استلام</button><button disabled={Number(item.total_quantity)<=0} onClick={()=>{setAction("technician-issue");setActionTarget(item);setFormError("");}}>صرف لفني</button><button disabled={Number(item.total_quantity)<=0} onClick={()=>{setAction("transfer");setActionTarget(item);setFormError("");}}>تحويل</button></div>:"—"}</td></tr>)}</tbody></table></div>:<div className="empty-state">لا توجد أصناف مطابقة.</div>}</section>
  <section className="panel inventory-movements"><div className="panel-head"><div><h2>أحدث الحركات</h2><p>سجل الاستلام والصرف والتحويل</p></div></div>{movements.length?<div className="movement-list">{movements.map(movement=><article key={movement.id}><span className={`movement-icon ${movement.movement_type}`}>{movementLabel(movement.movement_type)}</span><div><strong>{movement.item_name} · {num(movement.quantity)}</strong><small>{[movement.from_warehouse_name,movement.to_warehouse_name,movement.technician_id,movement.reference].filter(Boolean).join(" · ")}</small></div><time>{date.format(new Date(movement.created_at))}</time></article>)}</div>:<div className="empty-state">لا توجد حركات مخزون.</div>}</section>
  {itemModal&&<div className="modal-backdrop"><section className="customer-modal"><div className="modal-head"><div><h2>إضافة صنف مخزون</h2><p>تعريف الصنف وحد إعادة الطلب</p></div><button onClick={()=>setItemModal(false)}>×</button></div><form onSubmit={createItem}><label>رمز الصنف SKU<input name="sku" placeholder="MEM-75GPD"/></label><label>اسم الصنف<input name="name" placeholder="شمعة ممبرين 75 GPD"/></label><label>وحدة القياس<input name="unit" defaultValue="حبة"/></label><label>حد إعادة الطلب<input name="reorderLevel" type="number" min="0" defaultValue="5"/></label><label>تكلفة الوحدة<input name="unitCost" type="number" min="0" step="0.01" defaultValue="0"/></label>{formError&&<p className="form-error">{formError}</p>}<div className="modal-actions"><button className="secondary-button" type="button" onClick={()=>setItemModal(false)}>إلغاء</button><button className="primary-button" disabled={saving}>{saving?"جارٍ الحفظ...":"إضافة الصنف"}</button></div></form></section></div>}
  {actionTarget&&<div className="modal-backdrop"><section className="customer-modal inventory-modal"><div className="modal-head"><div><h2>{action==="receive"?"استلام مخزون":action==="technician-issue"?"صرف عهدة لفني":"تحويل بين المستودعات"}</h2><p>{actionTarget.name} · {actionTarget.sku}</p></div><button onClick={()=>setActionTarget(null)}>×</button></div><form onSubmit={saveMovement}><label>المستودع {action==="transfer"?"المصدر":""}<input name="warehouseId" defaultValue={actionTarget.balances?.[0]?.warehouse_id||"main-riyadh"}/></label>{action==="transfer"&&<label>المستودع الوجهة<input name="toWarehouseId" placeholder="warehouse-id"/></label>}{action==="technician-issue"&&<label>معرف الفني<input name="technicianId" placeholder="TECH-ID"/></label>}<label>الكمية<input name="quantity" type="number" min="0.01" step="0.01"/></label>{action==="receive"&&<label>تكلفة الوحدة<input name="unitCost" type="number" min="0" step="0.01" defaultValue={Number(actionTarget.unit_cost)}/></label>}<label>المرجع<input name="reference" placeholder="رقم أمر الشراء أو المهمة"/></label><label>ملاحظات<input name="notes"/></label>{formError&&<p className="form-error">{formError}</p>}<div className="modal-actions"><button className="secondary-button" type="button" onClick={()=>setActionTarget(null)}>إلغاء</button><button className="primary-button" disabled={saving}>{saving?"جارٍ الحفظ...":"تسجيل الحركة"}</button></div></form></section></div>}
 </div></main></PreviewAuthGuard>;
}
